# Advanced RAG — SEC Filings

**Pipeline**: Metadata Extraction → Query Rewriting → Multi-Query → Hybrid Search (BM25 + Dense + RRF) → CrossEncoder Reranking → Context Compression → LLM Generation with Citations

## What's new vs Baseline RAG?

| Stage | Baseline | Advanced |
|-------|----------|----------|
| Query prep | Raw query | Rewrite + 2 variants |
| Retrieval | Dense only | BM25 + Dense + RRF |
| Scope | All chunks | Metadata-filtered |
| Scoring | Cosine sim | CrossEncoder rerank |
| Context | Full chunks | Sentence-level compression |
| Answer | Plain text | Text with [n] citations |

Each improvement is independently motivated:
1. **Metadata filtering** — restricts search to the relevant company/year, reducing irrelevant noise
2. **Query rewriting** — aligns query vocabulary with financial document language
3. **Multi-query** — different phrasings capture different relevant chunks
4. **Hybrid BM25 + Dense** — BM25 handles exact financial term matching; dense handles semantic similarity
5. **CrossEncoder reranking** — more accurate relevance scoring than bi-encoder cosine similarity
6. **Context compression** — removes off-topic sentences, reduces LLM context noise
7. **Citation generation** — improves traceability and faithfulness

In [ ]:
print('hi')

hi

In [ ]:
# Uncomment to install dependencies
# !pip install sentence-transformers chromadb rank-bm25 groq python-dotenv pandas tqdm

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Verify the sqlite size is correct after mounting
import os
size = os.path.getsize("/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/chroma_db/chroma.sqlite3")
print(f"SQLite size: {size / 1024 / 1024:.1f} MB")  # should be ~250MB

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
SQLite size: 557.2 MB

In [ ]:
import os
os.environ["GEMINI_API_KEY"] = "AIzaSyD4Xwj4eCpjy5szY6DQ37CJfIoyXZD2UD8"

## 1. Configuration

In [ ]:
CONFIG = {
    # --- Paths (Google Drive) ---
    "chroma_db_path": "/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/chroma_db",
    "chunks_path":    "/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/sec_data/chunks/sec_chunks.jsonl",
    "eval_path":      "/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/GenAI Eval QA.csv",
    "results_dir":    "/content/results",

    # --- Models ---
    "dense_model_name":   "nomic-ai/nomic-embed-text-v1.5",
    "reranker_model_name":"cross-encoder/ms-marco-MiniLM-L-6-v2",
    "execution_profile":  "dev",
    "gemini_dev_model":   "gemini-2.5-flash-lite",
    "gemini_final_model": "gemini-2.5-flash-lite",
    "agent_model":        "gemini-2.5-flash-lite",
    "judge_model":        "gemini-2.5-flash",

    # --- Retrieval ---
    "bm25_top_k":        15,
    "dense_top_k":       15,
    "rerank_top_k":      7,
    "multi_query_n":     2,
    "rrf_k":             60,

    # --- Context compression ---
    "compress_top_sentences": 4,

    # --- Generation ---
    "max_context_chars":     9000,
    "temperature_rewriter":  0.2,
    "temperature_generator": 0.2,
    "temperature_judge":     0.1,
    "max_tokens_answer":     512,
    "max_tokens_judge":      256,

    # --- Cost tracking ---
    "gemini_cost_input_per_1m":  0.10,
    "gemini_cost_output_per_1m": 0.40,

    # --- Evaluation ---
    "eval_max_questions": None,       # ← ADD THIS. Set to None to run all

    # --- Rate limiting ---
    "max_rpm":                    10,
    "inter_question_sleep_sec":   40,
    "llm_max_retries":            3,
    "llm_retry_base_delay_sec":   5,
}

## 2. Imports & Setup

In [ ]:
import os
import re
import json
import time
import threading
from collections import deque, Counter as _Counter
from pathlib import Path
from typing import Optional
import re as _re

import numpy as np
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv
from pydantic import BaseModel, Field

import chromadb
from sentence_transformers import SentenceTransformer, CrossEncoder
from rank_bm25 import BM25Okapi
from google import genai
from google.genai import types as genai_types

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
assert GEMINI_API_KEY, "Set GEMINI_API_KEY in your .env file"

LLM_MODEL = (
    CONFIG["gemini_final_model"]
    if CONFIG["execution_profile"] == "final"
    else CONFIG["gemini_dev_model"]
)
print(f"Execution profile : {CONFIG['execution_profile']}")
print(f"LLM model         : {LLM_MODEL}")

Execution profile : dev
LLM model         : gemini-2.5-flash-lite

## 3. Load Models

In [ ]:
CONFIG["reranker_model_name"] = "cross-encoder/ms-marco-MiniLM-L-6-v2"

In [ ]:
print("Loading embedding model...")
embed_model = SentenceTransformer(
    CONFIG["dense_model_name"],
    trust_remote_code=True,
)
print(f"  ok {CONFIG['dense_model_name']}")

print("Loading reranker...")
reranker = CrossEncoder(CONFIG["reranker_model_name"])
print(f"  ok {CONFIG['reranker_model_name']}")

genai_client = genai.Client(api_key=GEMINI_API_KEY)
print(f"  ok Gemini client ready (model: {LLM_MODEL})")


# ── Rate Limiter ───────────────────────────────────────────────────────────────
class RateLimiter:
    def __init__(self, max_rpm: int):
        self.max_rpm = max_rpm
        self._ts: deque = deque()
        self._lock = threading.Lock()

    def wait(self):
        with self._lock:
            now = time.time()
            while self._ts and now - self._ts[0] >= 60.0:
                self._ts.popleft()
            if len(self._ts) >= self.max_rpm:
                sleep_for = 60.0 - (now - self._ts[0])
                if sleep_for > 0:
                    print(f"  [RateLimit] sleeping {sleep_for:.1f}s ...")
                    time.sleep(sleep_for)
            self._ts.append(time.time())

rate_limiter = RateLimiter(CONFIG["max_rpm"])


# ── Per-Question Token Accumulator ─────────────────────────────────────────────
_question_tokens: dict = {}

def _reset_question_tokens() -> None:
    global _question_tokens
    _question_tokens = {}

def _add_tokens(step: str, input_tok: int, output_tok: int) -> None:
    if step not in _question_tokens:
        _question_tokens[step] = {'input': 0, 'output': 0}
    _question_tokens[step]['input']  += int(input_tok  or 0)
    _question_tokens[step]['output'] += int(output_tok or 0)

def _get_question_token_totals() -> tuple:
    total_in  = sum(v['input']  for v in _question_tokens.values())
    total_out = sum(v['output'] for v in _question_tokens.values())
    return total_in, total_out

def _estimate_cost_usd(total_input: int, total_output: int) -> float:
    rate_in  = CONFIG.get('gemini_cost_input_per_1m',  0.10) / 1_000_000
    rate_out = CONFIG.get('gemini_cost_output_per_1m', 0.40) / 1_000_000
    return total_input * rate_in + total_output * rate_out


# ── LLM Call ───────────────────────────────────────────────────────────────────
def call_llm(
    messages: list,
    model: str = None,
    temperature: float = 0.2,
    max_tokens: int = 512,
    json_mode: bool = False,
    step: str = 'generate',
) -> str:
    """Call Gemini with retry. Accumulates tokens to _question_tokens[step]."""
    model = model or LLM_MODEL
    system_instruction = None
    user_parts = []
    for msg in messages:
        if msg["role"] == "system":
            system_instruction = msg["content"]
        else:
            user_parts.append(msg["content"])
    contents = "\n\n".join(user_parts) if user_parts else ""

    cfg_kwargs = dict(temperature=temperature, max_output_tokens=max_tokens)
    if json_mode:
        cfg_kwargs["response_mime_type"] = "application/json"
    if system_instruction:
        cfg_kwargs["system_instruction"] = system_instruction

    for attempt in range(CONFIG["llm_max_retries"]):
        try:
            rate_limiter.wait()
            resp = genai_client.models.generate_content(
                model=model,
                contents=contents,
                config=genai_types.GenerateContentConfig(**cfg_kwargs),
            )
            if step and resp.usage_metadata:
                _add_tokens(step,
                    resp.usage_metadata.prompt_token_count     or 0,
                    resp.usage_metadata.candidates_token_count or 0)
            return resp.text.strip()
        except Exception as e:
            delay = CONFIG["llm_retry_base_delay_sec"] * (2 ** attempt)
            print(f"  [WARN] attempt {attempt+1}/{CONFIG['llm_max_retries']} failed ({e}). Retrying in {delay}s...")
            time.sleep(delay)
    raise RuntimeError(f"LLM call failed after {CONFIG['llm_max_retries']} attempts")


# ── Heuristic Scoring Utilities ────────────────────────────────────────────────
def _tokenize(text: str) -> list:
    return _re.sub(r'[^\w\s]', '', text.lower()).split()

def token_f1_score(pred: str, ref: str) -> float:
    if not pred or not ref:
        return 0.0
    pred_toks = _tokenize(pred)
    ref_toks  = _tokenize(ref)
    if not pred_toks or not ref_toks:
        return 0.0
    common = sum((_Counter(pred_toks) & _Counter(ref_toks)).values())
    if common == 0:
        return 0.0
    precision = common / len(pred_toks)
    recall    = common / len(ref_toks)
    return 2 * precision * recall / (precision + recall)

def numerical_accuracy_score(pred: str, ref: str) -> Optional[float]:
    nums_ref  = [float(n.replace(',', '')) for n in _re.findall(r'-?\d[\d,]*\.?\d*', ref)]
    nums_pred = [float(n.replace(',', '')) for n in _re.findall(r'-?\d[\d,]*\.?\d*', pred)]
    if not nums_ref:
        return None
    hits = sum(
        1 for r in nums_ref
        if any(abs(p - r) / (abs(r) + 1e-9) < 0.01 for p in nums_pred)
    )
    return hits / len(nums_ref)

def compute_decision_from_text(answer_text: str) -> str:
    lower = answer_text.lower()
    refusal_phrases = [
        'insufficient', 'not contain', 'not available', 'cannot find',
        "don't have", 'no information', 'not provided', 'unable to',
        'not enough', 'not present', 'not found', 'insufficient data',
    ]
    return 'refuse' if any(p in lower for p in refusal_phrases) else 'answer'


# ── Structured Judge (matches CrewAI) ─────────────────────────────────────────
class JudgeOutput(BaseModel):
    score:          float = Field(default=0.0, description='Score 0.0-1.0')
    claims_covered: float = Field(default=0.0, description='Fraction of key facts covered 0.0-1.0')
    reason:         str   = Field(default='',  description='Short explanation')

def _build_correctness_prompt(question: str, reference_answer: str, candidate_answer: str) -> str:
    return (
        'Score the candidate answer against the reference answer from 0 to 1 for a financial QA task. '
        '1 = correct value, correct units, correct period. '
        '0 = wrong number, wrong company, wrong period, or completely missing. '
        'Give partial credit for answers close but with unit errors. '
        'Also set claims_covered: fraction of distinct facts/numbers in the reference present in the candidate. '
        'Return a valid JSON object only that matches the requested schema.\n\n'
        f'Question:\n{question}\n\n'
        f'Reference answer:\n{reference_answer}\n\n'
        f'Candidate answer:\n{candidate_answer}'
    )

def _build_faithfulness_prompt(question: str, context: str, candidate_answer: str) -> str:
    return (
        'Score how well the candidate answer is grounded in the retrieved filing context from 0 to 1. '
        '1 = every number and claim is directly supported by the context. '
        '0 = answer contains numbers or claims not present in the context (hallucinated). '
        'Also set claims_covered: fraction of claims in the candidate supported by the context. '
        'Return a valid JSON object only that matches the requested schema.\n\n'
        f'Question:\n{question}\n\n'
        f'Retrieved context:\n{context}\n\n'
        f'Candidate answer:\n{candidate_answer}'
    )

def _safe_judge_call(prompt_text: str, task_name: str) -> JudgeOutput:
    _fb = JudgeOutput(score=0.0, claims_covered=0.0, reason='judge fallback — all attempts failed')
    for attempt in range(CONFIG["llm_max_retries"]):
        try:
            rate_limiter.wait()
            response = genai_client.models.generate_content(
                model=CONFIG["judge_model"],
                contents=prompt_text,
                config=genai_types.GenerateContentConfig(
                    response_mime_type='application/json',
                    response_schema=JudgeOutput,
                    temperature=CONFIG.get('temperature_judge', 0.1),
                ),
            )
            if response.usage_metadata:
                _add_tokens(task_name,
                    response.usage_metadata.prompt_token_count     or 0,
                    response.usage_metadata.candidates_token_count or 0)
            result = response.parsed
            if result is None:
                result = JudgeOutput(**json.loads(response.text))
            return result
        except Exception as e:
            print(f"  [WARN] Judge ({task_name}) attempt {attempt+1} failed: {e}")
            if attempt < CONFIG["llm_max_retries"] - 1:
                time.sleep(CONFIG["llm_retry_base_delay_sec"] * (2 ** attempt))
    return _fb

def llm_judge_correctness(question: str, reference_answer: str, candidate_answer: str) -> tuple:
    result = _safe_judge_call(
        _build_correctness_prompt(question, reference_answer, candidate_answer),
        task_name='judge_correctness',
    )
    return (max(0.0, min(1.0, float(result.score))),
            max(0.0, min(1.0, float(result.claims_covered))),
            result.reason)

def llm_judge_faithfulness(question: str, context: str, candidate_answer: str) -> tuple:
    result = _safe_judge_call(
        _build_faithfulness_prompt(question, context[:CONFIG.get('max_context_chars', 9000)], candidate_answer),
        task_name='judge_faithfulness',
    )
    return (max(0.0, min(1.0, float(result.score))),
            max(0.0, min(1.0, float(result.claims_covered))),
            result.reason)

print("Client, rate limiter, token tracking, heuristics, and judge ready.")

Loading embedding model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/140 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/120 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

configuration_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- configuration_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_hf_nomic_bert.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- modeling_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors:   0%|          | 0.00/547M [00:00<?, ?B/s]

WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

  ok nomic-ai/nomic-embed-text-v1.5
Loading reranker...

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

  ok cross-encoder/ms-marco-MiniLM-L-6-v2
  ok Gemini client ready (model: gemini-2.5-flash-lite)
Client, rate limiter, token tracking, heuristics, and judge ready.

## 4. Load Data

In [ ]:
# --- ChromaDB ---
print("Connecting to ChromaDB...")
chroma_client = chromadb.PersistentClient(path=CONFIG["chroma_db_path"])
collections = chroma_client.list_collections()
collection = chroma_client.get_collection(collections[0].name)
print(f"  ok '{collections[0].name}'  ({collection.count():,} chunks)")

# --- JSONL chunks (needed for BM25) ---
print("Loading SEC chunks from JSONL...")
raw_chunks = []
with open(CONFIG["chunks_path"], "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            raw_chunks.append(json.loads(line))

chunks_df = pd.DataFrame(raw_chunks)

# Filter low-value chunks (matching the existing pipeline)
if "flag_low_value_combined" in chunks_df.columns:
    before = len(chunks_df)
    chunks_df = chunks_df[~chunks_df["flag_low_value_combined"].fillna(False)].reset_index(drop=True)
    print(f"  Filtered {before - len(chunks_df)} low-value chunks")

print(f"  ok {len(chunks_df):,} chunks loaded")


def make_contextual_chunk(row) -> str:
    """Reconstruct the contextual chunk text (must match what was stored in ChromaDB)."""
    company = row.get("company_name", row.get("company", "?"))
    ticker  = row.get("ticker", "?")
    form    = row.get("form_type", "?")
    date    = str(row.get("filing_date", "?"))[:10]
    year    = row.get("filing_year", "?")
    section = row.get("section_title", "?")
    text    = row.get("text", row.get("raw_chunk", ""))
    return (
        f"Company: {company} ({ticker})\n"
        f"Filing: {form} | Date: {date} | Year: {year}\n"
        f"Section: {section}\n"
        f"Content: {text}"
    )


# Build contextual chunks column and BM25 tokens
chunks_df["contextual_chunk"] = chunks_df.apply(make_contextual_chunk, axis=1)
chunks_df["bm25_tokens"] = chunks_df["contextual_chunk"].str.lower().str.split()

# Build BM25 index
print("Building BM25 index...")
bm25_index = BM25Okapi(chunks_df["bm25_tokens"].tolist())
print(f"  ok BM25 index built  ({len(chunks_df):,} documents)")

# --- Adjacent-chunk expansion lookup ---
# Maps chunk_id string -> DataFrame row index (for expand_adjacent)
_chunk_id_to_row = {str(row["chunk_id"]): idx for idx, row in chunks_df.iterrows()}

# Maps (ticker, form_type, filing_date) -> {chunk_index -> df_row_idx}
_filing_chunk_lookup: dict = {}
for idx, row in chunks_df.iterrows():
    key = (str(row["ticker"]), str(row["form_type"]), str(row.get("filing_date", ""))[:10])
    ci  = int(row.get("chunk_index", -1))
    if ci >= 0:
        _filing_chunk_lookup.setdefault(key, {})[ci] = idx

print(f"  ok adjacent-chunk lookup built  ({len(_filing_chunk_lookup)} filings)")

Connecting to ChromaDB...
  ok 'sec_sections'  (588 chunks)
Loading SEC chunks from JSONL...
  Filtered 550 low-value chunks
  ok 12,725 chunks loaded
Building BM25 index...
  ok BM25 index built  (12,725 documents)
  ok adjacent-chunk lookup built  (144 filings)

## 5. Step 1 — Metadata Extraction

Extract company ticker, filing year, and form type from the query to narrow retrieval scope.
This reduces the search space from ~12,600 chunks to only the relevant company/period.

In [ ]:
# Known tickers in the dataset
KNOWN_TICKERS = {
    "AAPL", "MSFT", "NVDA", "JPM", "BAC", "BRK.B", "BRK",
    "JNJ", "UNH", "XOM", "CVX", "WMT", "COST",
}

# Company name -> ticker mapping for natural language mentions
COMPANY_TO_TICKER = {
    "apple": "AAPL", "microsoft": "MSFT", "nvidia": "NVDA",
    "jpmorgan": "JPM", "jp morgan": "JPM", "bank of america": "BAC",
    "berkshire": "BRK.B", "johnson": "JNJ", "unitedhealth": "UNH",
    "exxon": "XOM", "exxonmobil": "XOM", "chevron": "CVX",
    "walmart": "WMT", "costco": "COST",
}


def extract_metadata(query: str) -> dict:
    """
    Extract ticker, filing_year, and form_type from query text.
    Uses regex for year/form_type and a lookup table for company names.
    Returns dict with None values for fields not found.
    """
    q_upper = query.upper()
    q_lower = query.lower()

    # --- Ticker ---
    ticker = None
    for t in KNOWN_TICKERS:
        if re.search(r"\b" + re.escape(t) + r"\b", q_upper):
            ticker = t
            break
    if ticker is None:
        for name, t in COMPANY_TO_TICKER.items():
            if name in q_lower:
                ticker = t
                break

    # --- Filing year (2020-2029) ---
    year_match = re.search(r"\b(202[0-9])\b", query)
    filing_year = int(year_match.group(1)) if year_match else None

    # --- Form type ---
    form_type = None
    if re.search(r"\b10-K\b|\bannual report\b|\bannual filing\b", query, re.IGNORECASE):
        form_type = "10-K"
    elif re.search(r"\b10-Q\b|\bquarterly report\b|\bquarterly filing\b", query, re.IGNORECASE):
        form_type = "10-Q"

    return {"ticker": ticker, "filing_year": filing_year, "form_type": form_type}


# Quick test
print(extract_metadata("What was Apple's revenue in fiscal 2024 10-K?"))
print(extract_metadata("Compare NVDA and MSFT operating income for 2023"))

{'ticker': 'AAPL', 'filing_year': 2024, 'form_type': '10-K'}
{'ticker': 'NVDA', 'filing_year': 2023, 'form_type': None}

## 6. Step 2 — Query Rewriting

Rewrite the user's question into a retrieval-optimised query.
Financial questions often use colloquial phrasing ("how much did they make") that doesn't match
document language ("net revenue", "operating income"). A single LLM call fixes the vocabulary mismatch.

In [ ]:
REWRITE_SYSTEM = (
    "You are a search query optimizer for SEC filings (10-K, 10-Q). "
    "Rewrite the user's question as a concise retrieval query that maximizes recall of relevant "
    "financial document chunks. Use precise financial terminology (e.g., 'net revenue', "
    "'operating income', 'diluted EPS'). Keep it under 25 words. "
    "Return only the rewritten query, nothing else."
)


def rewrite_query(query: str) -> str:
    """Rewrite query for better retrieval alignment with financial document language."""
    return call_llm(
        messages=[
            {"role": "system", "content": REWRITE_SYSTEM},
            {"role": "user",   "content": query},
        ],
        model=CONFIG["agent_model"],
        temperature=CONFIG["temperature_rewriter"],
        max_tokens=80,
    )

## 7. Step 3 — Multi-Query Generation

Generate additional query variants to increase retrieval coverage.
Different phrasings surface different relevant chunks — e.g., asking about "revenue growth"
and "year-over-year revenue change" may retrieve complementary passages.

In [ ]:
MULTI_QUERY_SYSTEM = (
    "Generate {n} alternative retrieval queries for the following question about SEC filings. "
    "Each variant should use different financial terminology or focus on a different aspect "
    "of the question to maximise retrieval coverage. "
    'Return a JSON object with key "queries" containing an array of {n} query strings.'
)


def generate_multi_queries(query: str, n: int = None) -> list:
    """Generate n alternative query variants for multi-query retrieval."""
    n = n or CONFIG["multi_query_n"]
    raw = call_llm(
        messages=[
            {"role": "system", "content": MULTI_QUERY_SYSTEM.format(n=n)},
            {"role": "user",   "content": query},
        ],
        model=CONFIG["agent_model"],
        temperature=CONFIG["temperature_rewriter"],
        max_tokens=200,
        json_mode=True,
    )
    try:
        data = json.loads(raw)
        return data.get("queries", [])[:n]
    except Exception:
        return []

## 8. Step 4 — Hybrid Search (BM25 + Dense + RRF)

BM25 excels at exact financial term matching ("EBITDA", "diluted EPS", specific dollar figures).
Dense retrieval excels at semantic similarity.
Reciprocal Rank Fusion (RRF) combines both ranked lists without requiring score normalisation.
Metadata filtering further restricts results to the relevant company/year.

In [ ]:
def build_bm25_mask(ticker=None, filing_year=None, form_type=None) -> np.ndarray:
    """Boolean mask to restrict BM25 search to matching metadata."""
    mask = np.ones(len(chunks_df), dtype=bool)
    if ticker:
        mask &= (chunks_df["ticker"].str.upper() == ticker.upper()).values
    if filing_year:
        mask &= (chunks_df["filing_year"].astype(int) == int(filing_year)).values
    if form_type:
        mask &= (chunks_df["form_type"].str.upper() == form_type.upper()).values
    return mask


def bm25_search(query: str, top_k: int, mask: np.ndarray = None) -> list:
    """BM25 retrieval over contextual chunks with optional metadata mask."""
    tokens = query.lower().split()
    scores = bm25_index.get_scores(tokens)
    if mask is not None:
        scores = scores * mask.astype(float)
    top_idx = np.argsort(scores)[::-1]
    # Keep only positive-scoring results
    top_idx = [i for i in top_idx if scores[i] > 0][:top_k]
    results = []
    for i in top_idx:
        row = chunks_df.iloc[i]
        results.append({
            "text":     row["contextual_chunk"],
            "metadata": {
                "ticker":      row.get("ticker", "?"),
                "form_type":   row.get("form_type", "?"),
                "filing_year": int(row.get("filing_year", 0)),
                "company":     row.get("company_name", row.get("company", "?")),
            },
            "score":    float(scores[i]),
            "chunk_id": str(row.get("chunk_id", i)),
        })
    return results


def dense_search(query: str, top_k: int, ticker=None, filing_year=None, form_type=None) -> list:
    """Dense (semantic) retrieval with optional ChromaDB metadata filtering."""
    query_vec = embed_model.encode("search_query: " + query, normalize_embeddings=True).tolist()

    filters = []
    if ticker:
        filters.append({"ticker": {"$eq": ticker}})
    if filing_year:
        filters.append({"filing_year": {"$eq": int(filing_year)}})
    if form_type:
        filters.append({"form_type": {"$eq": form_type}})

    kwargs = dict(
        query_embeddings=[query_vec],
        n_results=min(top_k, collection.count()),
        include=["documents", "metadatas", "distances"],
    )

    if len(filters) == 1:
        kwargs["where"] = filters[0]
    elif len(filters) > 1:
        kwargs["where"] = {"$and": filters}

    results = collection.query(**kwargs)

    chunks = []
    for doc, meta, dist, cid in zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0],
        results["ids"][0],
    ):
        chunks.append({
            "text": doc,
            "metadata": meta,
            "score": float(1.0 - dist),
            "chunk_id": cid,
        })

    return chunks


def rrf_merge(result_lists: list, k: int = None) -> list:
    """
    Reciprocal Rank Fusion over multiple ranked lists.
    Formula: score(d) = sum_i 1 / (k + rank_i(d) + 1)
    """
    k = k or CONFIG["rrf_k"]
    scores = {}
    pool   = {}
    for ranked_list in result_lists:
        for rank, chunk in enumerate(ranked_list):
            cid = chunk["chunk_id"]
            scores[cid] = scores.get(cid, 0.0) + 1.0 / (k + rank + 1)
            if cid not in pool:
                pool[cid] = chunk
    merged = []
    for cid in sorted(scores, key=scores.__getitem__, reverse=True):
        c = dict(pool[cid])
        c["score"] = scores[cid]
        merged.append(c)
    return merged


def expand_adjacent(candidates: list, expand_n: int = 1) -> list:
    """
    For each chunk in the RRF pool, add the immediately preceding and following
    chunks within the same filing to the candidate pool (score=0.0).
    These extras enter the CrossEncoder reranking pool — the reranker then decides
    whether they're actually relevant, recovering table headers split from data rows.
    """
    existing_ids = {c["chunk_id"] for c in candidates}
    extras = {}

    for chunk in candidates:
        row_idx = _chunk_id_to_row.get(chunk["chunk_id"])
        if row_idx is None:
            continue
        row     = chunks_df.iloc[row_idx]
        base_ci = int(row.get("chunk_index", -1))
        if base_ci < 0:
            continue
        key    = (str(row["ticker"]), str(row["form_type"]), str(row.get("filing_date", ""))[:10])
        ci_map = _filing_chunk_lookup.get(key, {})

        for delta in range(-expand_n, expand_n + 1):
            if delta == 0:
                continue
            adj_idx = ci_map.get(base_ci + delta)
            if adj_idx is None:
                continue
            adj_row = chunks_df.iloc[adj_idx]
            adj_id  = str(adj_row["chunk_id"])
            if adj_id in existing_ids or adj_id in extras:
                continue
            extras[adj_id] = {
                "text":     adj_row["contextual_chunk"],
                "metadata": {
                    "ticker":      adj_row.get("ticker", "?"),
                    "form_type":   adj_row.get("form_type", "?"),
                    "filing_year": int(adj_row.get("filing_year", 0)),
                    "company":     adj_row.get("company_name", adj_row.get("company", "?")),
                },
                "score":    0.0,
                "chunk_id": adj_id,
            }

    return candidates + list(extras.values())

## 9. Step 5 — CrossEncoder Reranking

The bi-encoder embedding model scores query and document independently (fast but approximate).
The CrossEncoder attends to both simultaneously, giving more accurate relevance scores.
Applied to the top RRF candidates to select the final context.

In [ ]:
def rerank(candidates: list, query: str, top_k: int = None) -> list:
    """Rerank candidate chunks using CrossEncoder (query, chunk) scoring."""
    top_k = top_k or CONFIG["rerank_top_k"]
    if not candidates:
        return []
    pairs  = [(query, c["text"]) for c in candidates]
    scores = reranker.predict(pairs, show_progress_bar=False)
    for c, s in zip(candidates, scores):
        c["rerank_score"] = float(s)
    return sorted(candidates, key=lambda x: x["rerank_score"], reverse=True)[:top_k]

## 10. Step 6 — Context Compression

Each retrieved chunk may contain irrelevant sentences.
We extract only the most relevant sentences (scored by CrossEncoder against the query),
reducing noise in the LLM context window.

In [ ]:
def compress_chunk(chunk: dict, query: str, top_n: int = None) -> dict:
    """
    Extract the most relevant sentences from a chunk using CrossEncoder scoring.
    Keeps the structured header (Company/Filing/Section) and replaces the content
    with only the top-N most relevant sentences.
    """
    top_n = top_n or CONFIG["compress_top_sentences"]
    if top_n is None:
        return chunk  # compression disabled

    text = chunk["text"]

    # Separate header (Company/Filing/Section lines) from content
    if "\nContent:" in text:
        header, _, content = text.partition("\nContent:")
        header = header + "\nContent:"
    else:
        header = ""
        content = text

    # Simple sentence splitting (handles ., !, ?, ;)
    sentences = re.split(r"(?<=[.!?;])\s+", content.strip())
    sentences = [s.strip() for s in sentences if len(s.strip()) > 25]

    if len(sentences) <= top_n:
        return chunk  # already short enough

    # Score each sentence against the query
    pairs  = [(query, s) for s in sentences]
    scores = reranker.predict(pairs, show_progress_bar=False)

    # Keep top-N sentences in original document order
    top_idx = sorted(
        sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:top_n]
    )
    compressed_content = " ".join(sentences[i] for i in top_idx)

    new_chunk = dict(chunk)
    new_chunk["text"] = (header + " " + compressed_content).strip()
    new_chunk["compressed"] = True
    return new_chunk


def compress_context(chunks: list, query: str) -> list:
    """Compress all chunks in the context."""
    return [compress_chunk(c, query) for c in chunks]

## 11. Step 7 — Generation with Citations

Instructs the LLM to cite source chunks using [n] notation.
This improves traceability and allows users to verify claims against the original filings.

In [ ]:
GENERATOR_SYSTEM_ADV = (
    "You are a financial analyst answering questions using only the retrieved filing context.\n"
    "Rules:\n"
    "- Be precise with numbers -- include units (millions, billions, %), fiscal periods, and line item names.\n"
    "- Cite your sources using [n] notation after each claim (e.g., 'Revenue was $394B in FY2024 [1]').\n"
    "- Only use information present in the provided context.\n"
    "- If the context does not contain enough information, say 'Insufficient information in the provided filings.'"
)


def format_context_adv(chunks: list, max_chars: int = None) -> str:
    """Format chunks with numbered headers for citation."""
    max_chars = max_chars or CONFIG["max_context_chars"]
    parts = []
    for i, c in enumerate(chunks, 1):
        m = c["metadata"]
        header = (
            f"[{i}] {m.get('ticker','?')} {m.get('form_type','?')} "
            f"{m.get('filing_year','?')} | {m.get('company','')}"
        )
        parts.append(f"{header}\n{c['text']}")
    context = "\n\n---\n\n".join(parts)
    return context[:max_chars]


def generate_with_citations(query: str, chunks: list) -> str:
    """Generate an answer with [n] citations referencing the retrieved chunks."""
    context  = format_context_adv(chunks)
    user_msg = f"Question:\n{query}\n\nRetrieved context (cite [n] for each claim):\n{context}"
    return call_llm(
        messages=[
            {"role": "system", "content": GENERATOR_SYSTEM_ADV},
            {"role": "user",   "content": user_msg},
        ],
        temperature=CONFIG["temperature_generator"],
        max_tokens=CONFIG["max_tokens_answer"],
    )

## 12. Full Advanced RAG Pipeline

In [ ]:
def advanced_rag(query: str, verbose: bool = False) -> dict:
    """
    Advanced RAG pipeline:
    1. Metadata extraction  -> filter to relevant company/year
    2. Query rewriting      -> align with financial document vocabulary
    3. Multi-query          -> generate additional query variants
    4. Hybrid retrieval     -> BM25 + Dense for each query variant
    5. RRF merge            -> combine all ranked lists
    6. Adjacent expansion   -> add neighboring chunks to recover split tables
    7. CrossEncoder rerank  -> accurate relevance re-scoring
    8. Context compression  -> keep only most relevant sentences
    9. Generation           -> answer with [n] citations
    """
    # 1. Metadata extraction
    meta = extract_metadata(query)
    if verbose:
        print(f"  [Meta]     {meta}")

    # 2. Query rewriting
    rewritten = rewrite_query(query)
    if verbose:
        print(f"  [Rewrite]  {rewritten}")

    # 3. Multi-query generation
    variants    = generate_multi_queries(rewritten)
    all_queries = [rewritten] + variants
    if verbose:
        print(f"  [Queries]  {all_queries}")

    # 4. Hybrid retrieval (BM25 + Dense) for each query variant
    bm25_mask    = build_bm25_mask(**meta)
    ranked_lists = []
    for q in all_queries:
        ranked_lists.append(bm25_search(q, CONFIG["bm25_top_k"], bm25_mask))
        ranked_lists.append(dense_search(q, CONFIG["dense_top_k"], **meta))

    # 5. RRF merge
    candidates = rrf_merge(ranked_lists)
    if verbose:
        print(f"  [RRF]      {len(candidates)} unique candidates after merge")

    # 6. Adjacent expansion — add chunk_index ± 1 within the same filing
    candidates = expand_adjacent(candidates, expand_n=1)
    if verbose:
        print(f"  [Expand]   {len(candidates)} candidates after adjacent expansion")

    # 7. CrossEncoder reranking
    reranked = rerank(candidates, rewritten)
    if verbose:
        print(f"  [Rerank]   top {len(reranked)} chunks selected")

    # 8. Context compression
    compressed = compress_context(reranked, rewritten)

    # 9. Generation with citations
    context = format_context_adv(compressed)
    answer  = generate_with_citations(query, compressed)

    return {
        "query":      query,
        "rewritten":  rewritten,
        "variants":   variants,
        "metadata":   meta,
        "answer":     answer,
        "chunks":     reranked,
        "context":    context,
        "n_chunks":   len(reranked),
    }

### Quick Demo

In [ ]:
demo_q = "What was Apple's total net revenue for fiscal year 2024?"
result = advanced_rag(demo_q, verbose=True)

print()
print("QUESTION:", result["query"])
print()
print("ANSWER:", result["answer"])
print()
print(f"Metadata extracted : {result['metadata']}")
print(f"Rewritten query    : {result['rewritten']}")
print(f"Query variants     : {result['variants']}")
print()
print(f"Retrieved {result['n_chunks']} chunks:")
for i, c in enumerate(result["chunks"], 1):
    m = c["metadata"]
    score = c.get("rerank_score", c.get("score", 0))
    compressed = "(compressed)" if c.get("compressed") else ""
    print(f"  [{i}] {m.get('ticker','?'):6s}  {m.get('form_type','?'):5s}  "
          f"year={m.get('filing_year','?')}  rerank={score:.3f}  {compressed}")

  [Meta]     {'ticker': 'AAPL', 'filing_year': 2024, 'form_type': None}
  [Rewrite]  Apple net revenue fiscal year 2024
  [Queries]  ['Apple net revenue fiscal year 2024', 'Apple Inc. total sales revenue 2024 fiscal period', 'Apple Inc. consolidated statements of operations net sales FY24']
  [RRF]      23 unique candidates after merge
  [Expand]   43 candidates after adjacent expansion
  [Rerank]   top 7 chunks selected

QUESTION: What was Apple's total net revenue for fiscal year 2024?

ANSWER: Apple's total net revenue for fiscal year 2024 was $391,035 million [6].

Metadata extracted : {'ticker': 'AAPL', 'filing_year': 2024, 'form_type': None}
Rewritten query    : Apple net revenue fiscal year 2024
Query variants     : ['Apple Inc. total sales revenue 2024 fiscal period', 'Apple Inc. consolidated statements of operations net sales FY24']

Retrieved 7 chunks:
  [1] AAPL    10-Q   year=2024  rerank=8.386
  [2] AAPL    10-Q   year=2024  rerank=7.750
  [3] AAPL    10-Q   year=2024  rerank=6.672
  [4] AAPL    10-Q   year=2024  rerank=6.189
  [5] AAPL    10-Q   year=2024  rerank=5.670
  [6] AAPL    10-K   year=2024  rerank=5.662
  [7] AAPL    10-Q   year=2024  rerank=5.442

## 13. Evaluation (LLM-as-Judge)

Same judge prompts as Baseline RAG for fair comparison.
Results are saved to `./results/advanced_results.csv`.

In [ ]:
CONFIG["eval_path"]

'/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/GenAI Eval QA.csv'

In [ ]:
eval_df = pd.read_csv(CONFIG["eval_path"])
# no split filter — load everything
if CONFIG.get("eval_max_questions"):
    eval_df = eval_df.head(CONFIG["eval_max_questions"])

print(f"Total questions : {len(eval_df)}")
print(eval_df["question_type"].value_counts().to_string())

Total questions : 100
question_type
extractive     25
paraphrased    25
reasoning      25
adversarial    25

In [ ]:
results = []

for idx, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc="Evaluating advanced"):
    question          = str(row["question"])
    reference_answer  = str(row["expected_answer"]).strip()
    question_id       = row.get("question_id", idx)
    question_type     = row.get("question_type", "unknown")
    company           = row.get("company", "")
    ticker            = row.get("ticker", "")
    form_type         = row.get("form_type", "")
    filing_year       = row.get("filing_year", None)
    expected_decision = str(row.get("expected_decision", "answer")).lower().strip()

    print(f'\nQ{idx+1}/{len(eval_df)} [{question_type}]  {ticker}  {filing_year}')

    # ── Reset token accumulator ────────────────────────────────────────────────
    _reset_question_tokens()

    # ── Run pipeline ──────────────────────────────────────────────────────────
    t0 = time.time()
    rag = advanced_rag(question)
    latency_sec  = round(time.time() - t0, 2)
    final_answer = rag["answer"]
    context      = rag["context"]

    # ── Heuristic scores ───────────────────────────────────────────────────────
    t_f1    = token_f1_score(final_answer, reference_answer) if reference_answer else None
    num_acc = numerical_accuracy_score(final_answer, reference_answer) if reference_answer else None
    predicted_decision = compute_decision_from_text(final_answer)
    decision_accuracy  = 1.0 if predicted_decision == expected_decision else 0.0

    # ── LLM Judge ──────────────────────────────────────────────────────────────
    is_unanswerable = (
        str(row.get("expected_answer", "")).strip().lower() in ("nan", "", "none")
        or expected_decision == "refuse"
    )
    if is_unanswerable:
        c_score   = decision_accuracy
        c_covered = decision_accuracy
        c_reason  = "Adversarial: scored by decision accuracy (refuse=correct)"
        f_score, _, f_reason = llm_judge_faithfulness(question, context, final_answer)
    else:
        c_score, c_covered, c_reason = llm_judge_correctness(question, reference_answer, final_answer)
        f_score, _,         f_reason = llm_judge_faithfulness(question, context, final_answer)

    # ── Token / cost summary ───────────────────────────────────────────────────
    gen_tok   = _question_tokens.get('generate',          {'input': 0, 'output': 0})
    corr_tok  = _question_tokens.get('judge_correctness', {'input': 0, 'output': 0})
    faith_tok = _question_tokens.get('judge_faithfulness',{'input': 0, 'output': 0})
    total_in, total_out = _get_question_token_totals()
    est_cost = _estimate_cost_usd(total_in, total_out)

    f1_str = f"{t_f1:.2f}" if t_f1 is not None else "N/A"
    print(f'  corr={c_score:.2f}  faith={f_score:.2f}  f1={f1_str}  '\
          f'tokens={total_in}in/{total_out}out  est=${est_cost:.5f}')

    results.append({
        "question_id":              question_id,
        "question":                 question,
        "question_type":            question_type,
        "company":                  company,
        "ticker":                   ticker,
        "form_type":                form_type,
        "filing_year":              filing_year,
        "reference_answer":         reference_answer,
        "expected_decision":        expected_decision,
        "final_answer":             final_answer,
        "pipeline":                 "advanced_rag",
        "n_chunks":                 rag["n_chunks"],
        "rewritten_query":          rag["rewritten"],
        "latency_sec":              latency_sec,
        "token_f1":                 t_f1,
        "numerical_accuracy":       num_acc,
        "decision_accuracy":        decision_accuracy,
        "predicted_decision":       predicted_decision,
        "llm_correctness_score":    c_score,
        "llm_claims_covered":       c_covered,
        "llm_correctness_reason":   c_reason,
        "llm_faithfulness_score":   f_score,
        "llm_faithfulness_reason":  f_reason,
        "model_generator":          LLM_MODEL,
        "model_judge_correctness":  CONFIG["judge_model"],
        "model_judge_faithfulness": CONFIG["judge_model"],
        "tokens_generate_input":    gen_tok["input"],
        "tokens_generate_output":   gen_tok["output"],
        "tokens_judge_corr_input":  corr_tok["input"],
        "tokens_judge_corr_output": corr_tok["output"],
        "tokens_judge_faith_input": faith_tok["input"],
        "tokens_judge_faith_output":faith_tok["output"],
        "tokens_total_input":       total_in,
        "tokens_total_output":      total_out,
        "est_cost_usd":             est_cost,
    })
    time.sleep(CONFIG["inter_question_sleep_sec"])

results_df = pd.DataFrame(results)
Path(CONFIG["results_dir"]).mkdir(parents=True, exist_ok=True)
out_path = Path(CONFIG["results_dir"]) / "advanced_results.csv"
results_df.to_csv(out_path, index=False)
print(f"\nSaved {len(results_df)} rows -> {out_path}")

Evaluating advanced:   0%|          | 0/100 [00:00<?, ?it/s]

Q1/100 [extractive]  AAPL  2023.0
  corr=0.99  faith=1.00  f1=0.78  tokens=7763in/213out  est=$0.00086

Evaluating advanced:   1%|          | 1/100 [01:25<2:21:11, 85.57s/it]

Q2/100 [extractive]  AAPL  2025.0
  corr=0.70  faith=1.00  f1=0.62  tokens=4053in/283out  est=$0.00052

Evaluating advanced:   2%|▏         | 2/100 [02:55<2:23:36, 87.93s/it]

Q3/100 [extractive]  MSFT  2023.0
  corr=0.35  faith=1.00  f1=0.24  tokens=10039in/353out  est=$0.00115

Evaluating advanced:   3%|▎         | 3/100 [04:27<2:25:45, 90.16s/it]

Q4/100 [extractive]  MSFT  2023.0
  corr=1.00  faith=1.00  f1=0.84  tokens=10545in/223out  est=$0.00114

Evaluating advanced:   4%|▍         | 4/100 [05:45<2:16:26, 85.27s/it]

Q5/100 [extractive]  NVDA  2025.0
  corr=0.60  faith=1.00  f1=0.18  tokens=6407in/266out  est=$0.00075

Evaluating advanced:   5%|▌         | 5/100 [07:05<2:11:52, 83.29s/it]

Q6/100 [extractive]  NVDA  2024.0
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  [WARN] attempt 2/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 10s...
  corr=1.00  faith=1.00  f1=0.36  tokens=7019in/218out  est=$0.00079

Evaluating advanced:   6%|▌         | 6/100 [08:40<2:16:28, 87.11s/it]

Q7/100 [extractive]  NVDA  2025.0
  corr=0.00  faith=1.00  f1=0.11  tokens=7744in/188out  est=$0.00085

Evaluating advanced:   7%|▋         | 7/100 [10:03<2:13:21, 86.04s/it]

Q8/100 [extractive]  JPM  2023.0
  corr=0.00  faith=1.00  f1=0.32  tokens=9833in/281out  est=$0.00110

Evaluating advanced:   8%|▊         | 8/100 [11:49<2:21:38, 92.37s/it]

Q9/100 [extractive]  JPM  2024.0
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  corr=1.00  faith=1.00  f1=0.18  tokens=3854in/336out  est=$0.00052

Evaluating advanced:   9%|▉         | 9/100 [13:11<2:14:59, 89.01s/it]

Q10/100 [extractive]  BAC  2025.0
  corr=0.00  faith=1.00  f1=0.00  tokens=9855in/194out  est=$0.00106

Evaluating advanced:  10%|█         | 10/100 [14:36<2:11:52, 87.91s/it]

Q11/100 [extractive]  BAC  2024.0
  corr=0.70  faith=1.00  f1=0.29  tokens=8207in/320out  est=$0.00095

Evaluating advanced:  11%|█         | 11/100 [16:27<2:20:55, 95.00s/it]

Q12/100 [extractive]  BRK-B  2025.0
  corr=0.00  faith=1.00  f1=0.10  tokens=590in/165out  est=$0.00013

Evaluating advanced:  12%|█▏        | 12/100 [17:13<1:57:23, 80.04s/it]

Q13/100 [extractive]  BRK-B  2023.0
  corr=0.00  faith=1.00  f1=0.06  tokens=640in/162out  est=$0.00013

Evaluating advanced:  13%|█▎        | 13/100 [17:59<1:41:00, 69.66s/it]

Q14/100 [extractive]  JNJ  2025.0
  corr=0.00  faith=0.00  f1=0.10  tokens=8147in/183out  est=$0.00089

Evaluating advanced:  14%|█▍        | 14/100 [19:19<1:44:05, 72.63s/it]

Q15/100 [extractive]  JNJ  2025.0
  corr=0.10  faith=1.00  f1=0.58  tokens=8966in/237out  est=$0.00099

Evaluating advanced:  15%|█▌        | 15/100 [20:49<1:50:34, 78.05s/it]

Q16/100 [extractive]  UNH  2024.0
  corr=0.98  faith=0.00  f1=0.64  tokens=9624in/376out  est=$0.00111

Evaluating advanced:  16%|█▌        | 16/100 [22:30<1:58:43, 84.80s/it]

Q17/100 [extractive]  UNH  2023.0
  corr=0.60  faith=1.00  f1=0.52  tokens=9736in/259out  est=$0.00108

Evaluating advanced:  17%|█▋        | 17/100 [23:47<1:54:05, 82.48s/it]

Q18/100 [extractive]  XOM  2023.0
  corr=0.95  faith=1.00  f1=0.63  tokens=8177in/218out  est=$0.00090

Evaluating advanced:  18%|█▊        | 18/100 [25:02<1:49:43, 80.28s/it]

Q19/100 [extractive]  XOM  2025.0
  corr=1.00  faith=1.00  f1=0.83  tokens=8836in/214out  est=$0.00097

Evaluating advanced:  19%|█▉        | 19/100 [26:26<1:49:55, 81.43s/it]

Q20/100 [extractive]  CVX  2024.0
  corr=0.00  faith=1.00  f1=0.00  tokens=6414in/194out  est=$0.00072

Evaluating advanced:  20%|██        | 20/100 [27:48<1:48:48, 81.61s/it]

Q21/100 [extractive]  CVX  2025.0
  corr=1.00  faith=1.00  f1=0.88  tokens=4153in/181out  est=$0.00049

Evaluating advanced:  21%|██        | 21/100 [29:04<1:45:21, 80.01s/it]

Q22/100 [extractive]  WMT  2023.0
  corr=1.00  faith=1.00  f1=0.44  tokens=5537in/225out  est=$0.00064

Evaluating advanced:  22%|██▏       | 22/100 [30:22<1:43:05, 79.30s/it]

Q23/100 [extractive]  WMT  2025.0
  corr=0.00  faith=1.00  f1=0.00  tokens=7120in/157out  est=$0.00077

Evaluating advanced:  23%|██▎       | 23/100 [31:42<1:41:53, 79.39s/it]

Q24/100 [extractive]  COST  2025.0
  corr=1.00  faith=1.00  f1=0.54  tokens=8784in/299out  est=$0.00100

Evaluating advanced:  24%|██▍       | 24/100 [33:01<1:40:36, 79.43s/it]

Q25/100 [extractive]  COST  2023.0
  corr=0.00  faith=1.00  f1=0.09  tokens=8224in/176out  est=$0.00089

Evaluating advanced:  25%|██▌       | 25/100 [34:21<1:39:29, 79.60s/it]

Q26/100 [paraphrased]  AAPL  2023.0
  corr=1.00  faith=1.00  f1=0.46  tokens=5153in/228out  est=$0.00061

Evaluating advanced:  26%|██▌       | 26/100 [35:35<1:36:04, 77.89s/it]

Q27/100 [paraphrased]  AAPL  2025.0
  corr=0.60  faith=1.00  f1=0.49  tokens=3965in/277out  est=$0.00051

Evaluating advanced:  27%|██▋       | 27/100 [36:56<1:35:57, 78.86s/it]

Q28/100 [paraphrased]  MSFT  2023.0
  corr=0.00  faith=1.00  f1=0.03  tokens=10801in/287out  est=$0.00119

Evaluating advanced:  28%|██▊       | 28/100 [38:24<1:37:49, 81.53s/it]

Q29/100 [paraphrased]  MSFT  2023.0
  corr=0.00  faith=1.00  f1=0.53  tokens=4627in/248out  est=$0.00056

Evaluating advanced:  29%|██▉       | 29/100 [40:02<1:42:18, 86.46s/it]

Q30/100 [paraphrased]  NVDA  2025.0
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  corr=1.00  faith=1.00  f1=0.39  tokens=6406in/236out  est=$0.00074

Evaluating advanced:  30%|███       | 30/100 [41:21<1:38:09, 84.14s/it]

Q31/100 [paraphrased]  NVDA  2024.0
  corr=1.00  faith=1.00  f1=0.55  tokens=6019in/183out  est=$0.00068

Evaluating advanced:  31%|███       | 31/100 [42:37<1:33:59, 81.73s/it]

Q32/100 [paraphrased]  NVDA  2025.0
  corr=0.00  faith=1.00  f1=0.11  tokens=7788in/174out  est=$0.00085

Evaluating advanced:  32%|███▏      | 32/100 [43:59<1:32:51, 81.93s/it]

Q33/100 [paraphrased]  JPM  2023.0
  corr=0.00  faith=0.00  f1=0.34  tokens=8876in/335out  est=$0.00102

Evaluating advanced:  33%|███▎      | 33/100 [45:33<1:35:29, 85.51s/it]

Q34/100 [paraphrased]  JPM  2024.0
  corr=1.00  faith=1.00  f1=0.37  tokens=3982in/220out  est=$0.00049

Evaluating advanced:  34%|███▍      | 34/100 [46:52<1:32:00, 83.65s/it]

Q35/100 [paraphrased]  BAC  2025.0
  corr=1.00  faith=1.00  f1=0.83  tokens=9368in/185out  est=$0.00101

Evaluating advanced:  35%|███▌      | 35/100 [48:21<1:32:21, 85.26s/it]

Q36/100 [paraphrased]  BAC  2024.0
  corr=0.05  faith=1.00  f1=0.16  tokens=5402in/260out  est=$0.00064

Evaluating advanced:  36%|███▌      | 36/100 [50:00<1:35:06, 89.16s/it]

Q37/100 [paraphrased]  BRK-B  2025.0
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  corr=0.00  faith=1.00  f1=0.10  tokens=583in/133out  est=$0.00011

Evaluating advanced:  37%|███▋      | 37/100 [50:56<1:23:27, 79.49s/it]

Q38/100 [paraphrased]  BRK-B  2023.0
  [RateLimit] sleeping 1.0s ...
  [RateLimit] sleeping 3.9s ...
  corr=0.00  faith=1.00  f1=0.06  tokens=646in/154out  est=$0.00013

Evaluating advanced:  38%|███▊      | 38/100 [51:47<1:13:13, 70.86s/it]

Q39/100 [paraphrased]  JNJ  2025.0
  corr=0.00  faith=1.00  f1=0.10  tokens=8922in/205out  est=$0.00097

Evaluating advanced:  39%|███▉      | 39/100 [53:06<1:14:32, 73.32s/it]

Q40/100 [paraphrased]  JNJ  2025.0
  corr=0.10  faith=1.00  f1=0.36  tokens=9009in/239out  est=$0.00100

Evaluating advanced:  40%|████      | 40/100 [54:23<1:14:22, 74.37s/it]

Q41/100 [paraphrased]  UNH  2024.0
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  corr=0.00  faith=1.00  f1=0.12  tokens=9690in/183out  est=$0.00104

Evaluating advanced:  41%|████      | 41/100 [55:58<1:19:08, 80.48s/it]

Q42/100 [paraphrased]  UNH  2023.0
  corr=0.85  faith=1.00  f1=0.37  tokens=9780in/267out  est=$0.00108

Evaluating advanced:  42%|████▏     | 42/100 [57:12<1:16:04, 78.70s/it]

Q43/100 [paraphrased]  XOM  2023.0
  corr=0.98  faith=1.00  f1=0.06  tokens=11311in/384out  est=$0.00128

Evaluating advanced:  43%|████▎     | 43/100 [58:28<1:13:50, 77.72s/it]

Q44/100 [paraphrased]  XOM  2025.0
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  corr=1.00  faith=1.00  f1=0.82  tokens=8558in/248out  est=$0.00096

Evaluating advanced:  44%|████▍     | 44/100 [59:56<1:15:37, 81.02s/it]

Q45/100 [paraphrased]  CVX  2024.0
  corr=1.00  faith=1.00  f1=0.47  tokens=8041in/204out  est=$0.00089

Evaluating advanced:  45%|████▌     | 45/100 [1:01:16<1:13:45, 80.47s/it]

Q46/100 [paraphrased]  CVX  2025.0
  corr=1.00  faith=1.00  f1=0.33  tokens=8968in/191out  est=$0.00097

Evaluating advanced:  46%|████▌     | 46/100 [1:02:45<1:14:49, 83.14s/it]

Q47/100 [paraphrased]  WMT  2023.0
  corr=1.00  faith=1.00  f1=0.48  tokens=5734in/223out  est=$0.00066

Evaluating advanced:  47%|████▋     | 47/100 [1:04:02<1:11:44, 81.22s/it]

Q48/100 [paraphrased]  WMT  2025.0
  corr=0.00  faith=1.00  f1=0.00  tokens=8439in/170out  est=$0.00091

Evaluating advanced:  48%|████▊     | 48/100 [1:05:28<1:11:39, 82.68s/it]

Q49/100 [paraphrased]  COST  2025.0
  corr=0.00  faith=1.00  f1=0.31  tokens=8183in/283out  est=$0.00093

Evaluating advanced:  49%|████▉     | 49/100 [1:07:03<1:13:23, 86.34s/it]

Q50/100 [paraphrased]  COST  2023.0
  corr=0.00  faith=1.00  f1=0.09  tokens=9660in/213out  est=$0.00105

Evaluating advanced:  50%|█████     | 50/100 [1:08:23<1:10:32, 84.66s/it]

Q51/100 [reasoning]  AAPL  2023.0
  corr=1.00  faith=1.00  f1=0.37  tokens=6882in/305out  est=$0.00081

Evaluating advanced:  51%|█████     | 51/100 [1:09:44<1:08:05, 83.39s/it]

Q52/100 [reasoning]  AAPL  2025.0
  corr=1.00  faith=1.00  f1=0.33  tokens=7457in/388out  est=$0.00090

Evaluating advanced:  52%|█████▏    | 52/100 [1:10:59<1:04:38, 80.80s/it]

Q53/100 [reasoning]  MSFT  2023.0
  corr=1.00  faith=1.00  f1=0.52  tokens=9023in/265out  est=$0.00101

Evaluating advanced:  53%|█████▎    | 53/100 [1:12:16<1:02:24, 79.67s/it]

Q54/100 [reasoning]  MSFT  2024.0
  corr=0.95  faith=1.00  f1=0.23  tokens=11238in/296out  est=$0.00124

Evaluating advanced:  54%|█████▍    | 54/100 [1:13:37<1:01:30, 80.23s/it]

Q55/100 [reasoning]  NVDA  2024.0
  corr=0.00  faith=0.00  f1=0.39  tokens=8758in/392out  est=$0.00103

Evaluating advanced:  55%|█████▌    | 55/100 [1:15:08<1:02:36, 83.47s/it]

Q56/100 [reasoning]  NVDA  2025.0
  corr=0.20  faith=0.50  f1=0.11  tokens=9095in/894out  est=$0.00127

Evaluating advanced:  56%|█████▌    | 56/100 [1:16:52<1:05:36, 89.46s/it]

Q57/100 [reasoning]  NVDA  2025.0
  corr=0.42  faith=1.00  f1=0.14  tokens=4579in/592out  est=$0.00069

Evaluating advanced:  57%|█████▋    | 57/100 [1:18:23<1:04:25, 89.89s/it]

Q58/100 [reasoning]  JPM  2025.0
  corr=0.00  faith=1.00  f1=0.11  tokens=4592in/228out  est=$0.00055

Evaluating advanced:  58%|█████▊    | 58/100 [1:19:39<1:00:02, 85.77s/it]

Q59/100 [reasoning]  JPM  2024.0
  corr=0.30  faith=1.00  f1=0.31  tokens=9851in/249out  est=$0.00108

Evaluating advanced:  59%|█████▉    | 59/100 [1:21:33<1:04:30, 94.41s/it]

Q60/100 [reasoning]  BAC  2025.0
  [WARN] attempt 1/3 failed (503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}). Retrying in 5s...
  corr=0.00  faith=1.00  f1=0.08  tokens=10923in/197out  est=$0.00117

Evaluating advanced:  60%|██████    | 60/100 [1:23:19<1:05:14, 97.86s/it]

Q61/100 [reasoning]  BAC  2025.0
  corr=0.00  faith=1.00  f1=0.00  tokens=9481in/207out  est=$0.00103

Evaluating advanced:  61%|██████    | 61/100 [1:25:02<1:04:38, 99.44s/it]

Q62/100 [reasoning]  BRK-B  2024.0
  corr=0.45  faith=0.00  f1=0.44  tokens=851in/275out  est=$0.00020

Evaluating advanced:  62%|██████▏   | 62/100 [1:25:57<54:24, 85.90s/it]

Q63/100 [reasoning]  BRK-B  2025.0
  corr=0.00  faith=1.00  f1=0.06  tokens=697in/168out  est=$0.00014

Evaluating advanced:  63%|██████▎   | 63/100 [1:26:42<45:32, 73.85s/it]

Q64/100 [reasoning]  JNJ  2025.0
  corr=0.00  faith=1.00  f1=0.10  tokens=10853in/173out  est=$0.00115

Evaluating advanced:  64%|██████▍   | 64/100 [1:28:19<48:22, 80.63s/it]

Q65/100 [reasoning]  JNJ  2023.0
  corr=0.00  faith=1.00  f1=0.34  tokens=8088in/247out  est=$0.00091

Evaluating advanced:  65%|██████▌   | 65/100 [1:29:50<48:53, 83.82s/it]

Q66/100 [reasoning]  UNH  2025.0
  corr=0.00  faith=1.00  f1=0.05  tokens=10353in/249out  est=$0.00113

Evaluating advanced:  66%|██████▌   | 66/100 [1:30:57<44:33, 78.65s/it]

Q67/100 [reasoning]  UNH  2025.0
  corr=0.00  faith=1.00  f1=0.06  tokens=5391in/217out  est=$0.00063

Evaluating advanced:  67%|██████▋   | 67/100 [1:32:12<42:39, 77.55s/it]

Q68/100 [reasoning]  XOM  2025.0
  [WARN] Judge (judge_correctness) attempt 1 failed: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
  corr=1.00  faith=1.00  f1=0.56  tokens=6349in/421out  est=$0.00080

Evaluating advanced:  68%|██████▊   | 68/100 [1:33:35<42:21, 79.43s/it]

Q69/100 [reasoning]  XOM  2024.0
  corr=0.25  faith=0.00  f1=0.09  tokens=10502in/799out  est=$0.00137

Evaluating advanced:  69%|██████▉   | 69/100 [1:35:23<45:27, 87.98s/it]

Q70/100 [reasoning]  CVX  2025.0
  corr=0.00  faith=1.00  f1=0.11  tokens=8318in/471out  est=$0.00102

Evaluating advanced:  70%|███████   | 70/100 [1:37:03<45:40, 91.33s/it]

Q71/100 [reasoning]  CVX  2024.0
  corr=0.00  faith=0.00  f1=0.00  tokens=8613in/262out  est=$0.00097

Evaluating advanced:  71%|███████   | 71/100 [1:38:31<43:42, 90.42s/it]

Q72/100 [reasoning]  WMT  2024.0
  corr=0.80  faith=1.00  f1=0.44  tokens=5909in/351out  est=$0.00073

Evaluating advanced:  72%|███████▏  | 72/100 [1:40:01<42:12, 90.46s/it]

Q73/100 [reasoning]  WMT  2025.0
  corr=0.95  faith=1.00  f1=0.40  tokens=7999in/458out  est=$0.00098

Evaluating advanced:  73%|███████▎  | 73/100 [1:41:48<42:49, 95.16s/it]

Q74/100 [reasoning]  COST  2025.0
  corr=0.00  faith=1.00  f1=0.08  tokens=8876in/285out  est=$0.00100

Evaluating advanced:  74%|███████▍  | 74/100 [1:43:03<38:36, 89.10s/it]

Q75/100 [reasoning]  COST  2024.0
  corr=1.00  faith=1.00  f1=0.58  tokens=6317in/239out  est=$0.00073

Evaluating advanced:  75%|███████▌  | 75/100 [1:44:18<35:22, 84.89s/it]

Q76/100 [adversarial]  AAPL  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3531in/98out  est=$0.00039

Evaluating advanced:  76%|███████▌  | 76/100 [1:45:37<33:16, 83.17s/it]

Q77/100 [adversarial]  AAPL  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=6229in/119out  est=$0.00067

Evaluating advanced:  77%|███████▋  | 77/100 [1:46:56<31:26, 82.00s/it]

Q78/100 [adversarial]  MSFT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3396in/134out  est=$0.00039

Evaluating advanced:  78%|███████▊  | 78/100 [1:48:22<30:33, 83.33s/it]

Q79/100 [adversarial]  MSFT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=9539in/109out  est=$0.00100

Evaluating advanced:  79%|███████▉  | 79/100 [1:49:55<30:07, 86.09s/it]

Q80/100 [adversarial]  NVDA  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=6038in/104out  est=$0.00065

Evaluating advanced:  80%|████████  | 80/100 [1:51:27<29:17, 87.88s/it]

Q81/100 [adversarial]  NVDA  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3159in/140out  est=$0.00037

Evaluating advanced:  81%|████████  | 81/100 [1:52:45<26:53, 84.94s/it]

Q82/100 [adversarial]  NVDA  nan
  corr=0.00  faith=0.20  f1=0.00  tokens=3580in/248out  est=$0.00046

Evaluating advanced:  82%|████████▏ | 82/100 [1:54:28<27:06, 90.37s/it]

Q83/100 [adversarial]  JPM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=4114in/117out  est=$0.00046

Evaluating advanced:  83%|████████▎ | 83/100 [1:55:58<25:31, 90.09s/it]

Q84/100 [adversarial]  JPM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=4138in/117out  est=$0.00046

Evaluating advanced:  84%|████████▍ | 84/100 [1:57:17<23:11, 86.95s/it]

Q85/100 [adversarial]  BAC  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3969in/122out  est=$0.00045

Evaluating advanced:  85%|████████▌ | 85/100 [1:58:53<22:22, 89.50s/it]

Q86/100 [adversarial]  BAC  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=5844in/109out  est=$0.00063

Evaluating advanced:  86%|████████▌ | 86/100 [2:00:33<21:38, 92.74s/it]

Q87/100 [adversarial]  BRK-B  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=412in/100out  est=$0.00008

Evaluating advanced:  87%|████████▋ | 87/100 [2:01:17<16:55, 78.08s/it]

Q88/100 [adversarial]  BRK-B  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=411in/91out  est=$0.00008

Evaluating advanced:  88%|████████▊ | 88/100 [2:02:01<13:34, 67.83s/it]

Q89/100 [adversarial]  JNJ  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3376in/122out  est=$0.00039

Evaluating advanced:  89%|████████▉ | 89/100 [2:03:17<12:53, 70.35s/it]

Q90/100 [adversarial]  JNJ  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3474in/117out  est=$0.00039

Evaluating advanced:  90%|█████████ | 90/100 [2:04:45<12:37, 75.80s/it]

Q91/100 [adversarial]  UNH  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=5047in/131out  est=$0.00056

Evaluating advanced:  91%|█████████ | 91/100 [2:06:15<12:00, 80.02s/it]

Q92/100 [adversarial]  UNH  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=9566in/109out  est=$0.00100

Evaluating advanced:  92%|█████████▏| 92/100 [2:07:46<11:04, 83.06s/it]

Q93/100 [adversarial]  XOM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=4680in/99out  est=$0.00051

Evaluating advanced:  93%|█████████▎| 93/100 [2:09:12<09:47, 83.97s/it]

Q94/100 [adversarial]  XOM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=2562in/106out  est=$0.00030

Evaluating advanced:  94%|█████████▍| 94/100 [2:10:28<08:09, 81.62s/it]

Q95/100 [adversarial]  CVX  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3592in/102out  est=$0.00040

Evaluating advanced:  95%|█████████▌| 95/100 [2:12:04<07:09, 85.99s/it]

Q96/100 [adversarial]  CVX  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3408in/122out  est=$0.00039

Evaluating advanced:  96%|█████████▌| 96/100 [2:13:27<05:40, 85.22s/it]

Q97/100 [adversarial]  WMT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=7664in/99out  est=$0.00081

Evaluating advanced:  97%|█████████▋| 97/100 [2:15:09<04:30, 90.28s/it]

Q98/100 [adversarial]  WMT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=4661in/112out  est=$0.00051

Evaluating advanced:  98%|█████████▊| 98/100 [2:16:50<03:06, 93.45s/it]

Q99/100 [adversarial]  COST  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3317in/100out  est=$0.00037

Evaluating advanced:  99%|█████████▉| 99/100 [2:18:18<01:31, 91.86s/it]

Q100/100 [adversarial]  COST  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3507in/99out  est=$0.00039

Evaluating advanced: 100%|██████████| 100/100 [2:19:41<00:00, 83.82s/it]

Saved 100 rows -> /content/results/advanced_results.csv

In [ ]:
results_df

,question_id,question,question_type,company,ticker,form_type,filing_year,reference_answer,expected_decision,final_answer,...,model_judge_faithfulness,tokens_generate_input,tokens_generate_output,tokens_judge_corr_input,tokens_judge_corr_output,tokens_judge_faith_input,tokens_judge_faith_output,tokens_total_input,tokens_total_output,est_cost_usd
0,1,What were Apple’s total net sales in fiscal ye...,extractive,Apple,AAPL,10-K,2023.0,Apple's total net sales in fiscal year 2023 we...,answer,Apple's total net sales were $383.3 billion in...,...,gemini-2.5-flash,3879,72,173,81,3711,60,7763,213,0.000862
1,2,"According to Apple’s fiscal Q3 2025 filing, wh...",extractive,Apple,AAPL,10-Q,2025.0,"According to Apple's Q3 2025 filing, the U.S. ...",answer,"Beginning in the second quarter of 2025, new U...",...,gemini-2.5-flash,1989,137,234,92,1830,54,4053,283,0.000519
2,3,What are the contingencies declared by Microso...,extractive,Microsoft,MSFT,10-Q,2023.0,Microsoft declared a contingency related to IR...,answer,"As of September 30, 2023, Microsoft had accrue...",...,gemini-2.5-flash,4879,213,327,95,4833,45,10039,353,0.001145
3,4,Which Microsoft business segment generated the...,extractive,Microsoft,MSFT,10-K,2023.0,Intelligent Cloud generated the highest revenu...,answer,The Intelligent Cloud segment generated the hi...,...,gemini-2.5-flash,5263,85,182,64,5100,74,10545,223,0.001144
4,5,What risk does Nvidia mention that could affec...,extractive,NVIDIA,NVDA,10-K,2025.0,Customers may delay adopting new architectures...,answer,Nvidia mentions that the availability of data ...,...,gemini-2.5-flash,3183,116,194,83,3030,67,6407,266,0.000747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,What internal AI system does Chevron use for d...,adversarial,Chevron,CVX,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,1792,47,0,0,1616,75,3408,122,0.000390
96,97,What percentage of Walmart employees work remo...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,3919,46,0,0,3745,53,7664,99,0.000806
97,98,What internal robot efficiency metrics does Wa...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,2421,56,0,0,2240,56,4661,112,0.000511
98,99,What percentage of Costco warehouses are fully...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,1746,49,0,0,1571,51,3317,100,0.000372
99,100,What internal AI system does Costco use for in...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,1842,48,0,0,1665,51,3507,99,0.000390

## 14. Results & Comparison with Baseline

In [ ]:
for idx, row in results_df.iterrows():
    print("Row:", idx)
    print("Question:", row['question'])
    print("Reference Answer:", row['reference_answer'])
    print("Final Answer:", row['final_answer'])
    # print("Generated Answer:", row['generated_answer'])
    print("Expected Decision:", row['expected_decision'])
    print("-" * 50)

Row: 0
Question: What were Apple’s total net sales in fiscal year 2023?
Reference Answer: Apple's total net sales in fiscal year 2023 were $383,285 million.
Final Answer: Apple's total net sales were $383.3 billion in fiscal year 2023 [1].
Expected Decision: answer
--------------------------------------------------
Row: 1
Question: According to Apple’s fiscal Q3 2025 filing, which countries were subject to new U.S. import tariffs?
Reference Answer: According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Final Answer: Beginning in the second quarter of 2025, new U.S. tariffs were announced on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union (EU), among others [1, 2, 3, 4].
Expected Decision: answer
--------------------------------------------------
Row: 2
Question: What are the contingencies declared by Microsoft for the quarter ended in September 2023?
Reference Answer: Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Final Answer: As of September 30, 2023, Microsoft had accrued aggregate legal liabilities of $597 million [2]. Additionally, Microsoft had a remaining transition tax liability of $7.7 billion as of September 30, 2023, with $3.7 billion of this amount being short-term and payable in the first quarter of fiscal year 2025 [1]. Microsoft also stated that as of September 30, 2023, they believe their allowances for income tax contingencies are adequate, following the receipt of Notices of Proposed Adjustment from the IRS for tax years 2004 to 2013 on September 26, 2023 [4].
Expected Decision: answer
--------------------------------------------------
Row: 3
Question: Which Microsoft business segment generated the highest revenue in the 2023 fiscal year?
Reference Answer: Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Final Answer: The Intelligent Cloud segment generated the highest revenue in the 2023 fiscal year, with $87,907 million [1, 2].
Expected Decision: answer
--------------------------------------------------
Row: 4
Question: What risk does Nvidia mention that could affect the timing of Data Center revenue in fiscal year 2025?
Reference Answer: Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Final Answer: Nvidia mentions that the availability of data centers, energy, and capital to support the buildout of NVIDIA AI infrastructure by their customers and partners is crucial, and any shortage of these resources could impact future revenue and financial performance [4, 7].
Expected Decision: answer
--------------------------------------------------
Row: 5
Question: What was Nvidia's gross margin percentage in fiscal year 2024?
Reference Answer: Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Final Answer: Gross margins increased to 75.0% in fiscal year 2025 from 72.7% in fiscal year 2024 [5].
Expected Decision: answer
--------------------------------------------------
Row: 6
Question: How many employees did Nvidia report at the end of fiscal year 2025?
Reference Answer: As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 7
Question: What was JPMorgan's CET1 capital ratio at the end of fiscal year 2023?
Reference Answer: JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Final Answer: JPMorgan's CET1 capital ratio was 13.2% at the end of fiscal year 2022 [1, 2, 3, 4].
Expected Decision: answer
--------------------------------------------------
Row: 8
Question: Which federal regulator supervises JPMorgan Chase as a bank holding company in 2024?
Reference Answer: JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Final Answer: The Federal Reserve acts as the supervisor of the consolidated operations of Bank Holding Companies (BHCs) [1]. As a large BHC, JPMorgan Chase is subject to supervisory stress testing administered by the Federal Reserve as part of the Federal Reserve’s annual Comprehensive Capital Analysis and Review (“CCAR”) framework [5]. The Federal Reserve establishes capital, liquidity, and leverage requirements for JPMorgan Chase that are generally consistent with the international Basel III capital and liquidity framework and evaluates the Firm’s compliance with those requirements [2]. The Federal Reserve also establishes capital requirements, including well-capitalized standards, for the Firm as a consolidated financial holding company [3]. Additionally, the Federal Reserve is authorized to take appropriate action against the parent BHC, such as JPMorgan Chase & Co., based on the undercapitalized status of any bank subsidiary [6].
Expected Decision: answer
--------------------------------------------------
Row: 9
Question: What were Bank of America's Total liabilities as of September 2025?
Reference Answer: Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 10
Question: What interest rate risk does Bank of America describe in its latest annual filing?
Reference Answer: Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and capital.
Final Answer: Interest rate risk is the most significant market risk exposure to Bank of America's banking book balance sheet, measured as the potential change in net interest income caused by movements in market interest rates [2, 7]. Market risk, including interest rate risk, can be substantial in the mortgage business, where it is the risk that values of mortgage assets or revenues will be adversely affected by changes in market conditions such as interest rate movements [3, 4]. Bank of America utilizes forward loan sale commitments and other derivative instruments, including purchased options and certain debt securities, to mitigate interest rate risk in mortgage banking production income [3, 4].
Expected Decision: answer
--------------------------------------------------
Row: 11
Question: What was Berkshire Hathaway’s net earnings attributable to shareholders reported in its latest annual report?
Reference Answer: Berkshire Hathaway's net earnings attributable to Berkshire shareholders in fiscal year 2025 were $66,968 million.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 12
Question: How much did Berkshire Hathaway pay to acquire an additional interest in Pilot Travel Centers in January 2023?
Reference Answer: Berkshire Hathaway acquired an additional 41.4% controlling interest in Pilot Travel Centers for approximately $8.2 billion on January 31, 2023, which was consolidated into financial statements from February 1, 2023.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 13
Question: What were Johnson & Johnson’s total sales for the first nine months of fiscal 2025?
Reference Answer: Johnson & Johnson's total sales for the nine months ended September 28, 2025 were $69,629 million.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 14
Question: What was Johnson & Johnson’s net earnings in the most recent annual report?
Reference Answer: Johnson & Johnson's net earnings from continuing operations in fiscal year 2025 were $26,804 million.
Final Answer: Johnson & Johnson's net earnings were $35,153 million in 2023 [2].
Expected Decision: answer
--------------------------------------------------
Row: 15
Question: What was UnitedHealth Group's medical care ratio for the three months ended June 2024?
Reference Answer: UnitedHealth Group's medical care ratio (MCR) for the three months ended June 30, 2024 was 85.1%, up from 83.2% in Q2 2023, an increase of 1.9 percentage points.
Final Answer: UnitedHealth Group's medical care ratio was 85.2% for the three months ended June 30, 2024 [1].
Expected Decision: answer
--------------------------------------------------
Row: 16
Question: What was UnitedHealth Group’s net earnings reported in 2023?
Reference Answer: UnitedHealth Group's net earnings reported in 2023 is $23,144 million.
Final Answer: UnitedHealth Group reported net earnings attributable to UnitedHealth Group common shareholders of $22,381 million in 2023 [3].
Expected Decision: answer
--------------------------------------------------
Row: 17
Question: How many oil-equivalent barrels per day did ExxonMobil produce in fiscal year 2023?
Reference Answer: ExxonMobil produced 3,738 thousand oil-equivalent barrels per day
Final Answer: ExxonMobil produced 3.7 million oil-equivalent barrels per day in 2023 [1].
Expected Decision: answer
--------------------------------------------------
Row: 18
Question: What was the total value of acquisitions completed by ExxonMobil during the third quarter of 2025?
Reference Answer: ExxonMobil completed $2.4 billion in acquisitions consisting primarily of proved and unproved acreage in the Permian basin.
Final Answer: During the third quarter of 2025, ExxonMobil completed $2.4 billion in acquisitions, primarily consisting of proved and unproved acreage in the Permian basin [3].
Expected Decision: answer
--------------------------------------------------
Row: 19
Question: What primarily caused Chevron’s international upstream earnings to decrease in the three months ended March 31, 2024?
Reference Answer: Chevron's International Upstream earnings decreased was primarily due to lower natural gas realizations
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 20
Question: What are Chevron’s two primary business segments in 2025?
Reference Answer: Chevron's two primary business segments in 2025 are Upstream and Downstream.
Final Answer: Chevron's two primary business segments in 2025 are Upstream and Downstream [1, 4, 5].
Expected Decision: answer
--------------------------------------------------
Row: 21
Question: What liability did Walmart accrue in fiscal year 2023 for opioid-related settlement agreements?
Reference Answer: During fiscal 2023, Walmart accrued a liability of approximately $3.3 billion for the opioid-related Settlement Framework.
Final Answer: Walmart accrued a liability of approximately $3.3 billion in fiscal year 2023 for the Settlement Framework and other previously agreed-upon state and tribal settlements related to opioid litigation [1, 2, 3, 6]. As of January 31, 2023, the accrued liability for opioid litigation settlement was $2,949 million [4].
Expected Decision: answer
--------------------------------------------------
Row: 22
Question: How many associates did Walmart employ globally in fiscal year 2025?
Reference Answer: Walmart employed approximately 2.1 million associates.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 23
Question: What was Costco’s total revenue reported in fiscal year 2025?
Reference Answer: Costco's total revenue for fiscal year 2025 was $275,235 million.
Final Answer: Costco's total revenue reported for the 52 weeks ended September 1, 2024, was $254,453 million [1]. The total revenue for fiscal year 2025 was $275,235 million [4].
Expected Decision: answer
--------------------------------------------------
Row: 24
Question: What membership fee revenue did Costco report for the quarter ended November 26, 2023?
Reference Answer: Costco reported membership fee revenue of $1,082 million for the 12 weeks ended November 26, 2023.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 25
Question: What amount of revenue did Apple generate during fiscal year 2023?
Reference Answer: Apple's total net sales in fiscal year 2023 were $383,285 million.
Final Answer: Apple generated $383,285 million in total net sales during fiscal year 2023 [3]. This represents a decrease of $11.0 billion, or 3%, compared to fiscal year 2022 [4].
Expected Decision: answer
--------------------------------------------------
Row: 26
Question: Which regions were impacted by the newly announced U.S. import duties referenced in Apple’s Q3 2025 report?
Reference Answer: According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Final Answer: The newly announced U.S. import duties in the second quarter of 2025 included additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the EU [4, 6]. In response, several countries have imposed, or threatened to impose, reciprocal tariffs on imports from the U.S. [1, 2, 3, 4, 6].
Expected Decision: answer
--------------------------------------------------
Row: 27
Question: What potential financial obligations did Microsoft flag in its three-month period ending September 2023?
Reference Answer: Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Final Answer: In the three-month period ending September 2023, Microsoft reported the following financial obligations:

*   **Unearned revenue:** $(4,126) million [1]
*   **Other current liabilities:** $(4,106) million [1]
*   **Other long-term liabilities:** $291 million [1]
*   **Derivative liabilities (net):** $(579) million [3]
Expected Decision: answer
--------------------------------------------------
Row: 28
Question: Which of Microsoft’s operating divisions contributed the largest share of revenue in the most recent fiscal year?
Reference Answer: Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Final Answer: For fiscal year 2024, the "Intelligent Cloud" division contributed the largest share of revenue, with $105,362 million.
Expected Decision: answer
--------------------------------------------------
Row: 29
Question: What factor does Nvidia identify that could delay the recognition of Data Center revenue in fiscal year 2025?
Reference Answer: Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Final Answer: Nvidia identifies that customers may delay adopting new architectures if their data center infrastructure is not ready, which could affect the timing of revenue recognition for Data Center products [5]. Additionally, the increased frequency and complexity of newly introduced products could lead to unanticipated quality or production issues, potentially impacting revenue timing [5].
Expected Decision: answer
--------------------------------------------------
Row: 30
Question: What proportion of Nvidia’s revenue remained as gross profit during fiscal year 2024?
Reference Answer: Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Final Answer: Nvidia's gross margin was 72.7% in fiscal year 2024 [5].
Expected Decision: answer
--------------------------------------------------
Row: 31
Question: What was the size of Nvidia's workforce at the close of its 2025 annual period?
Reference Answer: As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 32
Question: What Common Equity Tier 1 capital ratio did JPMorgan report at the end of fiscal year 2023?
Reference Answer: JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Final Answer: JPMorgan reported a Common Equity Tier 1 (CET1) capital ratio of 13.6% at the end of fiscal year 2023 under the Basel III Advanced framework [2]. Under the Basel III Standardized framework, the CET1 capital ratio was 13.2% [2].
Expected Decision: answer
--------------------------------------------------
Row: 33
Question: What government body had oversight responsibility over JPMorgan Chase's holding company structure in 2024?
Reference Answer: JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Final Answer: The Federal Reserve acts as the supervisor of the consolidated operations of Bank Holding Companies (BHCs), including JPMorgan Chase & Co. [6]. The Federal Reserve also establishes capital requirements for JPMorgan Chase as a consolidated financial holding company [2, 5].
Expected Decision: answer
--------------------------------------------------
Row: 34
Question: What was the aggregate sum of all debts and obligations owed by Bank of America as of September 2025?
Reference Answer: Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Final Answer: Total liabilities were $3,099,564 million as of September 30, 2025 [1].
Expected Decision: answer
--------------------------------------------------
Row: 35
Question: How does Bank of America characterise the threat posed by fluctuating borrowing costs in its 2024 annual period?
Reference Answer: Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and capital.
Final Answer: Bank of America characterizes the threat posed by fluctuating borrowing costs by stating that the cost and availability of unsecured funding may be negatively impacted by general market conditions or by matters specific to the financial services industry or the Corporation. They seek to mitigate refinancing risk by actively managing the amount of their borrowings that they anticipate will mature within any month or quarter [1].
Expected Decision: answer
--------------------------------------------------
Row: 36
Question: What was the total profit that Berkshire Hathaway recorded for the most recent yearly report?
Reference Answer: Berkshire Hathaway's net earnings attributable to Berkshire shareholders in fiscal year 2025 were $66,968 million.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 37
Question: How much did Berkshire Hathaway spend in January 2023 to buy out the remaining ownership stake in Pilot Travel Centers?
Reference Answer: Berkshire Hathaway acquired an additional 41.4% controlling interest in Pilot Travel Centers for approximately $8.2 billion on January 31, 2023, which was consolidated into financial statements from February 1, 2023.

In [ ]:
results_df

,question_id,question,question_type,company,ticker,form_type,filing_year,reference_answer,expected_decision,final_answer,...,model_judge_faithfulness,tokens_generate_input,tokens_generate_output,tokens_judge_corr_input,tokens_judge_corr_output,tokens_judge_faith_input,tokens_judge_faith_output,tokens_total_input,tokens_total_output,est_cost_usd
0,1,What were Apple’s total net sales in fiscal ye...,extractive,Apple,AAPL,10-K,2023.0,Apple's total net sales in fiscal year 2023 we...,answer,Apple's total net sales were $383.3 billion in...,...,gemini-2.5-flash,3879,72,173,81,3711,60,7763,213,0.000862
1,2,"According to Apple’s fiscal Q3 2025 filing, wh...",extractive,Apple,AAPL,10-Q,2025.0,"According to Apple's Q3 2025 filing, the U.S. ...",answer,"Beginning in the second quarter of 2025, new U...",...,gemini-2.5-flash,1989,137,234,92,1830,54,4053,283,0.000519
2,3,What are the contingencies declared by Microso...,extractive,Microsoft,MSFT,10-Q,2023.0,Microsoft declared a contingency related to IR...,answer,"As of September 30, 2023, Microsoft had accrue...",...,gemini-2.5-flash,4879,213,327,95,4833,45,10039,353,0.001145
3,4,Which Microsoft business segment generated the...,extractive,Microsoft,MSFT,10-K,2023.0,Intelligent Cloud generated the highest revenu...,answer,The Intelligent Cloud segment generated the hi...,...,gemini-2.5-flash,5263,85,182,64,5100,74,10545,223,0.001144
4,5,What risk does Nvidia mention that could affec...,extractive,NVIDIA,NVDA,10-K,2025.0,Customers may delay adopting new architectures...,answer,Nvidia mentions that the availability of data ...,...,gemini-2.5-flash,3183,116,194,83,3030,67,6407,266,0.000747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,What internal AI system does Chevron use for d...,adversarial,Chevron,CVX,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,1792,47,0,0,1616,75,3408,122,0.000390
96,97,What percentage of Walmart employees work remo...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,3919,46,0,0,3745,53,7664,99,0.000806
97,98,What internal robot efficiency metrics does Wa...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,2421,56,0,0,2240,56,4661,112,0.000511
98,99,What percentage of Costco warehouses are fully...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,1746,49,0,0,1571,51,3317,100,0.000372
99,100,What internal AI system does Costco use for in...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,1842,48,0,0,1665,51,3507,99,0.000390

In [ ]:
print("=" * 60)
print(" ADVANCED RAG — EVALUATION RESULTS")
print("=" * 60)

scored_c = results_df[results_df['llm_correctness_score'].notna()]
scored_f = results_df[results_df['llm_faithfulness_score'].notna()]
print(f'\nTotal questions    : {len(results_df)}')
print(f'Correctness judged : {len(scored_c)}')
print(f'Faithfulness judged: {len(scored_f)}')

print('\nOverall metrics:')
for col, label in [
    ('llm_correctness_score',  'LLM Correctness  '),
    ('llm_claims_covered',     'Claims Covered   '),
    ('llm_faithfulness_score', 'LLM Faithfulness '),
    ('token_f1',               'Token F1         '),
    ('numerical_accuracy',     'Numerical Accuracy'),
    ('decision_accuracy',      'Decision Accuracy'),
]:
    vals = results_df[col].dropna()
    if len(vals):
        print(f'  {label}: {vals.mean():.4f}  (n={len(vals)})')

print('\nBy question_type:')
type_cols = ['llm_correctness_score', 'llm_faithfulness_score', 'token_f1', 'decision_accuracy']
avail = [c for c in type_cols if c in results_df.columns]
if avail and 'question_type' in results_df.columns:
    print(results_df.groupby('question_type')[avail].mean().round(3).to_string())

if 'latency_sec' in results_df.columns:
    lat = results_df['latency_sec'].dropna()
    if len(lat):
        print(f'\nLatency: mean={lat.mean():.1f}s  median={lat.median():.1f}s  max={lat.max():.1f}s')

print('\nToken & cost summary:')
for col in ['tokens_generate_input', 'tokens_generate_output',
            'tokens_judge_corr_input', 'tokens_judge_corr_output',
            'tokens_judge_faith_input', 'tokens_judge_faith_output',
            'tokens_total_input', 'tokens_total_output']:
    if col in results_df.columns:
        print(f'  {col:35s}: {int(results_df[col].sum()):,}')
if 'est_cost_usd' in results_df.columns:
    print(f'  {"Total estimated cost (USD)":35s}: ${results_df["est_cost_usd"].sum():.4f}')

# Compare with baseline if available
baseline_path = Path(CONFIG["results_dir"]) / "baseline_results.csv"
if baseline_path.exists():
    baseline_df = pd.read_csv(baseline_path)
    print("\n" + "=" * 60)
    print(" COMPARISON: BASELINE vs ADVANCED RAG")
    print("=" * 60)
    cols = ['llm_correctness_score', 'llm_faithfulness_score', 'token_f1', 'decision_accuracy']
    avail = [c for c in cols if c in results_df.columns and c in baseline_df.columns]
    comparison = pd.DataFrame({
        "Baseline": baseline_df[avail].mean(),
        "Advanced": results_df[avail].mean(),
    }).round(3)
    comparison["Delta"] = (comparison["Advanced"] - comparison["Baseline"]).round(3)
    print(comparison.to_string())
else:
    print("\n(Run baseline_rag.ipynb first to see comparison)")

============================================================
 ADVANCED RAG — EVALUATION RESULTS
============================================================

Total questions    : 100
Correctness judged : 100
Faithfulness judged: 100

Overall metrics:
  LLM Correctness  : 0.5787  (n=100)
  Claims Covered   : 0.6127  (n=100)
  LLM Faithfulness : 0.9170  (n=100)
  Token F1         : 0.2313  (n=100)
  Numerical Accuracy: 0.4675  (n=67)
  Decision Accuracy: 0.7400  (n=100)

By question_type:
               llm_correctness_score  llm_faithfulness_score  token_f1  decision_accuracy
question_type
adversarial                    0.960                   0.968     0.000               0.96
extractive                     0.519                   0.920     0.373               0.68
paraphrased                    0.463                   0.960     0.317               0.72
reasoning                      0.373                   0.820     0.236               0.60

Latency: mean=35.8s  median=35.3s  max=62.2s

Token & cost summary:
  tokens_generate_input              : 329,113
  tokens_generate_output             : 11,240
  tokens_judge_corr_input            : 17,423
  tokens_judge_corr_output           : 5,040
  tokens_judge_faith_input           : 313,851
  tokens_judge_faith_output          : 6,925
  tokens_total_input                 : 660,387
  tokens_total_output                : 23,205
  Total estimated cost (USD)         : $0.0753

(Run baseline_rag.ipynb first to see comparison)

In [ ]:
import pandas as pd

# Load only what exists
advanced_df = pd.read_csv("/content/results/advanced_results.csv")
print(f"Advanced results: {len(advanced_df)} rows")
print(f"Columns: {list(advanced_df.columns)}")

Advanced results: 100 rows
Columns: ['question_id', 'question', 'question_type', 'company', 'ticker', 'form_type', 'filing_year', 'reference_answer', 'expected_decision', 'final_answer', 'pipeline', 'n_chunks', 'rewritten_query', 'latency_sec', 'token_f1', 'numerical_accuracy', 'decision_accuracy', 'predicted_decision', 'llm_correctness_score', 'llm_claims_covered', 'llm_correctness_reason', 'llm_faithfulness_score', 'llm_faithfulness_reason', 'model_generator', 'model_judge_correctness', 'model_judge_faithfulness', 'tokens_generate_input', 'tokens_generate_output', 'tokens_judge_corr_input', 'tokens_judge_corr_output', 'tokens_judge_faith_input', 'tokens_judge_faith_output', 'tokens_total_input', 'tokens_total_output', 'est_cost_usd']

In [ ]:
# Step 1 — Did answers come out?
print("=== ANSWER CHECK ===")
empty = advanced_df["final_answer"].isna() | (advanced_df["final_answer"].str.strip() == "")
refusals = advanced_df["final_answer"].str.contains(
    "insufficient|not contain|cannot find|not available|unable to",
    case=False, na=False
)
print(f"Total          : {len(advanced_df)}")
print(f"Empty answers  : {empty.sum()}")
print(f"Refusals       : {refusals.sum()}")
print(f"Actual answers : {(~empty & ~refusals).sum()}")

=== ANSWER CHECK ===
Total          : 100
Empty answers  : 0
Refusals       : 49
Actual answers : 51

In [ ]:
# Step 2 — Eyeball every single question
pd.set_option("display.max_colwidth", 200)
for _, row in advanced_df.iterrows():
    print(f"\nQ{_+1} [{row.get('question_type','?')}] {row.get('ticker','?')} {row.get('filing_year','?')}")
    print(f"Question : {row['question']}")
    print(f"Expected : {str(row['reference_answer'])[:300]}")
    print(f"Got      : {str(row['final_answer'])[:300]}")
    print(f"Scores   : corr={row.get('llm_correctness_score',0):.2f}  "
          f"faith={row.get('llm_faithfulness_score',0):.2f}  "
          f"num_acc={row.get('numerical_accuracy','N/A')}")
    print("-"*80)

Q1 [extractive] AAPL 2023.0
Question : What were Apple’s total net sales in fiscal year 2023?
Expected : Apple's total net sales in fiscal year 2023 were $383,285 million.
Got      : Apple's total net sales were $383.3 billion in fiscal year 2023 [1].
Scores   : corr=0.99  faith=1.00  num_acc=0.5
--------------------------------------------------------------------------------

Q2 [extractive] AAPL 2025.0
Question : According to Apple’s fiscal Q3 2025 filing, which countries were subject to new U.S. import tariffs?
Expected : According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Got      : Beginning in the second quarter of 2025, new U.S. tariffs were announced on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union (EU), among others [1, 2, 3, 4].
Scores   : corr=0.70  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q3 [extractive] MSFT 2023.0
Question : What are the contingencies declared by Microsoft for the quarter ended in September 2023?
Expected : Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Got      : As of September 30, 2023, Microsoft had accrued aggregate legal liabilities of $597 million [2]. Additionally, Microsoft had a remaining transition tax liability of $7.7 billion as of September 30, 2023, with $3.7 billion of this amount being short-term and payable in the first quarter of fiscal yea
Scores   : corr=0.35  faith=1.00  num_acc=0.6666666666666666
--------------------------------------------------------------------------------

Q4 [extractive] MSFT 2023.0
Question : Which Microsoft business segment generated the highest revenue in the 2023 fiscal year?
Expected : Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Got      : The Intelligent Cloud segment generated the highest revenue in the 2023 fiscal year, with $87,907 million [1, 2].
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q5 [extractive] NVDA 2025.0
Question : What risk does Nvidia mention that could affect the timing of Data Center revenue in fiscal year 2025?
Expected : Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Got      : Nvidia mentions that the availability of data centers, energy, and capital to support the buildout of NVIDIA AI infrastructure by their customers and partners is crucial, and any shortage of these resources could impact future revenue and financial performance [4, 7].
Scores   : corr=0.60  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q6 [extractive] NVDA 2024.0
Question : What was Nvidia's gross margin percentage in fiscal year 2024?
Expected : Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Got      : Gross margins increased to 75.0% in fiscal year 2025 from 72.7% in fiscal year 2024 [5].
Scores   : corr=1.00  faith=1.00  num_acc=0.75
--------------------------------------------------------------------------------

Q7 [extractive] NVDA 2025.0
Question : How many employees did Nvidia report at the end of fiscal year 2025?
Expected : As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q8 [extractive] JPM 2023.0
Question : What was JPMorgan's CET1 capital ratio at the end of fiscal year 2023?
Expected : JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Got      : JPMorgan's CET1 capital ratio was 13.2% at the end of fiscal year 2022 [1, 2, 3, 4].
Scores   : corr=0.00  faith=1.00  num_acc=0.6
--------------------------------------------------------------------------------

Q9 [extractive] JPM 2024.0
Question : Which federal regulator supervises JPMorgan Chase as a bank holding company in 2024?
Expected : JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Got      : The Federal Reserve acts as the supervisor of the consolidated operations of Bank Holding Companies (BHCs) [1]. As a large BHC, JPMorgan Chase is subject to supervisory stress testing administered by the Federal Reserve as part of the Federal Reserve’s annual Comprehensive Capital Analysis and Revie
Scores   : corr=1.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q10 [extractive] BAC 2025.0
Question : What were Bank of America's Total liabilities as of September 2025?
Expected : Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q11 [extractive] BAC 2024.0
Question : What interest rate risk does Bank of America describe in its latest annual filing?
Expected : Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and c
Got      : Interest rate risk is the most significant market risk exposure to Bank of America's banking book balance sheet, measured as the potential change in net interest income caused by movements in market interest rates [2, 7]. Market risk, including interest rate risk, can be substantial in the mortgage
Scores   : corr=0.70  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q12 [extractive] BRK-B 2025.0
Question : What was Berkshire Hathaway’s net earnings attributable to shareholders reported in its latest annual report?
Expected : Berkshire Hathaway's net earnings attributable to Berkshire shareholders in fiscal year 2025 were $66,968 million.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q13 [extractive] BRK-B 2023.0
Question : How much did Berkshire Hathaway pay to acquire an additional interest in Pilot Travel Centers in January 2023?
Expected : Berkshire Hathaway acquired an additional 41.4% controlling interest in Pilot Travel Centers for approximately $8.2 billion on January 31, 2023, which was consolidated into financial statements from February 1, 2023.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q14 [extractive] JNJ 2025.0
Question : What were Johnson & Johnson’s total sales for the first nine months of fiscal 2025?
Expected : Johnson & Johnson's total sales for the nine months ended September 28, 2025 were $69,629 million.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=0.00  num_acc=0.0
--------------------------------------------------------------------------------

Q15 [extractive] JNJ 2025.0
Question : What was Johnson & Johnson’s net earnings in the most recent annual report?
Expected : Johnson & Johnson's net earnings from continuing operations in fiscal year 2025 were $26,804 million.
Got      : Johnson & Johnson's net earnings were $35,153 million in 2023 [2].
Scores   : corr=0.10  faith=1.00  num_acc=0.5
--------------------------------------------------------------------------------

Q16 [extractive] UNH 2024.0
Question : What was UnitedHealth Group's medical care ratio for the three months ended June 2024?
Expected : UnitedHealth Group's medical care ratio (MCR) for the three months ended June 30, 2024 was 85.1%, up from 83.2% in Q2 2023, an increase of 1.9 percentage points.
Got      : UnitedHealth Group's medical care ratio was 85.2% for the three months ended June 30, 2024 [1].
Scores   : corr=0.98  faith=0.00  num_acc=0.5714285714285714
--------------------------------------------------------------------------------

Q17 [extractive] UNH 2023.0
Question : What was UnitedHealth Group’s net earnings reported in 2023?
Expected : UnitedHealth Group's net earnings reported in 2023 is $23,144 million.
Got      : UnitedHealth Group reported net earnings attributable to UnitedHealth Group common shareholders of $22,381 million in 2023 [3].
Scores   : corr=0.60  faith=1.00  num_acc=0.5
--------------------------------------------------------------------------------

Q18 [extractive] XOM 2023.0
Question : How many oil-equivalent barrels per day did ExxonMobil produce in fiscal year 2023?
Expected : ExxonMobil produced 3,738 thousand oil-equivalent barrels per day
Got      : ExxonMobil produced 3.7 million oil-equivalent barrels per day in 2023 [1].
Scores   : corr=0.95  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q19 [extractive] XOM 2025.0
Question : What was the total value of acquisitions completed by ExxonMobil during the third quarter of 2025?
Expected : ExxonMobil completed $2.4 billion in acquisitions consisting primarily of proved and unproved acreage in the Permian basin.
Got      : During the third quarter of 2025, ExxonMobil completed $2.4 billion in acquisitions, primarily consisting of proved and unproved acreage in the Permian basin [3].
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q20 [extractive] CVX 2024.0
Question : What primarily caused Chevron’s international upstream earnings to decrease in the three months ended March 31, 2024?
Expected : Chevron's International Upstream earnings decreased was primarily due to lower natural gas realizations
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q21 [extractive] CVX 2025.0
Question : What are Chevron’s two primary business segments in 2025?
Expected : Chevron's two primary business segments in 2025 are Upstream and Downstream.
Got      : Chevron's two primary business segments in 2025 are Upstream and Downstream [1, 4, 5].
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q22 [extractive] WMT 2023.0
Question : What liability did Walmart accrue in fiscal year 2023 for opioid-related settlement agreements?
Expected : During fiscal 2023, Walmart accrued a liability of approximately $3.3 billion for the opioid-related Settlement Framework.
Got      : Walmart accrued a liability of approximately $3.3 billion in fiscal year 2023 for the Settlement Framework and other previously agreed-upon state and tribal settlements related to opioid litigation [1, 2, 3, 6]. As of January 31, 2023, the accrued liability for opioid litigation settlement was $2,94
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q23 [extractive] WMT 2025.0
Question : How many associates did Walmart employ globally in fiscal year 2025?
Expected : Walmart employed approximately 2.1 million associates.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q24 [extractive] COST 2025.0
Question : What was Costco’s total revenue reported in fiscal year 2025?
Expected : Costco's total revenue for fiscal year 2025 was $275,235 million.
Got      : Costco's total revenue reported for the 52 weeks ended September 1, 2024, was $254,453 million [1]. The total revenue for fiscal year 2025 was $275,235 million [4].
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q25 [extractive] COST 2023.0
Question : What membership fee revenue did Costco report for the quarter ended November 26, 2023?
Expected : Costco reported membership fee revenue of $1,082 million for the 12 weeks ended November 26, 2023.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q26 [paraphrased] AAPL 2023.0
Question : What amount of revenue did Apple generate during fiscal year 2023?
Expected : Apple's total net sales in fiscal year 2023 were $383,285 million.
Got      : Apple generated $383,285 million in total net sales during fiscal year 2023 [3]. This represents a decrease of $11.0 billion, or 3%, compared to fiscal year 2022 [4].
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q27 [paraphrased] AAPL 2025.0
Question : Which regions were impacted by the newly announced U.S. import duties referenced in Apple’s Q3 2025 report?
Expected : According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Got      : The newly announced U.S. import duties in the second quarter of 2025 included additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the EU [4, 6]. In response, several countries have imposed, or threatened to impose, reciprocal tariffs on imports from the U.S. [1,
Scores   : corr=0.60  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q28 [paraphrased] MSFT 2023.0
Question : What potential financial obligations did Microsoft flag in its three-month period ending September 2023?
Expected : Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Got      : In the three-month period ending September 2023, Microsoft reported the following financial obligations:

*   **Unearned revenue:** $(4,126) million [1]
*   **Other current liabilities:** $(4,106) million [1]
*   **Other long-term liabilities:** $291 million [1]
*   **Derivative liabilities (net):**
Scores   : corr=0.00  faith=1.00  num_acc=0.6666666666666666
--------------------------------------------------------------------------------

Q29 [paraphrased] MSFT 2023.0
Question : Which of Microsoft’s operating divisions contributed the largest share of revenue in the most recent fiscal year?
Expected : Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Got      : For fiscal year 2024, the "Intelligent Cloud" division contributed the largest share of revenue, with $105,362 million.
Scores   : corr=0.00  faith=1.00  num_acc=0.5
--------------------------------------------------------------------------------

Q30 [paraphrased] NVDA 2025.0
Question : What factor does Nvidia identify that could delay the recognition of Data Center revenue in fiscal year 2025?
Expected : Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Got      : Nvidia identifies that customers may delay adopting new architectures if their data center infrastructure is not ready, which could affect the timing of revenue recognition for Data Center products [5]. Additionally, the increased frequency and complexity of newly introduced products could lead to u
Scores   : corr=1.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q31 [paraphrased] NVDA 2024.0
Question : What proportion of Nvidia’s revenue remained as gross profit during fiscal year 2024?
Expected : Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Got      : Nvidia's gross margin was 72.7% in fiscal year 2024 [5].
Scores   : corr=1.00  faith=1.00  num_acc=0.75
--------------------------------------------------------------------------------

Q32 [paraphrased] NVDA 2025.0
Question : What was the size of Nvidia's workforce at the close of its 2025 annual period?
Expected : As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q33 [paraphrased] JPM 2023.0
Question : What Common Equity Tier 1 capital ratio did JPMorgan report at the end of fiscal year 2023?
Expected : JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Got      : JPMorgan reported a Common Equity Tier 1 (CET1) capital ratio of 13.6% at the end of fiscal year 2023 under the Basel III Advanced framework [2]. Under the Basel III Standardized framework, the CET1 capital ratio was 13.2% [2].
Scores   : corr=0.00  faith=0.00  num_acc=0.6
--------------------------------------------------------------------------------

Q34 [paraphrased] JPM 2024.0
Question : What government body had oversight responsibility over JPMorgan Chase's holding company structure in 2024?
Expected : JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Got      : The Federal Reserve acts as the supervisor of the consolidated operations of Bank Holding Companies (BHCs), including JPMorgan Chase & Co. [6]. The Federal Reserve also establishes capital requirements for JPMorgan Chase as a consolidated financial holding company [2, 5].
Scores   : corr=1.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q35 [paraphrased] BAC 2025.0
Question : What was the aggregate sum of all debts and obligations owed by Bank of America as of September 2025?
Expected : Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Got      : Total liabilities were $3,099,564 million as of September 30, 2025 [1].
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q36 [paraphrased] BAC 2024.0
Question : How does Bank of America characterise the threat posed by fluctuating borrowing costs in its 2024 annual period?
Expected : Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and c
Got      : Bank of America characterizes the threat posed by fluctuating borrowing costs by stating that the cost and availability of unsecured funding may be negatively impacted by general market conditions or by matters specific to the financial services industry or the Corporation. They seek to mitigate ref
Scores   : corr=0.05  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q37 [paraphrased] BRK-B 2025.0

In [ ]:
# Step 3 — Retrieval vs Generation diagnosis
hi_faith_lo_corr = advanced_df[
    (advanced_df["llm_faithfulness_score"] >= 0.6) &
    (advanced_df["llm_correctness_score"]  <  0.3)
]
lo_faith_lo_corr = advanced_df[
    (advanced_df["llm_faithfulness_score"] <  0.4) &
    (advanced_df["llm_correctness_score"]  <  0.3)
]
hi_both = advanced_df[
    (advanced_df["llm_faithfulness_score"] >= 0.6) &
    (advanced_df["llm_correctness_score"]  >= 0.6)
]

print("=== RETRIEVAL vs GENERATION DIAGNOSIS ===")
print(f"Wrong chunks retrieved  (faith↑ corr↓) : {len(hi_faith_lo_corr)} — finding irrelevant content")
print(f"Hallucination / no ctx  (faith↓ corr↓) : {len(lo_faith_lo_corr)} — LLM making things up")
print(f"Working correctly       (faith↑ corr↑) : {len(hi_both)}")

=== RETRIEVAL vs GENERATION DIAGNOSIS ===
Wrong chunks retrieved  (faith↑ corr↓) : 31 — finding irrelevant content
Hallucination / no ctx  (faith↓ corr↓) : 6 — LLM making things up
Working correctly       (faith↑ corr↑) : 57