# Advanced RAG — SEC Filings

**Pipeline**: Metadata Extraction → Query Rewriting → Multi-Query → Hybrid Search (BM25 + Dense + RRF) → CrossEncoder Reranking → Context Compression → LLM Generation with Citations

## What's new vs Baseline RAG?

| Stage | Baseline | Advanced |
|-------|----------|----------|
| Query prep | Raw query | Rewrite + 2 variants |
| Retrieval | Dense only | BM25 + Dense + RRF |
| Scope | All chunks | Metadata-filtered |
| Scoring | Cosine sim | CrossEncoder rerank |
| Context | Full chunks | Sentence-level compression |
| Answer | Plain text | Text with [n] citations |

Each improvement is independently motivated:
1. **Metadata filtering** — restricts search to the relevant company/year, reducing irrelevant noise
2. **Query rewriting** — aligns query vocabulary with financial document language
3. **Multi-query** — different phrasings capture different relevant chunks
4. **Hybrid BM25 + Dense** — BM25 handles exact financial term matching; dense handles semantic similarity
5. **CrossEncoder reranking** — more accurate relevance scoring than bi-encoder cosine similarity
6. **Context compression** — removes off-topic sentences, reduces LLM context noise
7. **Citation generation** — improves traceability and faithfulness

In [1]:
print('hi')

hi

In [2]:
# Uncomment to install dependencies
!pip install sentence-transformers chromadb rank-bm25 groq python-dotenv pandas tqdm

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.5)
Requirement already satisfied: rank-bm25 in /usr/local/lib/python3.12/dist-packages (0.2.2)
Requirement already satisfied: groq in /usr/local/lib/python3.12/dist-packages (1.1.1)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.42.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.24.4)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.40.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-proto==1.40.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.40.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.61b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.61b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.6)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

# Verify the sqlite size is correct after mounting
import os
size = os.path.getsize("/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/chroma_db/chroma.sqlite3")
print(f"SQLite size: {size / 1024 / 1024:.1f} MB")  # should be ~250MB

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
SQLite size: 557.2 MB

In [4]:
import os
os.environ["GEMINI_API_KEY"] = "AIzaSyDi03FSjM-wYaf-QAaDhB9uMyBneXD3q-Q"

## 1. Configuration

In [5]:
CONFIG = {
    # --- Paths (Google Drive) ---
    "chroma_db_path": "/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/chroma_db",
    "chunks_path":    "/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/sec_data/chunks/sec_chunks.jsonl",
    "eval_path":      "/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/GenAI Eval QA.csv",
    "results_dir":    "/content/results",

    # --- Models ---
    "dense_model_name":   "nomic-ai/nomic-embed-text-v1.5",
    "reranker_model_name":"cross-encoder/ms-marco-MiniLM-L-6-v2",
    "execution_profile":  "dev",
    "gemini_dev_model":   "gemini-2.5-flash",
    "gemini_final_model": "gemini-2.5-flash",
    "agent_model":        "gemini-2.5-flash",
    "judge_model":        "gemini-2.5-flash",

    # --- Retrieval ---
    "bm25_top_k":        15,
    "dense_top_k":       15,
    "rerank_top_k":      7,
    "multi_query_n":     2,
    "rrf_k":             60,

    # --- Context compression ---
    "compress_top_sentences": 4,

    # --- Generation ---
    "max_context_chars":     9000,
    "temperature_rewriter":  0.2,
    "temperature_generator": 0.2,
    "temperature_judge":     0.1,
    "max_tokens_answer":     512,
    "max_tokens_judge":      256,

    # --- Cost tracking ---
    "gemini_cost_input_per_1m":  0.10,
    "gemini_cost_output_per_1m": 0.40,

    # --- Evaluation ---
    "eval_max_questions": None,       # ← ADD THIS. Set to None to run all

    # --- Rate limiting ---
    "max_rpm":                    10,
    "inter_question_sleep_sec":   40,
    "llm_max_retries":            3,
    "llm_retry_base_delay_sec":   5,
}

## 2. Imports & Setup

In [6]:
import os
import re
import json
import time
import threading
from collections import deque, Counter as _Counter
from pathlib import Path
from typing import Optional
import re as _re

import numpy as np
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv
from pydantic import BaseModel, Field

import chromadb
from sentence_transformers import SentenceTransformer, CrossEncoder
from rank_bm25 import BM25Okapi
from google import genai
from google.genai import types as genai_types

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
assert GEMINI_API_KEY, "Set GEMINI_API_KEY in your .env file"

LLM_MODEL = (
    CONFIG["gemini_final_model"]
    if CONFIG["execution_profile"] == "final"
    else CONFIG["gemini_dev_model"]
)
print(f"Execution profile : {CONFIG['execution_profile']}")
print(f"LLM model         : {LLM_MODEL}")

Execution profile : dev
LLM model         : gemini-2.5-flash

## 3. Load Models

In [7]:
CONFIG["reranker_model_name"] = "cross-encoder/ms-marco-MiniLM-L-6-v2"

In [8]:
print("Loading embedding model...")
embed_model = SentenceTransformer(
    CONFIG["dense_model_name"],
    trust_remote_code=True,
)
print(f"  ok {CONFIG['dense_model_name']}")

print("Loading reranker...")
reranker = CrossEncoder(CONFIG["reranker_model_name"])
print(f"  ok {CONFIG['reranker_model_name']}")

genai_client = genai.Client(api_key=GEMINI_API_KEY)
print(f"  ok Gemini client ready (model: {LLM_MODEL})")


# ── Rate Limiter ───────────────────────────────────────────────────────────────
class RateLimiter:
    def __init__(self, max_rpm: int):
        self.max_rpm = max_rpm
        self._ts: deque = deque()
        self._lock = threading.Lock()

    def wait(self):
        with self._lock:
            now = time.time()
            while self._ts and now - self._ts[0] >= 60.0:
                self._ts.popleft()
            if len(self._ts) >= self.max_rpm:
                sleep_for = 60.0 - (now - self._ts[0])
                if sleep_for > 0:
                    print(f"  [RateLimit] sleeping {sleep_for:.1f}s ...")
                    time.sleep(sleep_for)
            self._ts.append(time.time())

rate_limiter = RateLimiter(CONFIG["max_rpm"])


# ── Per-Question Token Accumulator ─────────────────────────────────────────────
_question_tokens: dict = {}

def _reset_question_tokens() -> None:
    global _question_tokens
    _question_tokens = {}

def _add_tokens(step: str, input_tok: int, output_tok: int) -> None:
    if step not in _question_tokens:
        _question_tokens[step] = {'input': 0, 'output': 0}
    _question_tokens[step]['input']  += int(input_tok  or 0)
    _question_tokens[step]['output'] += int(output_tok or 0)

def _get_question_token_totals() -> tuple:
    total_in  = sum(v['input']  for v in _question_tokens.values())
    total_out = sum(v['output'] for v in _question_tokens.values())
    return total_in, total_out

def _estimate_cost_usd(total_input: int, total_output: int) -> float:
    rate_in  = CONFIG.get('gemini_cost_input_per_1m',  0.10) / 1_000_000
    rate_out = CONFIG.get('gemini_cost_output_per_1m', 0.40) / 1_000_000
    return total_input * rate_in + total_output * rate_out


# ── LLM Call ───────────────────────────────────────────────────────────────────
def call_llm(
    messages: list,
    model: str = None,
    temperature: float = 0.2,
    max_tokens: int = 512,
    json_mode: bool = False,
    step: str = 'generate',
) -> str:
    """Call Gemini with retry. Accumulates tokens to _question_tokens[step]."""
    model = model or LLM_MODEL
    system_instruction = None
    user_parts = []
    for msg in messages:
        if msg["role"] == "system":
            system_instruction = msg["content"]
        else:
            user_parts.append(msg["content"])
    contents = "\n\n".join(user_parts) if user_parts else ""

    cfg_kwargs = dict(temperature=temperature, max_output_tokens=max_tokens)
    if json_mode:
        cfg_kwargs["response_mime_type"] = "application/json"
    if system_instruction:
        cfg_kwargs["system_instruction"] = system_instruction

    for attempt in range(CONFIG["llm_max_retries"]):
        try:
            rate_limiter.wait()
            resp = genai_client.models.generate_content(
                model=model,
                contents=contents,
                config=genai_types.GenerateContentConfig(**cfg_kwargs),
            )
            if step and resp.usage_metadata:
                _add_tokens(step,
                    resp.usage_metadata.prompt_token_count     or 0,
                    resp.usage_metadata.candidates_token_count or 0)
            return resp.text.strip()
        except Exception as e:
            delay = CONFIG["llm_retry_base_delay_sec"] * (2 ** attempt)
            print(f"  [WARN] attempt {attempt+1}/{CONFIG['llm_max_retries']} failed ({e}). Retrying in {delay}s...")
            time.sleep(delay)
    raise RuntimeError(f"LLM call failed after {CONFIG['llm_max_retries']} attempts")


# ── Heuristic Scoring Utilities ────────────────────────────────────────────────
def _tokenize(text: str) -> list:
    return _re.sub(r'[^\w\s]', '', text.lower()).split()

def token_f1_score(pred: str, ref: str) -> float:
    if not pred or not ref:
        return 0.0
    pred_toks = _tokenize(pred)
    ref_toks  = _tokenize(ref)
    if not pred_toks or not ref_toks:
        return 0.0
    common = sum((_Counter(pred_toks) & _Counter(ref_toks)).values())
    if common == 0:
        return 0.0
    precision = common / len(pred_toks)
    recall    = common / len(ref_toks)
    return 2 * precision * recall / (precision + recall)

def numerical_accuracy_score(pred: str, ref: str) -> Optional[float]:
    nums_ref  = [float(n.replace(',', '')) for n in _re.findall(r'-?\d[\d,]*\.?\d*', ref)]
    nums_pred = [float(n.replace(',', '')) for n in _re.findall(r'-?\d[\d,]*\.?\d*', pred)]
    if not nums_ref:
        return None
    hits = sum(
        1 for r in nums_ref
        if any(abs(p - r) / (abs(r) + 1e-9) < 0.01 for p in nums_pred)
    )
    return hits / len(nums_ref)

def compute_decision_from_text(answer_text: str) -> str:
    lower = answer_text.lower()
    refusal_phrases = [
        'insufficient', 'not contain', 'not available', 'cannot find',
        "don't have", 'no information', 'not provided', 'unable to',
        'not enough', 'not present', 'not found', 'insufficient data',
    ]
    return 'refuse' if any(p in lower for p in refusal_phrases) else 'answer'


# ── Structured Judge (matches CrewAI) ─────────────────────────────────────────
class JudgeOutput(BaseModel):
    score:          float = Field(default=0.0, description='Score 0.0-1.0')
    claims_covered: float = Field(default=0.0, description='Fraction of key facts covered 0.0-1.0')
    reason:         str   = Field(default='',  description='Short explanation')

def _build_correctness_prompt(question: str, reference_answer: str, candidate_answer: str) -> str:
    return (
        'Score the candidate answer against the reference answer from 0 to 1 for a financial QA task. '
        '1 = correct value, correct units, correct period. '
        '0 = wrong number, wrong company, wrong period, or completely missing. '
        'Give partial credit for answers close but with unit errors. '
        'Also set claims_covered: fraction of distinct facts/numbers in the reference present in the candidate. '
        'Return a valid JSON object only that matches the requested schema.\n\n'
        f'Question:\n{question}\n\n'
        f'Reference answer:\n{reference_answer}\n\n'
        f'Candidate answer:\n{candidate_answer}'
    )

def _build_faithfulness_prompt(question: str, context: str, candidate_answer: str) -> str:
    return (
        'Score how well the candidate answer is grounded in the retrieved filing context from 0 to 1. '
        '1 = every number and claim is directly supported by the context. '
        '0 = answer contains numbers or claims not present in the context (hallucinated). '
        'Also set claims_covered: fraction of claims in the candidate supported by the context. '
        'Return a valid JSON object only that matches the requested schema.\n\n'
        f'Question:\n{question}\n\n'
        f'Retrieved context:\n{context}\n\n'
        f'Candidate answer:\n{candidate_answer}'
    )

def _safe_judge_call(prompt_text: str, task_name: str) -> JudgeOutput:
    _fb = JudgeOutput(score=0.0, claims_covered=0.0, reason='judge fallback — all attempts failed')
    for attempt in range(CONFIG["llm_max_retries"]):
        try:
            rate_limiter.wait()
            response = genai_client.models.generate_content(
                model=CONFIG["judge_model"],
                contents=prompt_text,
                config=genai_types.GenerateContentConfig(
                    response_mime_type='application/json',
                    response_schema=JudgeOutput,
                    temperature=CONFIG.get('temperature_judge', 0.1),
                ),
            )
            if response.usage_metadata:
                _add_tokens(task_name,
                    response.usage_metadata.prompt_token_count     or 0,
                    response.usage_metadata.candidates_token_count or 0)
            result = response.parsed
            if result is None:
                result = JudgeOutput(**json.loads(response.text))
            return result
        except Exception as e:
            print(f"  [WARN] Judge ({task_name}) attempt {attempt+1} failed: {e}")
            if attempt < CONFIG["llm_max_retries"] - 1:
                time.sleep(CONFIG["llm_retry_base_delay_sec"] * (2 ** attempt))
    return _fb

def llm_judge_correctness(question: str, reference_answer: str, candidate_answer: str) -> tuple:
    result = _safe_judge_call(
        _build_correctness_prompt(question, reference_answer, candidate_answer),
        task_name='judge_correctness',
    )
    return (max(0.0, min(1.0, float(result.score))),
            max(0.0, min(1.0, float(result.claims_covered))),
            result.reason)

def llm_judge_faithfulness(question: str, context: str, candidate_answer: str) -> tuple:
    result = _safe_judge_call(
        _build_faithfulness_prompt(question, context[:CONFIG.get('max_context_chars', 9000)], candidate_answer),
        task_name='judge_faithfulness',
    )
    return (max(0.0, min(1.0, float(result.score))),
            max(0.0, min(1.0, float(result.claims_covered))),
            result.reason)

print("Client, rate limiter, token tracking, heuristics, and judge ready.")

Loading embedding model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

  ok nomic-ai/nomic-embed-text-v1.5
Loading reranker...

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  ok cross-encoder/ms-marco-MiniLM-L-6-v2
  ok Gemini client ready (model: gemini-2.5-flash)
Client, rate limiter, token tracking, heuristics, and judge ready.

## 4. Load Data

In [9]:
# --- ChromaDB ---
print("Connecting to ChromaDB...")
chroma_client = chromadb.PersistentClient(path=CONFIG["chroma_db_path"])
collections = chroma_client.list_collections()
collection = chroma_client.get_collection(collections[0].name)
print(f"  ok '{collections[0].name}'  ({collection.count():,} chunks)")

# --- JSONL chunks (needed for BM25) ---
print("Loading SEC chunks from JSONL...")
raw_chunks = []
with open(CONFIG["chunks_path"], "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            raw_chunks.append(json.loads(line))

chunks_df = pd.DataFrame(raw_chunks)

# Filter low-value chunks (matching the existing pipeline)
if "flag_low_value_combined" in chunks_df.columns:
    before = len(chunks_df)
    chunks_df = chunks_df[~chunks_df["flag_low_value_combined"].fillna(False)].reset_index(drop=True)
    print(f"  Filtered {before - len(chunks_df)} low-value chunks")

print(f"  ok {len(chunks_df):,} chunks loaded")


def make_contextual_chunk(row) -> str:
    """Reconstruct the contextual chunk text (must match what was stored in ChromaDB)."""
    company = row.get("company_name", row.get("company", "?"))
    ticker  = row.get("ticker", "?")
    form    = row.get("form_type", "?")
    date    = str(row.get("filing_date", "?"))[:10]
    year    = row.get("filing_year", "?")
    section = row.get("section_title", "?")
    text    = row.get("text", row.get("raw_chunk", ""))
    return (
        f"Company: {company} ({ticker})\n"
        f"Filing: {form} | Date: {date} | Year: {year}\n"
        f"Section: {section}\n"
        f"Content: {text}"
    )


# Build contextual chunks column and BM25 tokens
chunks_df["contextual_chunk"] = chunks_df.apply(make_contextual_chunk, axis=1)
chunks_df["bm25_tokens"] = chunks_df["contextual_chunk"].str.lower().str.split()

# Build BM25 index
print("Building BM25 index...")
bm25_index = BM25Okapi(chunks_df["bm25_tokens"].tolist())
print(f"  ok BM25 index built  ({len(chunks_df):,} documents)")

# --- Adjacent-chunk expansion lookup ---
# Maps chunk_id string -> DataFrame row index (for expand_adjacent)
_chunk_id_to_row = {str(row["chunk_id"]): idx for idx, row in chunks_df.iterrows()}

# Maps (ticker, form_type, filing_date) -> {chunk_index -> df_row_idx}
_filing_chunk_lookup: dict = {}
for idx, row in chunks_df.iterrows():
    key = (str(row["ticker"]), str(row["form_type"]), str(row.get("filing_date", ""))[:10])
    ci  = int(row.get("chunk_index", -1))
    if ci >= 0:
        _filing_chunk_lookup.setdefault(key, {})[ci] = idx

print(f"  ok adjacent-chunk lookup built  ({len(_filing_chunk_lookup)} filings)")

Connecting to ChromaDB...
  ok 'sec_sections'  (588 chunks)
Loading SEC chunks from JSONL...
  Filtered 550 low-value chunks
  ok 12,725 chunks loaded
Building BM25 index...
  ok BM25 index built  (12,725 documents)
  ok adjacent-chunk lookup built  (144 filings)

## 5. Step 1 — Metadata Extraction

Extract company ticker, filing year, and form type from the query to narrow retrieval scope.
This reduces the search space from ~12,600 chunks to only the relevant company/period.

In [10]:
# Known tickers in the dataset
KNOWN_TICKERS = {
    "AAPL", "MSFT", "NVDA", "JPM", "BAC", "BRK.B", "BRK",
    "JNJ", "UNH", "XOM", "CVX", "WMT", "COST",
}

# Company name -> ticker mapping for natural language mentions
COMPANY_TO_TICKER = {
    "apple": "AAPL", "microsoft": "MSFT", "nvidia": "NVDA",
    "jpmorgan": "JPM", "jp morgan": "JPM", "bank of america": "BAC",
    "berkshire": "BRK.B", "johnson": "JNJ", "unitedhealth": "UNH",
    "exxon": "XOM", "exxonmobil": "XOM", "chevron": "CVX",
    "walmart": "WMT", "costco": "COST",
}


def extract_metadata(query: str) -> dict:
    """
    Extract ticker, filing_year, and form_type from query text.
    Uses regex for year/form_type and a lookup table for company names.
    Returns dict with None values for fields not found.
    """
    q_upper = query.upper()
    q_lower = query.lower()

    # --- Ticker ---
    ticker = None
    for t in KNOWN_TICKERS:
        if re.search(r"\b" + re.escape(t) + r"\b", q_upper):
            ticker = t
            break
    if ticker is None:
        for name, t in COMPANY_TO_TICKER.items():
            if name in q_lower:
                ticker = t
                break

    # --- Filing year (2020-2029) ---
    year_match = re.search(r"\b(202[0-9])\b", query)
    filing_year = int(year_match.group(1)) if year_match else None

    # --- Form type ---
    form_type = None
    if re.search(r"\b10-K\b|\bannual report\b|\bannual filing\b", query, re.IGNORECASE):
        form_type = "10-K"
    elif re.search(r"\b10-Q\b|\bquarterly report\b|\bquarterly filing\b", query, re.IGNORECASE):
        form_type = "10-Q"

    return {"ticker": ticker, "filing_year": filing_year, "form_type": form_type}


# Quick test
print(extract_metadata("What was Apple's revenue in fiscal 2024 10-K?"))
print(extract_metadata("Compare NVDA and MSFT operating income for 2023"))

{'ticker': 'AAPL', 'filing_year': 2024, 'form_type': '10-K'}
{'ticker': 'NVDA', 'filing_year': 2023, 'form_type': None}

## 6. Step 2 — Query Rewriting

Rewrite the user's question into a retrieval-optimised query.
Financial questions often use colloquial phrasing ("how much did they make") that doesn't match
document language ("net revenue", "operating income"). A single LLM call fixes the vocabulary mismatch.

In [11]:
REWRITE_SYSTEM = (
    "You are a search query optimizer for SEC filings (10-K, 10-Q). "
    "Rewrite the user's question as a concise retrieval query that maximizes recall of relevant "
    "financial document chunks. Use precise financial terminology (e.g., 'net revenue', "
    "'operating income', 'diluted EPS'). Keep it under 25 words. "
    "Return only the rewritten query, nothing else."
)


def rewrite_query(query: str) -> str:
    """Rewrite query for better retrieval alignment with financial document language."""
    return call_llm(
        messages=[
            {"role": "system", "content": REWRITE_SYSTEM},
            {"role": "user",   "content": query},
        ],
        model=CONFIG["agent_model"],
        temperature=CONFIG["temperature_rewriter"],
        max_tokens=80,
    )

## 7. Step 3 — Multi-Query Generation

Generate additional query variants to increase retrieval coverage.
Different phrasings surface different relevant chunks — e.g., asking about "revenue growth"
and "year-over-year revenue change" may retrieve complementary passages.

In [12]:
MULTI_QUERY_SYSTEM = (
    "Generate {n} alternative retrieval queries for the following question about SEC filings. "
    "Each variant should use different financial terminology or focus on a different aspect "
    "of the question to maximise retrieval coverage. "
    'Return a JSON object with key "queries" containing an array of {n} query strings.'
)


def generate_multi_queries(query: str, n: int = None) -> list:
    """Generate n alternative query variants for multi-query retrieval."""
    n = n or CONFIG["multi_query_n"]
    raw = call_llm(
        messages=[
            {"role": "system", "content": MULTI_QUERY_SYSTEM.format(n=n)},
            {"role": "user",   "content": query},
        ],
        model=CONFIG["agent_model"],
        temperature=CONFIG["temperature_rewriter"],
        max_tokens=200,
        json_mode=True,
    )
    try:
        data = json.loads(raw)
        return data.get("queries", [])[:n]
    except Exception:
        return []

## 8. Step 4 — Hybrid Search (BM25 + Dense + RRF)

BM25 excels at exact financial term matching ("EBITDA", "diluted EPS", specific dollar figures).
Dense retrieval excels at semantic similarity.
Reciprocal Rank Fusion (RRF) combines both ranked lists without requiring score normalisation.
Metadata filtering further restricts results to the relevant company/year.

In [13]:
def build_bm25_mask(ticker=None, filing_year=None, form_type=None) -> np.ndarray:
    """Boolean mask to restrict BM25 search to matching metadata."""
    mask = np.ones(len(chunks_df), dtype=bool)
    if ticker:
        mask &= (chunks_df["ticker"].str.upper() == ticker.upper()).values
    if filing_year:
        mask &= (chunks_df["filing_year"].astype(int) == int(filing_year)).values
    if form_type:
        mask &= (chunks_df["form_type"].str.upper() == form_type.upper()).values
    return mask


def bm25_search(query: str, top_k: int, mask: np.ndarray = None) -> list:
    """BM25 retrieval over contextual chunks with optional metadata mask."""
    tokens = query.lower().split()
    scores = bm25_index.get_scores(tokens)
    if mask is not None:
        scores = scores * mask.astype(float)
    top_idx = np.argsort(scores)[::-1]
    # Keep only positive-scoring results
    top_idx = [i for i in top_idx if scores[i] > 0][:top_k]
    results = []
    for i in top_idx:
        row = chunks_df.iloc[i]
        results.append({
            "text":     row["contextual_chunk"],
            "metadata": {
                "ticker":      row.get("ticker", "?"),
                "form_type":   row.get("form_type", "?"),
                "filing_year": int(row.get("filing_year", 0)),
                "company":     row.get("company_name", row.get("company", "?")),
            },
            "score":    float(scores[i]),
            "chunk_id": str(row.get("chunk_id", i)),
        })
    return results


def dense_search(query: str, top_k: int, ticker=None, filing_year=None, form_type=None) -> list:
    """Dense (semantic) retrieval with optional ChromaDB metadata filtering."""
    query_vec = embed_model.encode("search_query: " + query, normalize_embeddings=True).tolist()

    filters = []
    if ticker:
        filters.append({"ticker": {"$eq": ticker}})
    if filing_year:
        filters.append({"filing_year": {"$eq": int(filing_year)}})
    if form_type:
        filters.append({"form_type": {"$eq": form_type}})

    kwargs = dict(
        query_embeddings=[query_vec],
        n_results=min(top_k, collection.count()),
        include=["documents", "metadatas", "distances"],
    )

    if len(filters) == 1:
        kwargs["where"] = filters[0]
    elif len(filters) > 1:
        kwargs["where"] = {"$and": filters}

    results = collection.query(**kwargs)

    chunks = []
    for doc, meta, dist, cid in zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0],
        results["ids"][0],
    ):
        chunks.append({
            "text": doc,
            "metadata": meta,
            "score": float(1.0 - dist),
            "chunk_id": cid,
        })

    return chunks


def rrf_merge(result_lists: list, k: int = None) -> list:
    """
    Reciprocal Rank Fusion over multiple ranked lists.
    Formula: score(d) = sum_i 1 / (k + rank_i(d) + 1)
    """
    k = k or CONFIG["rrf_k"]
    scores = {}
    pool   = {}
    for ranked_list in result_lists:
        for rank, chunk in enumerate(ranked_list):
            cid = chunk["chunk_id"]
            scores[cid] = scores.get(cid, 0.0) + 1.0 / (k + rank + 1)
            if cid not in pool:
                pool[cid] = chunk
    merged = []
    for cid in sorted(scores, key=scores.__getitem__, reverse=True):
        c = dict(pool[cid])
        c["score"] = scores[cid]
        merged.append(c)
    return merged


def expand_adjacent(candidates: list, expand_n: int = 1) -> list:
    """
    For each chunk in the RRF pool, add the immediately preceding and following
    chunks within the same filing to the candidate pool (score=0.0).
    These extras enter the CrossEncoder reranking pool — the reranker then decides
    whether they're actually relevant, recovering table headers split from data rows.
    """
    existing_ids = {c["chunk_id"] for c in candidates}
    extras = {}

    for chunk in candidates:
        row_idx = _chunk_id_to_row.get(chunk["chunk_id"])
        if row_idx is None:
            continue
        row     = chunks_df.iloc[row_idx]
        base_ci = int(row.get("chunk_index", -1))
        if base_ci < 0:
            continue
        key    = (str(row["ticker"]), str(row["form_type"]), str(row.get("filing_date", ""))[:10])
        ci_map = _filing_chunk_lookup.get(key, {})

        for delta in range(-expand_n, expand_n + 1):
            if delta == 0:
                continue
            adj_idx = ci_map.get(base_ci + delta)
            if adj_idx is None:
                continue
            adj_row = chunks_df.iloc[adj_idx]
            adj_id  = str(adj_row["chunk_id"])
            if adj_id in existing_ids or adj_id in extras:
                continue
            extras[adj_id] = {
                "text":     adj_row["contextual_chunk"],
                "metadata": {
                    "ticker":      adj_row.get("ticker", "?"),
                    "form_type":   adj_row.get("form_type", "?"),
                    "filing_year": int(adj_row.get("filing_year", 0)),
                    "company":     adj_row.get("company_name", adj_row.get("company", "?")),
                },
                "score":    0.0,
                "chunk_id": adj_id,
            }

    return candidates + list(extras.values())

## 9. Step 5 — CrossEncoder Reranking

The bi-encoder embedding model scores query and document independently (fast but approximate).
The CrossEncoder attends to both simultaneously, giving more accurate relevance scores.
Applied to the top RRF candidates to select the final context.

In [14]:
def rerank(candidates: list, query: str, top_k: int = None) -> list:
    """Rerank candidate chunks using CrossEncoder (query, chunk) scoring."""
    top_k = top_k or CONFIG["rerank_top_k"]
    if not candidates:
        return []
    pairs  = [(query, c["text"]) for c in candidates]
    scores = reranker.predict(pairs, show_progress_bar=False)
    for c, s in zip(candidates, scores):
        c["rerank_score"] = float(s)
    return sorted(candidates, key=lambda x: x["rerank_score"], reverse=True)[:top_k]

## 10. Step 6 — Context Compression

Each retrieved chunk may contain irrelevant sentences.
We extract only the most relevant sentences (scored by CrossEncoder against the query),
reducing noise in the LLM context window.

In [15]:
def compress_chunk(chunk: dict, query: str, top_n: int = None) -> dict:
    """
    Extract the most relevant sentences from a chunk using CrossEncoder scoring.
    Keeps the structured header (Company/Filing/Section) and replaces the content
    with only the top-N most relevant sentences.
    """
    top_n = top_n or CONFIG["compress_top_sentences"]
    if top_n is None:
        return chunk  # compression disabled

    text = chunk["text"]

    # Separate header (Company/Filing/Section lines) from content
    if "\nContent:" in text:
        header, _, content = text.partition("\nContent:")
        header = header + "\nContent:"
    else:
        header = ""
        content = text

    # Simple sentence splitting (handles ., !, ?, ;)
    sentences = re.split(r"(?<=[.!?;])\s+", content.strip())
    sentences = [s.strip() for s in sentences if len(s.strip()) > 25]

    if len(sentences) <= top_n:
        return chunk  # already short enough

    # Score each sentence against the query
    pairs  = [(query, s) for s in sentences]
    scores = reranker.predict(pairs, show_progress_bar=False)

    # Keep top-N sentences in original document order
    top_idx = sorted(
        sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:top_n]
    )
    compressed_content = " ".join(sentences[i] for i in top_idx)

    new_chunk = dict(chunk)
    new_chunk["text"] = (header + " " + compressed_content).strip()
    new_chunk["compressed"] = True
    return new_chunk


def compress_context(chunks: list, query: str) -> list:
    """Compress all chunks in the context."""
    return [compress_chunk(c, query) for c in chunks]

## 11. Step 7 — Generation with Citations

Instructs the LLM to cite source chunks using [n] notation.
This improves traceability and allows users to verify claims against the original filings.

In [16]:
GENERATOR_SYSTEM_ADV = (
    "You are a financial analyst answering questions using only the retrieved filing context.\n"
    "Rules:\n"
    "- Be precise with numbers -- include units (millions, billions, %), fiscal periods, and line item names.\n"
    "- Cite your sources using [n] notation after each claim (e.g., 'Revenue was $394B in FY2024 [1]').\n"
    "- Only use information present in the provided context.\n"
    "- If the context does not contain enough information, say 'Insufficient information in the provided filings.'"
)


def format_context_adv(chunks: list, max_chars: int = None) -> str:
    """Format chunks with numbered headers for citation."""
    max_chars = max_chars or CONFIG["max_context_chars"]
    parts = []
    for i, c in enumerate(chunks, 1):
        m = c["metadata"]
        header = (
            f"[{i}] {m.get('ticker','?')} {m.get('form_type','?')} "
            f"{m.get('filing_year','?')} | {m.get('company','')}"
        )
        parts.append(f"{header}\n{c['text']}")
    context = "\n\n---\n\n".join(parts)
    return context[:max_chars]


def generate_with_citations(query: str, chunks: list) -> str:
    """Generate an answer with [n] citations referencing the retrieved chunks."""
    context  = format_context_adv(chunks)
    user_msg = f"Question:\n{query}\n\nRetrieved context (cite [n] for each claim):\n{context}"
    return call_llm(
        messages=[
            {"role": "system", "content": GENERATOR_SYSTEM_ADV},
            {"role": "user",   "content": user_msg},
        ],
        temperature=CONFIG["temperature_generator"],
        max_tokens=CONFIG["max_tokens_answer"],
    )

## 12. Full Advanced RAG Pipeline

In [17]:
def advanced_rag(query: str, verbose: bool = False) -> dict:
    """
    Advanced RAG pipeline:
    1. Metadata extraction  -> filter to relevant company/year
    2. Query rewriting      -> align with financial document vocabulary
    3. Multi-query          -> generate additional query variants
    4. Hybrid retrieval     -> BM25 + Dense for each query variant
    5. RRF merge            -> combine all ranked lists
    6. Adjacent expansion   -> add neighboring chunks to recover split tables
    7. CrossEncoder rerank  -> accurate relevance re-scoring
    8. Context compression  -> keep only most relevant sentences
    9. Generation           -> answer with [n] citations
    """
    # 1. Metadata extraction
    meta = extract_metadata(query)
    if verbose:
        print(f"  [Meta]     {meta}")

    # 2. Query rewriting
    rewritten = rewrite_query(query)
    if verbose:
        print(f"  [Rewrite]  {rewritten}")

    # 3. Multi-query generation
    variants    = generate_multi_queries(rewritten)
    all_queries = [rewritten] + variants
    if verbose:
        print(f"  [Queries]  {all_queries}")

    # 4. Hybrid retrieval (BM25 + Dense) for each query variant
    bm25_mask    = build_bm25_mask(**meta)
    ranked_lists = []
    for q in all_queries:
        ranked_lists.append(bm25_search(q, CONFIG["bm25_top_k"], bm25_mask))
        ranked_lists.append(dense_search(q, CONFIG["dense_top_k"], **meta))

    # 5. RRF merge
    candidates = rrf_merge(ranked_lists)
    if verbose:
        print(f"  [RRF]      {len(candidates)} unique candidates after merge")

    # 6. Adjacent expansion — add chunk_index ± 1 within the same filing
    candidates = expand_adjacent(candidates, expand_n=1)
    if verbose:
        print(f"  [Expand]   {len(candidates)} candidates after adjacent expansion")

    # 7. CrossEncoder reranking
    reranked = rerank(candidates, rewritten)
    if verbose:
        print(f"  [Rerank]   top {len(reranked)} chunks selected")

    # 8. Context compression
    compressed = compress_context(reranked, rewritten)

    # 9. Generation with citations
    context = format_context_adv(compressed)
    answer  = generate_with_citations(query, compressed)

    return {
        "query":      query,
        "rewritten":  rewritten,
        "variants":   variants,
        "metadata":   meta,
        "answer":     answer,
        "chunks":     reranked,
        "context":    context,
        "n_chunks":   len(reranked),
    }

### Quick Demo

In [18]:
demo_q = "What was Apple's total net revenue for fiscal year 2024?"
result = advanced_rag(demo_q, verbose=True)

print()
print("QUESTION:", result["query"])
print()
print("ANSWER:", result["answer"])
print()
print(f"Metadata extracted : {result['metadata']}")
print(f"Rewritten query    : {result['rewritten']}")
print(f"Query variants     : {result['variants']}")
print()
print(f"Retrieved {result['n_chunks']} chunks:")
for i, c in enumerate(result["chunks"], 1):
    m = c["metadata"]
    score = c.get("rerank_score", c.get("score", 0))
    compressed = "(compressed)" if c.get("compressed") else ""
    print(f"  [{i}] {m.get('ticker','?'):6s}  {m.get('form_type','?'):5s}  "
          f"year={m.get('filing_year','?')}  rerank={score:.3f}  {compressed}")

  [Meta]     {'ticker': 'AAPL', 'filing_year': 2024, 'form_type': None}
  [Rewrite]  Apple
  [Queries]  ['Apple']
  [RRF]      15 unique candidates after merge
  [Expand]   28 candidates after adjacent expansion
  [Rerank]   top 7 chunks selected

QUESTION: What was Apple's total net revenue for fiscal year 2024?

ANSWER: The provided filings contain Apple's total net sales for the nine months ended June 29,

Metadata extracted : {'ticker': 'AAPL', 'filing_year': 2024, 'form_type': None}
Rewritten query    : Apple
Query variants     : []

Retrieved 7 chunks:
  [1] AAPL    10-Q   year=2024  rerank=2.937
  [2] AAPL    10-Q   year=2024  rerank=2.690
  [3] AAPL    10-Q   year=2024  rerank=2.562
  [4] AAPL    10-Q   year=2024  rerank=2.049
  [5] AAPL    10-Q   year=2024  rerank=1.942
  [6] AAPL    10-Q   year=2024  rerank=1.927
  [7] AAPL    10-K   year=2024  rerank=1.769

## 13. Evaluation (LLM-as-Judge)

Same judge prompts as Baseline RAG for fair comparison.
Results are saved to `./results/advanced_results.csv`.

In [19]:
CONFIG["eval_path"]

'/content/drive/MyDrive/sec_rag_team_share_clean_upgrade/GenAI Eval QA.csv'

In [20]:
eval_df = pd.read_csv(CONFIG["eval_path"])
# no split filter — load everything
if CONFIG.get("eval_max_questions"):
    eval_df = eval_df.head(CONFIG["eval_max_questions"])

print(f"Total questions : {len(eval_df)}")
print(eval_df["question_type"].value_counts().to_string())

Total questions : 100
question_type
extractive     25
paraphrased    25
reasoning      25
adversarial    25

In [21]:
results = []

for idx, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc="Evaluating advanced"):
    question          = str(row["question"])
    reference_answer  = str(row["expected_answer"]).strip()
    question_id       = row.get("question_id", idx)
    question_type     = row.get("question_type", "unknown")
    company           = row.get("company", "")
    ticker            = row.get("ticker", "")
    form_type         = row.get("form_type", "")
    filing_year       = row.get("filing_year", None)
    expected_decision = str(row.get("expected_decision", "answer")).lower().strip()

    print(f'\nQ{idx+1}/{len(eval_df)} [{question_type}]  {ticker}  {filing_year}')

    # ── Reset token accumulator ────────────────────────────────────────────────
    _reset_question_tokens()

    # ── Run pipeline ──────────────────────────────────────────────────────────
    t0 = time.time()
    rag = advanced_rag(question)
    latency_sec  = round(time.time() - t0, 2)
    final_answer = rag["answer"]
    context      = rag["context"]

    # ── Heuristic scores ───────────────────────────────────────────────────────
    t_f1    = token_f1_score(final_answer, reference_answer) if reference_answer else None
    num_acc = numerical_accuracy_score(final_answer, reference_answer) if reference_answer else None
    predicted_decision = compute_decision_from_text(final_answer)
    decision_accuracy  = 1.0 if predicted_decision == expected_decision else 0.0

    # ── LLM Judge ──────────────────────────────────────────────────────────────
    is_unanswerable = (
        str(row.get("expected_answer", "")).strip().lower() in ("nan", "", "none")
        or expected_decision == "refuse"
    )
    if is_unanswerable:
        c_score   = decision_accuracy
        c_covered = decision_accuracy
        c_reason  = "Adversarial: scored by decision accuracy (refuse=correct)"
        f_score, _, f_reason = llm_judge_faithfulness(question, context, final_answer)
    else:
        c_score, c_covered, c_reason = llm_judge_correctness(question, reference_answer, final_answer)
        f_score, _,         f_reason = llm_judge_faithfulness(question, context, final_answer)

    # ── Token / cost summary ───────────────────────────────────────────────────
    gen_tok   = _question_tokens.get('generate',          {'input': 0, 'output': 0})
    corr_tok  = _question_tokens.get('judge_correctness', {'input': 0, 'output': 0})
    faith_tok = _question_tokens.get('judge_faithfulness',{'input': 0, 'output': 0})
    total_in, total_out = _get_question_token_totals()
    est_cost = _estimate_cost_usd(total_in, total_out)

    f1_str = f"{t_f1:.2f}" if t_f1 is not None else "N/A"
    print(f'  corr={c_score:.2f}  faith={f_score:.2f}  f1={f1_str}  '\
          f'tokens={total_in}in/{total_out}out  est=${est_cost:.5f}')

    results.append({
        "question_id":              question_id,
        "question":                 question,
        "question_type":            question_type,
        "company":                  company,
        "ticker":                   ticker,
        "form_type":                form_type,
        "filing_year":              filing_year,
        "reference_answer":         reference_answer,
        "expected_decision":        expected_decision,
        "final_answer":             final_answer,
        "pipeline":                 "advanced_rag",
        "n_chunks":                 rag["n_chunks"],
        "rewritten_query":          rag["rewritten"],
        "latency_sec":              latency_sec,
        "token_f1":                 t_f1,
        "numerical_accuracy":       num_acc,
        "decision_accuracy":        decision_accuracy,
        "predicted_decision":       predicted_decision,
        "llm_correctness_score":    c_score,
        "llm_claims_covered":       c_covered,
        "llm_correctness_reason":   c_reason,
        "llm_faithfulness_score":   f_score,
        "llm_faithfulness_reason":  f_reason,
        "model_generator":          LLM_MODEL,
        "model_judge_correctness":  CONFIG["judge_model"],
        "model_judge_faithfulness": CONFIG["judge_model"],
        "tokens_generate_input":    gen_tok["input"],
        "tokens_generate_output":   gen_tok["output"],
        "tokens_judge_corr_input":  corr_tok["input"],
        "tokens_judge_corr_output": corr_tok["output"],
        "tokens_judge_faith_input": faith_tok["input"],
        "tokens_judge_faith_output":faith_tok["output"],
        "tokens_total_input":       total_in,
        "tokens_total_output":      total_out,
        "est_cost_usd":             est_cost,
    })
    time.sleep(CONFIG["inter_question_sleep_sec"])

results_df = pd.DataFrame(results)
out_path = Path(CONFIG["results_dir"]) / "drive/advanced_results.csv"
Path(out_path).parent.mkdir(parents=True, exist_ok=True)
results_df.to_csv(out_path, index=False)
print(f"\nSaved {len(results_df)} rows -> {out_path}")

Evaluating advanced:   0%|          | 0/100 [00:00<?, ?it/s]

Q1/100 [extractive]  AAPL  2023.0
  corr=0.00  faith=1.00  f1=0.62  tokens=10624in/182out  est=$0.00114

Evaluating advanced:   1%|          | 1/100 [00:54<1:30:07, 54.62s/it]

Q2/100 [extractive]  AAPL  2025.0
  corr=0.00  faith=1.00  f1=0.25  tokens=9421in/195out  est=$0.00102

Evaluating advanced:   2%|▏         | 2/100 [01:45<1:25:14, 52.19s/it]

Q3/100 [extractive]  MSFT  2023.0
  corr=0.00  faith=0.30  f1=0.14  tokens=6731in/212out  est=$0.00076

Evaluating advanced:   3%|▎         | 3/100 [02:41<1:27:34, 54.17s/it]

Q4/100 [extractive]  MSFT  2023.0
  corr=0.00  faith=1.00  f1=0.21  tokens=9021in/134out  est=$0.00096

Evaluating advanced:   4%|▍         | 4/100 [03:30<1:23:22, 52.11s/it]

Q5/100 [extractive]  NVDA  2025.0
  corr=0.90  faith=1.00  f1=0.19  tokens=5668in/176out  est=$0.00064

Evaluating advanced:   5%|▌         | 5/100 [04:22<1:22:37, 52.19s/it]

Q6/100 [extractive]  NVDA  2024.0
  corr=0.00  faith=1.00  f1=0.11  tokens=583in/106out  est=$0.00010

Evaluating advanced:   6%|▌         | 6/100 [05:09<1:18:50, 50.33s/it]

Q7/100 [extractive]  NVDA  2025.0
  corr=0.00  faith=1.00  f1=0.34  tokens=8794in/146out  est=$0.00094

Evaluating advanced:   7%|▋         | 7/100 [05:59<1:17:39, 50.10s/it]

Q8/100 [extractive]  JPM  2023.0
  corr=0.00  faith=1.00  f1=0.00  tokens=3904in/139out  est=$0.00045

Evaluating advanced:   8%|▊         | 8/100 [06:48<1:16:26, 49.85s/it]

Q9/100 [extractive]  JPM  2024.0
  corr=0.00  faith=1.00  f1=0.10  tokens=5942in/111out  est=$0.00064

Evaluating advanced:   9%|▉         | 9/100 [07:38<1:15:40, 49.89s/it]

Q10/100 [extractive]  BAC  2025.0
  corr=0.00  faith=1.00  f1=0.31  tokens=9478in/243out  est=$0.00105

Evaluating advanced:  10%|█         | 10/100 [08:31<1:16:14, 50.83s/it]

Q11/100 [extractive]  BAC  2024.0
  corr=0.00  faith=1.00  f1=0.13  tokens=3977in/141out  est=$0.00045

Evaluating advanced:  11%|█         | 11/100 [09:21<1:15:06, 50.63s/it]

Q12/100 [extractive]  BRK-B  2025.0
  corr=0.00  faith=1.00  f1=0.10  tokens=584in/108out  est=$0.00010

Evaluating advanced:  12%|█▏        | 12/100 [10:08<1:12:29, 49.42s/it]

Q13/100 [extractive]  BRK-B  2023.0
  corr=0.00  faith=1.00  f1=0.06  tokens=627in/100out  est=$0.00010

Evaluating advanced:  13%|█▎        | 13/100 [10:55<1:10:48, 48.84s/it]

Q14/100 [extractive]  JNJ  2025.0
  corr=0.00  faith=1.00  f1=0.12  tokens=6565in/160out  est=$0.00072

Evaluating advanced:  14%|█▍        | 14/100 [11:47<1:11:03, 49.57s/it]

Q15/100 [extractive]  JNJ  2025.0
  corr=0.00  faith=1.00  f1=0.07  tokens=4833in/120out  est=$0.00053

Evaluating advanced:  15%|█▌        | 15/100 [12:36<1:10:17, 49.62s/it]

Q16/100 [extractive]  UNH  2024.0
  corr=0.00  faith=1.00  f1=0.12  tokens=9000in/204out  est=$0.00098

Evaluating advanced:  16%|█▌        | 16/100 [13:27<1:09:56, 49.95s/it]

Q17/100 [extractive]  UNH  2023.0
  corr=0.00  faith=1.00  f1=0.17  tokens=9561in/191out  est=$0.00103

Evaluating advanced:  17%|█▋        | 17/100 [14:17<1:09:02, 49.91s/it]

Q18/100 [extractive]  XOM  2023.0
  corr=0.00  faith=1.00  f1=0.00  tokens=581in/99out  est=$0.00010

Evaluating advanced:  18%|█▊        | 18/100 [15:04<1:06:53, 48.94s/it]

Q19/100 [extractive]  XOM  2025.0
  corr=0.00  faith=1.00  f1=0.17  tokens=3704in/138out  est=$0.00043

Evaluating advanced:  19%|█▉        | 19/100 [15:54<1:06:37, 49.36s/it]

Q20/100 [extractive]  CVX  2024.0
  corr=0.10  faith=1.00  f1=0.35  tokens=9274in/201out  est=$0.00101

Evaluating advanced:  20%|██        | 20/100 [16:55<1:10:33, 52.92s/it]

Q21/100 [extractive]  CVX  2025.0
  corr=0.10  faith=0.50  f1=0.78  tokens=7983in/165out  est=$0.00086

Evaluating advanced:  21%|██        | 21/100 [17:49<1:09:52, 53.07s/it]

Q22/100 [extractive]  WMT  2023.0
  corr=1.00  faith=1.00  f1=0.67  tokens=4553in/166out  est=$0.00052

Evaluating advanced:  22%|██▏       | 22/100 [18:38<1:07:28, 51.91s/it]

Q23/100 [extractive]  WMT  2025.0
  corr=0.00  faith=1.00  f1=0.00  tokens=10255in/119out  est=$0.00107

Evaluating advanced:  23%|██▎       | 23/100 [19:27<1:05:41, 51.19s/it]

Q24/100 [extractive]  COST  2025.0
  corr=0.00  faith=1.00  f1=0.38  tokens=8878in/204out  est=$0.00097

Evaluating advanced:  24%|██▍       | 24/100 [20:23<1:06:46, 52.72s/it]

Q25/100 [extractive]  COST  2023.0
  corr=0.00  faith=1.00  f1=0.09  tokens=8605in/119out  est=$0.00091

Evaluating advanced:  25%|██▌       | 25/100 [21:14<1:05:10, 52.14s/it]

Q26/100 [paraphrased]  AAPL  2023.0
  corr=0.00  faith=1.00  f1=0.21  tokens=10016in/134out  est=$0.00106

Evaluating advanced:  26%|██▌       | 26/100 [22:06<1:04:00, 51.90s/it]

Q27/100 [paraphrased]  AAPL  2025.0
  corr=0.00  faith=1.00  f1=0.20  tokens=10140in/172out  est=$0.00108

Evaluating advanced:  27%|██▋       | 27/100 [22:56<1:02:44, 51.57s/it]

Q28/100 [paraphrased]  MSFT  2023.0
  corr=0.05  faith=0.00  f1=0.09  tokens=5058in/165out  est=$0.00057

Evaluating advanced:  28%|██▊       | 28/100 [23:53<1:03:44, 53.12s/it]

Q29/100 [paraphrased]  MSFT  2023.0
  corr=0.00  faith=1.00  f1=0.12  tokens=3525in/203out  est=$0.00043

Evaluating advanced:  29%|██▉       | 29/100 [24:43<1:01:48, 52.24s/it]

Q30/100 [paraphrased]  NVDA  2025.0
  corr=0.00  faith=1.00  f1=0.00  tokens=5270in/110out  est=$0.00057

Evaluating advanced:  30%|███       | 30/100 [25:34<1:00:16, 51.66s/it]

Q31/100 [paraphrased]  NVDA  2024.0
  corr=0.00  faith=1.00  f1=0.07  tokens=6696in/141out  est=$0.00073

Evaluating advanced:  31%|███       | 31/100 [26:25<59:21, 51.61s/it]

Q32/100 [paraphrased]  NVDA  2025.0
  corr=0.00  faith=1.00  f1=0.11  tokens=3952in/122out  est=$0.00044

Evaluating advanced:  32%|███▏      | 32/100 [27:14<57:41, 50.90s/it]

Q33/100 [paraphrased]  JPM  2023.0
  corr=1.00  faith=1.00  f1=0.35  tokens=7821in/177out  est=$0.00085

Evaluating advanced:  33%|███▎      | 33/100 [28:04<56:16, 50.40s/it]

Q34/100 [paraphrased]  JPM  2024.0
  corr=0.00  faith=1.00  f1=0.10  tokens=3043in/121out  est=$0.00035

Evaluating advanced:  34%|███▍      | 34/100 [28:52<54:48, 49.83s/it]

Q35/100 [paraphrased]  BAC  2025.0
  corr=0.00  faith=1.00  f1=0.29  tokens=7579in/176out  est=$0.00083

Evaluating advanced:  35%|███▌      | 35/100 [29:42<54:07, 49.96s/it]

Q36/100 [paraphrased]  BAC  2024.0
  corr=0.00  faith=1.00  f1=0.10  tokens=7027in/170out  est=$0.00077

Evaluating advanced:  36%|███▌      | 36/100 [30:34<53:41, 50.33s/it]

Q37/100 [paraphrased]  BRK-B  2025.0
  corr=0.00  faith=1.00  f1=0.10  tokens=574in/104out  est=$0.00010

Evaluating advanced:  37%|███▋      | 37/100 [31:21<51:46, 49.32s/it]

Q38/100 [paraphrased]  BRK-B  2023.0
  corr=0.00  faith=1.00  f1=0.06  tokens=636in/108out  est=$0.00011

Evaluating advanced:  38%|███▊      | 38/100 [32:09<50:32, 48.91s/it]

Q39/100 [paraphrased]  JNJ  2025.0
  corr=0.00  faith=1.00  f1=0.13  tokens=6563in/197out  est=$0.00074

Evaluating advanced:  39%|███▉      | 39/100 [33:00<50:37, 49.79s/it]

Q40/100 [paraphrased]  JNJ  2025.0
  corr=0.00  faith=1.00  f1=0.21  tokens=4927in/196out  est=$0.00057

Evaluating advanced:  40%|████      | 40/100 [33:56<51:38, 51.64s/it]

Q41/100 [paraphrased]  UNH  2024.0
  corr=0.00  faith=1.00  f1=0.23  tokens=9081in/170out  est=$0.00098

Evaluating advanced:  41%|████      | 41/100 [34:48<50:47, 51.66s/it]

Q42/100 [paraphrased]  UNH  2023.0
  corr=0.00  faith=1.00  f1=0.10  tokens=9641in/180out  est=$0.00104

Evaluating advanced:  42%|████▏     | 42/100 [35:40<49:57, 51.69s/it]

Q43/100 [paraphrased]  XOM  2023.0
  corr=0.00  faith=1.00  f1=0.00  tokens=4049in/127out  est=$0.00046

Evaluating advanced:  43%|████▎     | 43/100 [36:28<48:04, 50.61s/it]

Q44/100 [paraphrased]  XOM  2025.0
  corr=0.10  faith=1.00  f1=0.07  tokens=9487in/170out  est=$0.00102

Evaluating advanced:  44%|████▍     | 44/100 [37:25<49:10, 52.68s/it]

Q45/100 [paraphrased]  CVX  2024.0
  corr=0.00  faith=0.50  f1=0.21  tokens=9266in/178out  est=$0.00100

Evaluating advanced:  45%|████▌     | 45/100 [38:28<51:06, 55.76s/it]

Q46/100 [paraphrased]  CVX  2025.0
  corr=1.00  faith=1.00  f1=0.42  tokens=5000in/189out  est=$0.00058

Evaluating advanced:  46%|████▌     | 46/100 [39:17<48:21, 53.74s/it]

Q47/100 [paraphrased]  WMT  2023.0
  corr=0.85  faith=1.00  f1=0.17  tokens=4549in/245out  est=$0.00055

Evaluating advanced:  47%|████▋     | 47/100 [40:15<48:27, 54.86s/it]

Q48/100 [paraphrased]  WMT  2025.0
  corr=1.00  faith=1.00  f1=0.33  tokens=3954in/150out  est=$0.00046

Evaluating advanced:  48%|████▊     | 48/100 [41:05<46:12, 53.32s/it]

Q49/100 [paraphrased]  COST  2025.0
  corr=1.00  faith=1.00  f1=0.36  tokens=9023in/176out  est=$0.00097

Evaluating advanced:  49%|████▉     | 49/100 [41:56<44:52, 52.79s/it]

Q50/100 [paraphrased]  COST  2023.0
  corr=0.00  faith=1.00  f1=0.12  tokens=9255in/135out  est=$0.00098

Evaluating advanced:  50%|█████     | 50/100 [42:47<43:36, 52.33s/it]

Q51/100 [reasoning]  AAPL  2023.0
  corr=0.00  faith=0.80  f1=0.18  tokens=8534in/166out  est=$0.00092

Evaluating advanced:  51%|█████     | 51/100 [43:51<45:34, 55.80s/it]

Q52/100 [reasoning]  AAPL  2025.0
  corr=0.25  faith=0.50  f1=0.41  tokens=9640in/216out  est=$0.00105

Evaluating advanced:  52%|█████▏    | 52/100 [44:54<46:16, 57.83s/it]

Q53/100 [reasoning]  MSFT  2023.0
  corr=0.00  faith=1.00  f1=0.46  tokens=8323in/178out  est=$0.00090

Evaluating advanced:  53%|█████▎    | 53/100 [45:44<43:24, 55.41s/it]

Q54/100 [reasoning]  MSFT  2024.0
  corr=0.00  faith=1.00  f1=0.12  tokens=9282in/204out  est=$0.00101

Evaluating advanced:  54%|█████▍    | 54/100 [46:35<41:40, 54.36s/it]

Q55/100 [reasoning]  NVDA  2024.0
  corr=0.00  faith=1.00  f1=0.25  tokens=6701in/129out  est=$0.00072

Evaluating advanced:  55%|█████▌    | 55/100 [47:26<39:55, 53.23s/it]

Q56/100 [reasoning]  NVDA  2025.0
  corr=0.20  faith=0.00  f1=0.31  tokens=7903in/153out  est=$0.00085

Evaluating advanced:  56%|█████▌    | 56/100 [48:27<40:45, 55.57s/it]

Q57/100 [reasoning]  NVDA  2025.0
  corr=0.00  faith=1.00  f1=0.10  tokens=7709in/225out  est=$0.00086

Evaluating advanced:  57%|█████▋    | 57/100 [49:28<40:54, 57.09s/it]

Q58/100 [reasoning]  JPM  2025.0
  corr=0.00  faith=1.00  f1=0.19  tokens=9562in/145out  est=$0.00101

Evaluating advanced:  58%|█████▊    | 58/100 [50:19<38:48, 55.45s/it]

Q59/100 [reasoning]  JPM  2024.0
  corr=0.00  faith=1.00  f1=0.00  tokens=6045in/153out  est=$0.00067

Evaluating advanced:  59%|█████▉    | 59/100 [51:12<37:13, 54.49s/it]

Q60/100 [reasoning]  BAC  2025.0
  corr=0.00  faith=1.00  f1=0.18  tokens=7625in/174out  est=$0.00083

Evaluating advanced:  60%|██████    | 60/100 [52:03<35:42, 53.56s/it]

Q61/100 [reasoning]  BAC  2025.0
  corr=0.00  faith=1.00  f1=0.12  tokens=9399in/138out  est=$0.00100

Evaluating advanced:  61%|██████    | 61/100 [52:54<34:23, 52.92s/it]

Q62/100 [reasoning]  BRK-B  2024.0
  corr=0.00  faith=1.00  f1=0.07  tokens=728in/138out  est=$0.00013

Evaluating advanced:  62%|██████▏   | 62/100 [53:41<32:17, 51.00s/it]

Q63/100 [reasoning]  BRK-B  2025.0
  corr=0.00  faith=1.00  f1=0.06  tokens=683in/110out  est=$0.00011

Evaluating advanced:  63%|██████▎   | 63/100 [54:28<30:47, 49.94s/it]

Q64/100 [reasoning]  JNJ  2025.0
  corr=0.00  faith=1.00  f1=0.19  tokens=8274in/128out  est=$0.00088

Evaluating advanced:  64%|██████▍   | 64/100 [55:18<29:59, 49.97s/it]

Q65/100 [reasoning]  JNJ  2023.0
  corr=0.00  faith=1.00  f1=0.28  tokens=7677in/154out  est=$0.00083

Evaluating advanced:  65%|██████▌   | 65/100 [56:08<29:06, 49.89s/it]

Q66/100 [reasoning]  UNH  2025.0
  corr=0.00  faith=1.00  f1=0.12  tokens=9338in/162out  est=$0.00100

Evaluating advanced:  66%|██████▌   | 66/100 [57:00<28:39, 50.58s/it]

Q67/100 [reasoning]  UNH  2025.0
  corr=0.00  faith=1.00  f1=0.18  tokens=5304in/143out  est=$0.00059

Evaluating advanced:  67%|██████▋   | 67/100 [57:52<27:56, 50.80s/it]

Q68/100 [reasoning]  XOM  2025.0
  corr=0.00  faith=1.00  f1=0.12  tokens=4310in/166out  est=$0.00050

Evaluating advanced:  68%|██████▊   | 68/100 [58:43<27:05, 50.81s/it]

Q69/100 [reasoning]  XOM  2024.0
  corr=0.00  faith=1.00  f1=0.22  tokens=4227in/186out  est=$0.00050

Evaluating advanced:  69%|██████▉   | 69/100 [59:32<26:07, 50.56s/it]

Q70/100 [reasoning]  CVX  2025.0
  corr=0.00  faith=1.00  f1=0.15  tokens=11680in/178out  est=$0.00124

Evaluating advanced:  70%|███████   | 70/100 [1:00:28<26:05, 52.19s/it]

Q71/100 [reasoning]  CVX  2024.0
  corr=0.00  faith=1.00  f1=0.00  tokens=4069in/153out  est=$0.00047

Evaluating advanced:  71%|███████   | 71/100 [1:01:19<25:03, 51.83s/it]

Q72/100 [reasoning]  WMT  2024.0
  corr=0.00  faith=0.10  f1=0.10  tokens=4422in/176out  est=$0.00051

Evaluating advanced:  72%|███████▏  | 72/100 [1:02:21<25:34, 54.81s/it]

Q73/100 [reasoning]  WMT  2025.0
  corr=0.00  faith=1.00  f1=0.15  tokens=11426in/175out  est=$0.00121

Evaluating advanced:  73%|███████▎  | 73/100 [1:03:16<24:39, 54.79s/it]

Q74/100 [reasoning]  COST  2025.0
  corr=0.00  faith=1.00  f1=0.08  tokens=4170in/129out  est=$0.00047

Evaluating advanced:  74%|███████▍  | 74/100 [1:04:07<23:16, 53.70s/it]

Q75/100 [reasoning]  COST  2024.0
  corr=0.00  faith=1.00  f1=0.00  tokens=9027in/138out  est=$0.00096

Evaluating advanced:  75%|███████▌  | 75/100 [1:04:58<22:03, 52.95s/it]

Q76/100 [adversarial]  AAPL  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=7553in/125out  est=$0.00081

Evaluating advanced:  76%|███████▌  | 76/100 [1:05:46<20:35, 51.50s/it]

Q77/100 [adversarial]  AAPL  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3466in/145out  est=$0.00040

Evaluating advanced:  77%|███████▋  | 77/100 [1:06:34<19:18, 50.36s/it]

Q78/100 [adversarial]  MSFT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3059in/116out  est=$0.00035

Evaluating advanced:  78%|███████▊  | 78/100 [1:07:22<18:13, 49.71s/it]

Q79/100 [adversarial]  MSFT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=6314in/104out  est=$0.00067

Evaluating advanced:  79%|███████▉  | 79/100 [1:08:10<17:12, 49.17s/it]

Q80/100 [adversarial]  NVDA  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3305in/131out  est=$0.00038

Evaluating advanced:  80%|████████  | 80/100 [1:09:00<16:24, 49.23s/it]

Q81/100 [adversarial]  NVDA  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3035in/84out  est=$0.00034

Evaluating advanced:  81%|████████  | 81/100 [1:09:49<15:33, 49.15s/it]

Q82/100 [adversarial]  NVDA  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3105in/98out  est=$0.00035

Evaluating advanced:  82%|████████▏ | 82/100 [1:10:39<14:49, 49.39s/it]

Q83/100 [adversarial]  JPM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=2994in/67out  est=$0.00033

Evaluating advanced:  83%|████████▎ | 83/100 [1:11:25<13:47, 48.65s/it]

Q84/100 [adversarial]  JPM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=5705in/65out  est=$0.00060

Evaluating advanced:  84%|████████▍ | 84/100 [1:12:13<12:53, 48.34s/it]

Q85/100 [adversarial]  BAC  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=4898in/83out  est=$0.00052

Evaluating advanced:  85%|████████▌ | 85/100 [1:13:00<11:59, 47.93s/it]

Q86/100 [adversarial]  BAC  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3782in/116out  est=$0.00042

Evaluating advanced:  86%|████████▌ | 86/100 [1:13:47<11:07, 47.69s/it]

Q87/100 [adversarial]  BRK-B  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=405in/56out  est=$0.00006

Evaluating advanced:  87%|████████▋ | 87/100 [1:14:32<10:10, 46.94s/it]

Q88/100 [adversarial]  BRK-B  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=405in/55out  est=$0.00006

Evaluating advanced:  88%|████████▊ | 88/100 [1:15:19<09:20, 46.70s/it]

Q89/100 [adversarial]  JNJ  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3309in/160out  est=$0.00039

Evaluating advanced:  89%|████████▉ | 89/100 [1:16:06<08:37, 47.08s/it]

Q90/100 [adversarial]  JNJ  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3242in/135out  est=$0.00038

Evaluating advanced:  90%|█████████ | 90/100 [1:16:54<07:52, 47.25s/it]

Q91/100 [adversarial]  UNH  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3241in/113out  est=$0.00037

Evaluating advanced:  91%|█████████ | 91/100 [1:17:42<07:06, 47.43s/it]

Q92/100 [adversarial]  UNH  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3197in/66out  est=$0.00035

Evaluating advanced:  92%|█████████▏| 92/100 [1:18:28<06:16, 47.01s/it]

Q93/100 [adversarial]  XOM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=6280in/85out  est=$0.00066

Evaluating advanced:  93%|█████████▎| 93/100 [1:19:16<05:30, 47.16s/it]

Q94/100 [adversarial]  XOM  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=2862in/151out  est=$0.00035

Evaluating advanced:  94%|█████████▍| 94/100 [1:20:04<04:44, 47.47s/it]

Q95/100 [adversarial]  CVX  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3531in/116out  est=$0.00040

Evaluating advanced:  95%|█████████▌| 95/100 [1:20:53<03:59, 47.91s/it]

Q96/100 [adversarial]  CVX  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3737in/77out  est=$0.00040

Evaluating advanced:  96%|█████████▌| 96/100 [1:21:41<03:12, 48.02s/it]

Q97/100 [adversarial]  WMT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3306in/152out  est=$0.00039

Evaluating advanced:  97%|█████████▋| 97/100 [1:22:30<02:25, 48.38s/it]

Q98/100 [adversarial]  WMT  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=3073in/103out  est=$0.00035

Evaluating advanced:  98%|█████████▊| 98/100 [1:23:18<01:36, 48.24s/it]

Q99/100 [adversarial]  COST  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=4175in/68out  est=$0.00044

Evaluating advanced:  99%|█████████▉| 99/100 [1:24:05<00:47, 47.99s/it]

Q100/100 [adversarial]  COST  nan
  corr=1.00  faith=1.00  f1=0.00  tokens=5872in/118out  est=$0.00063

Evaluating advanced: 100%|██████████| 100/100 [1:24:53<00:00, 50.93s/it]

Saved 100 rows -> /content/results/drive/advanced_results.csv

In [22]:
results_df

,question_id,question,question_type,company,ticker,form_type,filing_year,reference_answer,expected_decision,final_answer,...,model_judge_faithfulness,tokens_generate_input,tokens_generate_output,tokens_judge_corr_input,tokens_judge_corr_output,tokens_judge_faith_input,tokens_judge_faith_output,tokens_total_input,tokens_total_output,est_cost_usd
0,1,What were Apple’s total net sales in fiscal ye...,extractive,Apple,AAPL,10-K,2023.0,Apple's total net sales in fiscal year 2023 we...,answer,Apple's total net sales in fiscal year 2023 ca...,...,gemini-2.5-flash,5310,28,169,52,5145,102,10624,182,0.001135
1,2,"According to Apple’s fiscal Q3 2025 filing, wh...",extractive,Apple,AAPL,10-Q,2025.0,"According to Apple's Q3 2025 filing, the U.S. ...",answer,The provided filings state that new tariffs we...,...,gemini-2.5-flash,4669,64,229,46,4523,85,9421,195,0.001020
2,3,What are the contingencies declared by Microso...,extractive,Microsoft,MSFT,10-Q,2023.0,Microsoft declared a contingency related to IR...,answer,"As of September 30, 2023, Microsoft declared t...",...,gemini-2.5-flash,3355,59,192,81,3184,72,6731,212,0.000758
3,4,Which Microsoft business segment generated the...,extractive,Microsoft,MSFT,10-K,2023.0,Intelligent Cloud generated the highest revenu...,answer,Insufficient information in the provided filings.,...,gemini-2.5-flash,4522,13,156,49,4343,72,9021,134,0.000956
4,5,What risk does Nvidia mention that could affec...,extractive,NVIDIA,NVDA,10-K,2025.0,Customers may delay adopting new architectures...,answer,"A shortage of data centers, energy, and capita...",...,gemini-2.5-flash,2837,30,165,78,2666,68,5668,176,0.000637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,What internal AI system does Chevron use for d...,adversarial,Chevron,CVX,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,1949,28,0,0,1788,49,3737,77,0.000405
96,97,What percentage of Walmart employees work remo...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,1708,79,0,0,1598,73,3306,152,0.000391
97,98,What internal robot efficiency metrics does Wa...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,1613,35,0,0,1460,68,3073,103,0.000349
98,99,What percentage of Costco warehouses are fully...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,2173,16,0,0,2002,52,4175,68,0.000445
99,100,What internal AI system does Costco use for in...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,3003,57,0,0,2869,61,5872,118,0.000634

## 14. Results & Comparison with Baseline

In [23]:
for idx, row in results_df.iterrows():
    print("Row:", idx)
    print("Question:", row['question'])
    print("Reference Answer:", row['reference_answer'])
    print("Final Answer:", row['final_answer'])
    # print("Generated Answer:", row['generated_answer'])
    print("Expected Decision:", row['expected_decision'])
    print("-" * 50)

Row: 0
Question: What were Apple’s total net sales in fiscal year 2023?
Reference Answer: Apple's total net sales in fiscal year 2023 were $383,285 million.
Final Answer: Apple's total net sales in fiscal year 2023 cannot be determined from the provided filings
Expected Decision: answer
--------------------------------------------------
Row: 1
Question: According to Apple’s fiscal Q3 2025 filing, which countries were subject to new U.S. import tariffs?
Reference Answer: According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Final Answer: The provided filings state that new tariffs were announced on imports to the U.S. beginning in the second quarter of 2025 [3]. However, the filings do not specify which countries were subject to these new U.S. import tariffs.
Expected Decision: answer
--------------------------------------------------
Row: 2
Question: What are the contingencies declared by Microsoft for the quarter ended in September 2023?
Reference Answer: Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Final Answer: As of September 30, 2023, Microsoft declared that its allowances
Expected Decision: answer
--------------------------------------------------
Row: 3
Question: Which Microsoft business segment generated the highest revenue in the 2023 fiscal year?
Reference Answer: Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 4
Question: What risk does Nvidia mention that could affect the timing of Data Center revenue in fiscal year 2025?
Reference Answer: Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Final Answer: A shortage of data centers, energy, and capital to support the buildout of NVIDIA AI infrastructure by customers
Expected Decision: answer
--------------------------------------------------
Row: 5
Question: What was Nvidia's gross margin percentage in fiscal year 2024?
Reference Answer: Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 6
Question: How many employees did Nvidia report at the end of fiscal year 2025?
Reference Answer: As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Final Answer: Insufficient information in the provided filings. The context states that as of the end of fiscal year
Expected Decision: answer
--------------------------------------------------
Row: 7
Question: What was JPMorgan's CET1 capital ratio at the end of fiscal year 2023?
Reference Answer: JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 8
Question: Which federal regulator supervises JPMorgan Chase as a bank holding company in 2024?
Reference Answer: JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 9
Question: What were Bank of America's Total liabilities as of September 2025?
Reference Answer: Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Final Answer: Insufficient information in the provided filings. The provided context does not contain Bank of America's Total liabilities as of September 2025. The latest available period-end data is June 30, 2025 [4]. Additionally, "Total liabilities" is not explicitly listed in the provided balance sheet information, only "Total assets" and "Total deposits" [1, 2,
Expected Decision: answer
--------------------------------------------------
Row: 10
Question: What interest rate risk does Bank of America describe in its latest annual filing?
Reference Answer: Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and capital.
Final Answer: Insufficient information in the provided filings. The retrieved context from Bank of America's latest annual filing (2025 10-K
Expected Decision: answer
--------------------------------------------------
Row: 11
Question: What was Berkshire Hathaway’s net earnings attributable to shareholders reported in its latest annual report?
Reference Answer: Berkshire Hathaway's net earnings attributable to Berkshire shareholders in fiscal year 2025 were $66,968 million.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 12
Question: How much did Berkshire Hathaway pay to acquire an additional interest in Pilot Travel Centers in January 2023?
Reference Answer: Berkshire Hathaway acquired an additional 41.4% controlling interest in Pilot Travel Centers for approximately $8.2 billion on January 31, 2023, which was consolidated into financial statements from February 1, 2023.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 13
Question: What were Johnson & Johnson’s total sales for the first nine months of fiscal 2025?
Reference Answer: Johnson & Johnson's total sales for the nine months ended September 28, 2025 were $69,629 million.
Final Answer: Insufficient information in the provided filings. The retrieved context indicates that "Consolidated statements of earnings for the
Expected Decision: answer
--------------------------------------------------
Row: 14
Question: What was Johnson & Johnson’s net earnings in the most recent annual report?
Reference Answer: Johnson & Johnson's net earnings from continuing operations in fiscal year 2025 were $26,804 million.
Final Answer: Insufficient information in the provided filings. The retrieved context for the most recent annual report (J
Expected Decision: answer
--------------------------------------------------
Row: 15
Question: What was UnitedHealth Group's medical care ratio for the three months ended June 2024?
Reference Answer: UnitedHealth Group's medical care ratio (MCR) for the three months ended June 30, 2024 was 85.1%, up from 83.2% in Q2 2023, an increase of 1.9 percentage points.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 16
Question: What was UnitedHealth Group’s net earnings reported in 2023?
Reference Answer: UnitedHealth Group's net earnings reported in 2023 is $23,144 million.
Final Answer: Insufficient information in the provided filings. The available filings are quarterly reports for 2023,
Expected Decision: answer
--------------------------------------------------
Row: 17
Question: How many oil-equivalent barrels per day did ExxonMobil produce in fiscal year 2023?
Reference Answer: ExxonMobil produced 3,738 thousand oil-equivalent barrels per day
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 18
Question: What was the total value of acquisitions completed by ExxonMobil during the third quarter of 2025?
Reference Answer: ExxonMobil completed $2.4 billion in acquisitions consisting primarily of proved and unproved acreage in the Permian basin.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 19
Question: What primarily caused Chevron’s international upstream earnings to decrease in the three months ended March 31, 2024?
Reference Answer: Chevron's International Upstream earnings decreased was primarily due to lower natural gas realizations
Final Answer: International upstream earnings decreased by $702 million, from $4,032 million
Expected Decision: answer
--------------------------------------------------
Row: 20
Question: What are Chevron’s two primary business segments in 2025?
Reference Answer: Chevron's two primary business segments in 2025 are Upstream and Downstream.
Final Answer: Chevron's two primary business segments in 2025 are its oil and gas
Expected Decision: answer
--------------------------------------------------
Row: 21
Question: What liability did Walmart accrue in fiscal year 2023 for opioid-related settlement agreements?
Reference Answer: During fiscal 2023, Walmart accrued a liability of approximately $3.3 billion for the opioid-related Settlement Framework.
Final Answer: During fiscal year 2023, Walmart accrued a liability of approximately $3.3 billion for the Settlement Framework and other previously agreed upon state and tribal settlements related to opioid-related litigation [1, 3, 5].
Expected Decision: answer
--------------------------------------------------
Row: 22
Question: How many associates did Walmart employ globally in fiscal year 2025?
Reference Answer: Walmart employed approximately 2.1 million associates.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 23
Question: What was Costco’s total revenue reported in fiscal year 2025?
Reference Answer: Costco's total revenue for fiscal year 2025 was $275,235 million.
Final Answer: Insufficient information in the provided filings. The context provides total revenue for the 12 weeks ended November 23, 2025, which was $67,307 million [1], but not for the entire fiscal year 2025.
Expected Decision: answer
--------------------------------------------------
Row: 24
Question: What membership fee revenue did Costco report for the quarter ended November 26, 2023?
Reference Answer: Costco reported membership fee revenue of $1,082 million for the 12 weeks ended November 26, 2023.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 25
Question: What amount of revenue did Apple generate during fiscal year 2023?
Reference Answer: Apple's total net sales in fiscal year 2023 were $383,285 million.
Final Answer: Insufficient information in the provided filings. The retrieved context provides net sales for the nine months ended July
Expected Decision: answer
--------------------------------------------------
Row: 26
Question: Which regions were impacted by the newly announced U.S. import duties referenced in Apple’s Q3 2025 report?
Reference Answer: According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Final Answer: Insufficient information in the provided filings. The retrieved context, including Apple's Q3 2025 report [3, 5], does not contain any discussion of newly announced U.
Expected Decision: answer
--------------------------------------------------
Row: 27
Question: What potential financial obligations did Microsoft flag in its three-month period ending September 2023?
Reference Answer: Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Final Answer: For the three-month period ending September 2023, Microsoft flagged the potential
Expected Decision: answer
--------------------------------------------------
Row: 28
Question: Which of Microsoft’s operating divisions contributed the largest share of revenue in the most recent fiscal year?
Reference Answer: Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Final Answer: Insufficient information in the provided filings. The context provides revenue increases and growth percentages for various products and services, such as Microsoft 365 Commercial products and cloud services [1, 2, 6, 7] and Productivity and Business Processes [5], but it does not provide the total revenue for any specific operating division or their respective shares of
Expected Decision: answer
--------------------------------------------------
Row: 29
Question: What factor does Nvidia identify that could delay the recognition of Data Center revenue in fiscal year 2025?
Reference Answer: Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 30
Question: What proportion of Nvidia’s revenue remained as gross profit during fiscal year 2024?
Reference Answer: Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Final Answer: Insufficient information in the provided filings. The retrieved context does not contain the necessary figures for Nvidia
Expected Decision: answer
--------------------------------------------------
Row: 31
Question: What was the size of Nvidia's workforce at the close of its 2025 annual period?
Reference Answer: As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 32
Question: What Common Equity Tier 1 capital ratio did JPMorgan report at the end of fiscal year 2023?
Reference Answer: JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Final Answer: JPMorgan reported a Common Equity Tier 1 (CET1) capital ratio of 15.0% at the end of fiscal year 2023 [6].
Expected Decision: answer
--------------------------------------------------
Row: 33
Question: What government body had oversight responsibility over JPMorgan Chase's holding company structure in 2024?
Reference Answer: JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 34
Question: What was the aggregate sum of all debts and obligations owed by Bank of America as of September 2025?
Reference Answer: Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Final Answer: Insufficient information in the provided filings. The retrieved context includes a Condensed Balance Sheet for Bank of America as of December 31, 2025, but not for September 2025 [3].
Expected Decision: answer
--------------------------------------------------
Row: 35
Question: How does Bank of America characterise the threat posed by fluctuating borrowing costs in its 2024 annual period?
Reference Answer: Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and capital.
Final Answer: Insufficient information in the provided filings. The retrieved context mentions "Item 1A - Risk Factors
Expected Decision: answer
--------------------------------------------------
Row: 36
Question: What was the total profit that Berkshire Hathaway recorded for the most recent yearly report?
Reference Answer: Berkshire Hathaway's net earnings attributable to Berkshire shareholders in fiscal year 2025 were $66,968 million.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 37
Question: How much did Berkshire Hathaway spend in January 2023 to buy out the remaining ownership stake in Pilot Travel Centers?
Reference Answer: Berkshire Hathaway acquired an additional 41.4% controlling interest in Pilot Travel Centers for approximately $8.2 billion on January 31, 2023, which was consolidated into financial statements from February 1, 2023.
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 38
Question: How much revenue did Johnson & Johnson generate during the first three quarters of fiscal year 2025?
Reference Answer: Johnson & Johnson's total sales for the nine months ended September 28, 2025 were $69,629 million.
Final Answer: Insufficient information in the provided filings. The retrieved context indicates that "Consolidated statements of earnings for
Expected Decision: answer
--------------------------------------------------
Row: 39
Question: What bottom-line profit did Johnson & Johnson record in its most recent annual filing?
Reference Answer: Johnson & Johnson's net earnings from continuing operations in fiscal year 2025 were $26,804 million.
Final Answer: Insufficient information in the provided filings. The retrieved context for Johnson & Johnson's most recent annual filing (JNJ 10-K for the year 2025, filed on 2026-02-11 [1]) does not contain the bottom-line profit figure.
Expected Decision: answer
--------------------------------------------------
Row: 40
Question: What proportion of premium revenue did UnitedHealth Group spend on medical care in the quarter ending June 2024?
Reference Answer: UnitedHealth Group's medical care ratio (MCR) for the three months ended June 30, 2024 was 85.1%, up from 83.2% in Q2 2023, an increase of 1.9 percentage points.
Final Answer: Insufficient information in the provided filings. The retrieved context for the quarter ending June 30, 2
Expected Decision: answer
--------------------------------------------------
Row: 41
Question: What was the total profit that UnitedHealth Group recorded at the close of its 2023 annual period?
Reference Answer: UnitedHealth Group's net earnings reported in 2023 is $23,144 million.
Final Answer: Insufficient information in the provided filings. The retrieved context contains 10-Q filings for the first three quarters of 2023, but not the full annual report (10-K) for the 2023
Expected Decision: answer
--------------------------------------------------
Row: 42
Question: What was ExxonMobil’s average daily production of oil-equivalent barrels in fiscal year 2023?
Reference Answer: ExxonMobil produced 3,738 thousand oil-equivalent barrels per day
Final Answer: Insufficient information in the provided filings.
Expected Decision: answer
--------------------------------------------------
Row: 43
Question: Had ExxonMobil finalised any purchases of other businesses by September 2025?
Reference Answer: ExxonMobil completed $2.4 billion in acquisitions consisting primarily of proved and unproved acreage in the Permian basin.
Final Answer: ExxonMobil acquired Pioneer Natural Resources Company on May 3, 2024 [1,
Expected Decision: answer
--------------------------------------------------
Row: 44
Question: What was the primary driver behind the decline in Chevron’s international upstream earnings in the March 2024 quarter?

In [24]:
results_df

,question_id,question,question_type,company,ticker,form_type,filing_year,reference_answer,expected_decision,final_answer,...,model_judge_faithfulness,tokens_generate_input,tokens_generate_output,tokens_judge_corr_input,tokens_judge_corr_output,tokens_judge_faith_input,tokens_judge_faith_output,tokens_total_input,tokens_total_output,est_cost_usd
0,1,What were Apple’s total net sales in fiscal ye...,extractive,Apple,AAPL,10-K,2023.0,Apple's total net sales in fiscal year 2023 we...,answer,Apple's total net sales in fiscal year 2023 ca...,...,gemini-2.5-flash,5310,28,169,52,5145,102,10624,182,0.001135
1,2,"According to Apple’s fiscal Q3 2025 filing, wh...",extractive,Apple,AAPL,10-Q,2025.0,"According to Apple's Q3 2025 filing, the U.S. ...",answer,The provided filings state that new tariffs we...,...,gemini-2.5-flash,4669,64,229,46,4523,85,9421,195,0.001020
2,3,What are the contingencies declared by Microso...,extractive,Microsoft,MSFT,10-Q,2023.0,Microsoft declared a contingency related to IR...,answer,"As of September 30, 2023, Microsoft declared t...",...,gemini-2.5-flash,3355,59,192,81,3184,72,6731,212,0.000758
3,4,Which Microsoft business segment generated the...,extractive,Microsoft,MSFT,10-K,2023.0,Intelligent Cloud generated the highest revenu...,answer,Insufficient information in the provided filings.,...,gemini-2.5-flash,4522,13,156,49,4343,72,9021,134,0.000956
4,5,What risk does Nvidia mention that could affec...,extractive,NVIDIA,NVDA,10-K,2025.0,Customers may delay adopting new architectures...,answer,"A shortage of data centers, energy, and capita...",...,gemini-2.5-flash,2837,30,165,78,2666,68,5668,176,0.000637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,What internal AI system does Chevron use for d...,adversarial,Chevron,CVX,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,1949,28,0,0,1788,49,3737,77,0.000405
96,97,What percentage of Walmart employees work remo...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,1708,79,0,0,1598,73,3306,152,0.000391
97,98,What internal robot efficiency metrics does Wa...,adversarial,Walmart,WMT,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,1613,35,0,0,1460,68,3073,103,0.000349
98,99,What percentage of Costco warehouses are fully...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filings.,...,gemini-2.5-flash,2173,16,0,0,2002,52,4175,68,0.000445
99,100,What internal AI system does Costco use for in...,adversarial,Costco,COST,NaN,NaN,nan,refuse,Insufficient information in the provided filin...,...,gemini-2.5-flash,3003,57,0,0,2869,61,5872,118,0.000634

In [25]:
print("=" * 60)
print(" ADVANCED RAG — EVALUATION RESULTS")
print("=" * 60)

scored_c = results_df[results_df['llm_correctness_score'].notna()]
scored_f = results_df[results_df['llm_faithfulness_score'].notna()]
print(f'\nTotal questions    : {len(results_df)}')
print(f'Correctness judged : {len(scored_c)}')
print(f'Faithfulness judged: {len(scored_f)}')

print('\nOverall metrics:')
for col, label in [
    ('llm_correctness_score',  'LLM Correctness  '),
    ('llm_claims_covered',     'Claims Covered   '),
    ('llm_faithfulness_score', 'LLM Faithfulness '),
    ('token_f1',               'Token F1         '),
    ('numerical_accuracy',     'Numerical Accuracy'),
    ('decision_accuracy',      'Decision Accuracy'),
]:
    vals = results_df[col].dropna()
    if len(vals):
        print(f'  {label}: {vals.mean():.4f}  (n={len(vals)})')

print('\nBy question_type:')
type_cols = ['llm_correctness_score', 'llm_faithfulness_score', 'token_f1', 'decision_accuracy']
avail = [c for c in type_cols if c in results_df.columns]
if avail and 'question_type' in results_df.columns:
    print(results_df.groupby('question_type')[avail].mean().round(3).to_string())

if 'latency_sec' in results_df.columns:
    lat = results_df['latency_sec'].dropna()
    if len(lat):
        print(f'\nLatency: mean={lat.mean():.1f}s  median={lat.median():.1f}s  max={lat.max():.1f}s')

print('\nToken & cost summary:')
for col in ['tokens_generate_input', 'tokens_generate_output',
            'tokens_judge_corr_input', 'tokens_judge_corr_output',
            'tokens_judge_faith_input', 'tokens_judge_faith_output',
            'tokens_total_input', 'tokens_total_output']:
    if col in results_df.columns:
        print(f'  {col:35s}: {int(results_df[col].sum()):,}')
if 'est_cost_usd' in results_df.columns:
    print(f'  {"Total estimated cost (USD)":35s}: ${results_df["est_cost_usd"].sum():.4f}')

# Compare with baseline if available
baseline_path = Path(CONFIG["results_dir"]) / "baseline_results.csv"
if baseline_path.exists():
    baseline_df = pd.read_csv(baseline_path)
    print("\n" + "=" * 60)
    print(" COMPARISON: BASELINE vs ADVANCED RAG")
    print("=" * 60)
    cols = ['llm_correctness_score', 'llm_faithfulness_score', 'token_f1', 'decision_accuracy']
    avail = [c for c in cols if c in results_df.columns and c in baseline_df.columns]
    comparison = pd.DataFrame({
        "Baseline": baseline_df[avail].mean(),
        "Advanced": results_df[avail].mean(),
    }).round(3)
    comparison["Delta"] = (comparison["Advanced"] - comparison["Baseline"]).round(3)
    print(comparison.to_string())
else:
    print("\n(Run baseline_rag.ipynb first to see comparison)")

============================================================
 ADVANCED RAG — EVALUATION RESULTS
============================================================

Total questions    : 100
Correctness judged : 100
Faithfulness judged: 100

Overall metrics:
  LLM Correctness  : 0.3255  (n=100)
  Claims Covered   : 0.3379  (n=100)
  LLM Faithfulness : 0.9470  (n=100)
  Token F1         : 0.1362  (n=100)
  Numerical Accuracy: 0.2276  (n=67)
  Decision Accuracy: 0.4300  (n=100)

By question_type:
               llm_correctness_score  llm_faithfulness_score  token_f1  decision_accuracy
question_type
adversarial                    1.000                   1.000     0.000               1.00
extractive                     0.084                   0.952     0.218               0.28
paraphrased                    0.200                   0.940     0.165               0.28
reasoning                      0.018                   0.896     0.161               0.16

Latency: mean=5.0s  median=5.2s  max=6.1s

Token & cost summary:
  tokens_generate_input              : 293,627
  tokens_generate_output             : 3,650
  tokens_judge_corr_input            : 14,438
  tokens_judge_corr_output           : 4,004
  tokens_judge_faith_input           : 277,122
  tokens_judge_faith_output          : 6,847
  tokens_total_input                 : 585,187
  tokens_total_output                : 14,501
  Total estimated cost (USD)         : $0.0643

(Run baseline_rag.ipynb first to see comparison)

In [26]:
import pandas as pd
from pathlib import Path

# Assuming CONFIG is defined in a previous cell
# Define out_path consistently with where it's saved in fa72160a
out_path = Path(CONFIG["results_dir"]) / "drive/advanced_results.csv"

# Load only what exists
advanced_df = pd.read_csv(out_path)
print(f"Advanced results: {len(advanced_df)} rows")
print(f"Columns: {list(advanced_df.columns)}")

Advanced results: 100 rows
Columns: ['question_id', 'question', 'question_type', 'company', 'ticker', 'form_type', 'filing_year', 'reference_answer', 'expected_decision', 'final_answer', 'pipeline', 'n_chunks', 'rewritten_query', 'latency_sec', 'token_f1', 'numerical_accuracy', 'decision_accuracy', 'predicted_decision', 'llm_correctness_score', 'llm_claims_covered', 'llm_correctness_reason', 'llm_faithfulness_score', 'llm_faithfulness_reason', 'model_generator', 'model_judge_correctness', 'model_judge_faithfulness', 'tokens_generate_input', 'tokens_generate_output', 'tokens_judge_corr_input', 'tokens_judge_corr_output', 'tokens_judge_faith_input', 'tokens_judge_faith_output', 'tokens_total_input', 'tokens_total_output', 'est_cost_usd']

In [27]:
# Step 1 — Did answers come out?
print("=== ANSWER CHECK ===")
empty = advanced_df["final_answer"].isna() | (advanced_df["final_answer"].str.strip() == "")
refusals = advanced_df["final_answer"].str.contains(
    "insufficient|not contain|cannot find|not available|unable to",
    case=False, na=False
)
print(f"Total          : {len(advanced_df)}")
print(f"Empty answers  : {empty.sum()}")
print(f"Refusals       : {refusals.sum()}")
print(f"Actual answers : {(~empty & ~refusals).sum()}")

=== ANSWER CHECK ===
Total          : 100
Empty answers  : 0
Refusals       : 82
Actual answers : 18

In [28]:
# Step 2 — Eyeball every single question
pd.set_option("display.max_colwidth", 200)
for _, row in advanced_df.iterrows():
    print(f"\nQ{_+1} [{row.get('question_type','?')}] {row.get('ticker','?')} {row.get('filing_year','?')}")
    print(f"Question : {row['question']}")
    print(f"Expected : {str(row['reference_answer'])[:300]}")
    print(f"Got      : {str(row['final_answer'])[:300]}")
    print(f"Scores   : corr={row.get('llm_correctness_score',0):.2f}  "
          f"faith={row.get('llm_faithfulness_score',0):.2f}  "
          f"num_acc={row.get('numerical_accuracy','N/A')}")
    print("-"*80)

Q1 [extractive] AAPL 2023.0
Question : What were Apple’s total net sales in fiscal year 2023?
Expected : Apple's total net sales in fiscal year 2023 were $383,285 million.
Got      : Apple's total net sales in fiscal year 2023 cannot be determined from the provided filings
Scores   : corr=0.00  faith=1.00  num_acc=0.5
--------------------------------------------------------------------------------

Q2 [extractive] AAPL 2025.0
Question : According to Apple’s fiscal Q3 2025 filing, which countries were subject to new U.S. import tariffs?
Expected : According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Got      : The provided filings state that new tariffs were announced on imports to the U.S. beginning in the second quarter of 2025 [3]. However, the filings do not specify which countries were subject to these new U.S. import tariffs.
Scores   : corr=0.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q3 [extractive] MSFT 2023.0
Question : What are the contingencies declared by Microsoft for the quarter ended in September 2023?
Expected : Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Got      : As of September 30, 2023, Microsoft declared that its allowances
Scores   : corr=0.00  faith=0.30  num_acc=0.6666666666666666
--------------------------------------------------------------------------------

Q4 [extractive] MSFT 2023.0
Question : Which Microsoft business segment generated the highest revenue in the 2023 fiscal year?
Expected : Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q5 [extractive] NVDA 2025.0
Question : What risk does Nvidia mention that could affect the timing of Data Center revenue in fiscal year 2025?
Expected : Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Got      : A shortage of data centers, energy, and capital to support the buildout of NVIDIA AI infrastructure by customers
Scores   : corr=0.90  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q6 [extractive] NVDA 2024.0
Question : What was Nvidia's gross margin percentage in fiscal year 2024?
Expected : Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q7 [extractive] NVDA 2025.0
Question : How many employees did Nvidia report at the end of fiscal year 2025?
Expected : As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Got      : Insufficient information in the provided filings. The context states that as of the end of fiscal year
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q8 [extractive] JPM 2023.0
Question : What was JPMorgan's CET1 capital ratio at the end of fiscal year 2023?
Expected : JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q9 [extractive] JPM 2024.0
Question : Which federal regulator supervises JPMorgan Chase as a bank holding company in 2024?
Expected : JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q10 [extractive] BAC 2025.0
Question : What were Bank of America's Total liabilities as of September 2025?
Expected : Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Got      : Insufficient information in the provided filings. The provided context does not contain Bank of America's Total liabilities as of September 2025. The latest available period-end data is June 30, 2025 [4]. Additionally, "Total liabilities" is not explicitly listed in the provided balance sheet inform
Scores   : corr=0.00  faith=1.00  num_acc=0.6666666666666666
--------------------------------------------------------------------------------

Q11 [extractive] BAC 2024.0
Question : What interest rate risk does Bank of America describe in its latest annual filing?
Expected : Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and c
Got      : Insufficient information in the provided filings. The retrieved context from Bank of America's latest annual filing (2025 10-K
Scores   : corr=0.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q12 [extractive] BRK-B 2025.0
Question : What was Berkshire Hathaway’s net earnings attributable to shareholders reported in its latest annual report?
Expected : Berkshire Hathaway's net earnings attributable to Berkshire shareholders in fiscal year 2025 were $66,968 million.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q13 [extractive] BRK-B 2023.0
Question : How much did Berkshire Hathaway pay to acquire an additional interest in Pilot Travel Centers in January 2023?
Expected : Berkshire Hathaway acquired an additional 41.4% controlling interest in Pilot Travel Centers for approximately $8.2 billion on January 31, 2023, which was consolidated into financial statements from February 1, 2023.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q14 [extractive] JNJ 2025.0
Question : What were Johnson & Johnson’s total sales for the first nine months of fiscal 2025?
Expected : Johnson & Johnson's total sales for the nine months ended September 28, 2025 were $69,629 million.
Got      : Insufficient information in the provided filings. The retrieved context indicates that "Consolidated statements of earnings for the
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q15 [extractive] JNJ 2025.0
Question : What was Johnson & Johnson’s net earnings in the most recent annual report?
Expected : Johnson & Johnson's net earnings from continuing operations in fiscal year 2025 were $26,804 million.
Got      : Insufficient information in the provided filings. The retrieved context for the most recent annual report (J
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q16 [extractive] UNH 2024.0
Question : What was UnitedHealth Group's medical care ratio for the three months ended June 2024?
Expected : UnitedHealth Group's medical care ratio (MCR) for the three months ended June 30, 2024 was 85.1%, up from 83.2% in Q2 2023, an increase of 1.9 percentage points.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q17 [extractive] UNH 2023.0
Question : What was UnitedHealth Group’s net earnings reported in 2023?
Expected : UnitedHealth Group's net earnings reported in 2023 is $23,144 million.
Got      : Insufficient information in the provided filings. The available filings are quarterly reports for 2023,
Scores   : corr=0.00  faith=1.00  num_acc=0.5
--------------------------------------------------------------------------------

Q18 [extractive] XOM 2023.0
Question : How many oil-equivalent barrels per day did ExxonMobil produce in fiscal year 2023?
Expected : ExxonMobil produced 3,738 thousand oil-equivalent barrels per day
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q19 [extractive] XOM 2025.0
Question : What was the total value of acquisitions completed by ExxonMobil during the third quarter of 2025?
Expected : ExxonMobil completed $2.4 billion in acquisitions consisting primarily of proved and unproved acreage in the Permian basin.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q20 [extractive] CVX 2024.0
Question : What primarily caused Chevron’s international upstream earnings to decrease in the three months ended March 31, 2024?
Expected : Chevron's International Upstream earnings decreased was primarily due to lower natural gas realizations
Got      : International upstream earnings decreased by $702 million, from $4,032 million
Scores   : corr=0.10  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q21 [extractive] CVX 2025.0
Question : What are Chevron’s two primary business segments in 2025?
Expected : Chevron's two primary business segments in 2025 are Upstream and Downstream.
Got      : Chevron's two primary business segments in 2025 are its oil and gas
Scores   : corr=0.10  faith=0.50  num_acc=1.0
--------------------------------------------------------------------------------

Q22 [extractive] WMT 2023.0
Question : What liability did Walmart accrue in fiscal year 2023 for opioid-related settlement agreements?
Expected : During fiscal 2023, Walmart accrued a liability of approximately $3.3 billion for the opioid-related Settlement Framework.
Got      : During fiscal year 2023, Walmart accrued a liability of approximately $3.3 billion for the Settlement Framework and other previously agreed upon state and tribal settlements related to opioid-related litigation [1, 3, 5].
Scores   : corr=1.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q23 [extractive] WMT 2025.0
Question : How many associates did Walmart employ globally in fiscal year 2025?
Expected : Walmart employed approximately 2.1 million associates.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q24 [extractive] COST 2025.0
Question : What was Costco’s total revenue reported in fiscal year 2025?
Expected : Costco's total revenue for fiscal year 2025 was $275,235 million.
Got      : Insufficient information in the provided filings. The context provides total revenue for the 12 weeks ended November 23, 2025, which was $67,307 million [1], but not for the entire fiscal year 2025.
Scores   : corr=0.00  faith=1.00  num_acc=0.5
--------------------------------------------------------------------------------

Q25 [extractive] COST 2023.0
Question : What membership fee revenue did Costco report for the quarter ended November 26, 2023?
Expected : Costco reported membership fee revenue of $1,082 million for the 12 weeks ended November 26, 2023.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q26 [paraphrased] AAPL 2023.0
Question : What amount of revenue did Apple generate during fiscal year 2023?
Expected : Apple's total net sales in fiscal year 2023 were $383,285 million.
Got      : Insufficient information in the provided filings. The retrieved context provides net sales for the nine months ended July
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q27 [paraphrased] AAPL 2025.0
Question : Which regions were impacted by the newly announced U.S. import duties referenced in Apple’s Q3 2025 report?
Expected : According to Apple's Q3 2025 filing, the U.S. imposed additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam, and the European Union.
Got      : Insufficient information in the provided filings. The retrieved context, including Apple's Q3 2025 report [3, 5], does not contain any discussion of newly announced U.
Scores   : corr=0.00  faith=1.00  num_acc=1.0
--------------------------------------------------------------------------------

Q28 [paraphrased] MSFT 2023.0
Question : What potential financial obligations did Microsoft flag in its three-month period ending September 2023?
Expected : Microsoft declared a contingency related to IRS Notices of Proposed Adjustment for tax years 2004–2013, seeking an additional tax payment of $28.9 billion plus penalties and interest due to intercompany transfer pricing issues.
Got      : For the three-month period ending September 2023, Microsoft flagged the potential
Scores   : corr=0.05  faith=0.00  num_acc=0.6666666666666666
--------------------------------------------------------------------------------

Q29 [paraphrased] MSFT 2023.0
Question : Which of Microsoft’s operating divisions contributed the largest share of revenue in the most recent fiscal year?
Expected : Intelligent Cloud generated the highest revenue with $87,907 million in fiscal year 2023.
Got      : Insufficient information in the provided filings. The context provides revenue increases and growth percentages for various products and services, such as Microsoft 365 Commercial products and cloud services [1, 2, 6, 7] and Productivity and Business Processes [5], but it does not provide the total
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q30 [paraphrased] NVDA 2025.0
Question : What factor does Nvidia identify that could delay the recognition of Data Center revenue in fiscal year 2025?
Expected : Customers may delay adopting new architectures if their data centre infrastructure is not ready.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q31 [paraphrased] NVDA 2024.0
Question : What proportion of Nvidia’s revenue remained as gross profit during fiscal year 2024?
Expected : Nvidia's gross margin was 72.7% in FY2024, up from 56.9% in FY2023.
Got      : Insufficient information in the provided filings. The retrieved context does not contain the necessary figures for Nvidia
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q32 [paraphrased] NVDA 2025.0
Question : What was the size of Nvidia's workforce at the close of its 2025 annual period?
Expected : As of the end of fiscal year 2025, Nvidia had approximately 36,000 employees in 38 countries; 27,100 in research and development and 8,900 in sales, marketing, operations and administrative positions.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q33 [paraphrased] JPM 2023.0
Question : What Common Equity Tier 1 capital ratio did JPMorgan report at the end of fiscal year 2023?
Expected : JPMorgan's Standardized and Advanced CET1 capital ratios were both 15.0% at end of FY2023, with CET1 capital of $251 billion.
Got      : JPMorgan reported a Common Equity Tier 1 (CET1) capital ratio of 15.0% at the end of fiscal year 2023 [6].
Scores   : corr=1.00  faith=1.00  num_acc=0.8
--------------------------------------------------------------------------------

Q34 [paraphrased] JPM 2024.0
Question : What government body had oversight responsibility over JPMorgan Chase's holding company structure in 2024?
Expected : JPMorgan Chase is supervised and regulated by the Federal Reserve as a bank holding company.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q35 [paraphrased] BAC 2025.0
Question : What was the aggregate sum of all debts and obligations owed by Bank of America as of September 2025?
Expected : Bank of America's total liabilities as of September 30, 2025 were $3,099,564 million.
Got      : Insufficient information in the provided filings. The retrieved context includes a Condensed Balance Sheet for Bank of America as of December 31, 2025, but not for September 2025 [3].
Scores   : corr=0.00  faith=1.00  num_acc=0.3333333333333333
--------------------------------------------------------------------------------

Q36 [paraphrased] BAC 2024.0
Question : How does Bank of America characterise the threat posed by fluctuating borrowing costs in its 2024 annual period?
Expected : Bank of America manages interest rate risk through an overall strategy incorporating derivatives and cash instruments to manage fluctuations in earnings and capital caused by interest rate volatility, with the goal that movements in interest rates do not significantly adversely affect earnings and c
Got      : Insufficient information in the provided filings. The retrieved context mentions "Item 1A - Risk Factors
Scores   : corr=0.00  faith=1.00  num_acc=nan
--------------------------------------------------------------------------------

Q37 [paraphrased] BRK-B 2025.0
Question : What was the total profit that Berkshire Hathaway recorded for the most recent yearly report?
Expected : Berkshire Hathaway's net earnings attributable to Berkshire shareholders in fiscal year 2025 were $66,968 million.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q38 [paraphrased] BRK-B 2023.0
Question : How much did Berkshire Hathaway spend in January 2023 to buy out the remaining ownership stake in Pilot Travel Centers?
Expected : Berkshire Hathaway acquired an additional 41.4% controlling interest in Pilot Travel Centers for approximately $8.2 billion on January 31, 2023, which was consolidated into financial statements from February 1, 2023.
Got      : Insufficient information in the provided filings.
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q39 [paraphrased] JNJ 2025.0
Question : How much revenue did Johnson & Johnson generate during the first three quarters of fiscal year 2025?
Expected : Johnson & Johnson's total sales for the nine months ended September 28, 2025 were $69,629 million.
Got      : Insufficient information in the provided filings. The retrieved context indicates that "Consolidated statements of earnings for
Scores   : corr=0.00  faith=1.00  num_acc=0.0
--------------------------------------------------------------------------------

Q40 [paraphrased] JNJ 2025.0

In [29]:
# Step 3 — Retrieval vs Generation diagnosis
hi_faith_lo_corr = advanced_df[
    (advanced_df["llm_faithfulness_score"] >= 0.6) &
    (advanced_df["llm_correctness_score"]  <  0.3)
]
lo_faith_lo_corr = advanced_df[
    (advanced_df["llm_faithfulness_score"] <  0.4) &
    (advanced_df["llm_correctness_score"]  <  0.3)
]
hi_both = advanced_df[
    (advanced_df["llm_faithfulness_score"] >= 0.6) &
    (advanced_df["llm_correctness_score"]  >= 0.6)
]

print("=== RETRIEVAL vs GENERATION DIAGNOSIS ===")
print(f"Wrong chunks retrieved  (faith↑ corr↓) : {len(hi_faith_lo_corr)} — finding irrelevant content")
print(f"Hallucination / no ctx  (faith↓ corr↓) : {len(lo_faith_lo_corr)} — LLM making things up")
print(f"Working correctly       (faith↑ corr↑) : {len(hi_both)}")

=== RETRIEVAL vs GENERATION DIAGNOSIS ===
Wrong chunks retrieved  (faith↑ corr↓) : 61 — finding irrelevant content
Hallucination / no ctx  (faith↓ corr↓) : 4 — LLM making things up
Working correctly       (faith↑ corr↑) : 32